### ISSUE TITLE
running deploy.py does not return private_key

### ISSUE THREAD

**Issue by j-ananto** [smartcontractkit/full-blockchain-solidity-course-py#1006]
Hello again,

My issue comes when I try to run deploy.py, even after having the code exactly like the video. Included a .env file and .gitignore.
Triple-checked for any errors, but print(private_key) still returns none. I also already installed python-dotenv and run load_dotenv.

echo $PRIVATE_KEY gives me the mnemonic phrase.

It gives me the following error message:

```
return binascii.unhexlify(ascii_hex)
binascii.Error: Non-hexadecimal digit found
```

**Comment by Magofoco** [comment]
This might be helpful:
https://ethereum.stackexchange.com/questions/98811/error-non-hexadecimal-digit-found

**Comment by j-ananto** [comment]
Hey @bot-eth-dev,

Thanks for the reply, but it's still giving me the same error message.

```
return binascii.unhexlify(ascii_hex)
binascii.Error: Non-hexadecimal digit found
```

**Comment by NoobGamesDev** [comment]
I ran into the same issue. By changing the Ganache rpc server hostname from 127.0.... to 192.168... You'll be able to work through :)

Hope anyone running into this issue, will be able to resolve this by switching the hostname. It's not related to the key (or dot-env) itself.
