### ISSUE TITLE
FRPM WEB3 IMPORT WEB3

### ISSUE THREAD

**Issue by AlrohfAZ** [smartcontractkit/full-blockchain-solidity-course-py#1035]
I have installed web3 and importeed it but when I run the code I get this error;
 from web3 import Web3
ModuleNotFoundError: No module named 'web3'
This is the code;
from solcx import compile_standard
import json
from web3 import Web3

with open("./simplestorage.sol", "r") as file:
    simple_storage_file = file.read()

# Compile Our Solidity

compiled_sol = compile_standard(
    {
        "language": "Solidity",
        "sources": {"simplestorage.sol": {"content": simple_storage_file}},
        "settings": {
            "outputSelection": {
                "*": {"*": ["abi", "metadata", "evm.bytecode", "evn.sourceMap"]}
            }
        },
    },
)

with open("compiled_code.json", "w") as file:
    json.dump(compiled_sol, file)

# To get a contract, you need to get the bytecode and ABI

# get bytecode
bytecode = compiled_sol["contracts"]["simplestorage.sol"]["SimpleStorage"]["evm"][
    "bytecode]"
]["object"]

# get abi
abi = compiled_sol["contracts"]["simplestorage.sol"]["SimpleStorage"]["abi"]

# for connecting to ganache
w3 = Web3(Web3.HTTPProvider("http://127.0.0.1:7545"))
chain_id = 5777
my_address = "0x73fb3a2E8045564ea58eF41f878b65868dEb8A12"
private_key = "0x827a6a94d43bd7a36e27e4df5c9f491679d3fa4f946129dbe737cd683f307f4f"

# Create the contract in python
SimpleStorage = w3.eth.contract(abi=abi, bytecode=bytecode)
print(SimpleStorage)

**Comment by AlrohfAZ** [comment]
I did not run it in the terminal, made it a cell and had to install ipython but after running the code worked. I am still receiving the same error in the terminal, is that a problem?

**Comment by AlrohfAZ** [comment]
Still having issues with web3, need help as soon as possible please.

**Comment by david-randoll** [comment]
you need to add "install_solc" to your import then before you call "compile_standard" you need to call install_solc with the version of solidity. See below.

`from solcx import compile_standard, install_solc

# Compile our solidity
install_solc("0.6.0")
compile_sol = compile_standard(
    {
        "language": "Solidity",
        "sources": {"SimpleStorage.sol": {"content": simple_storage_file}},
        "settings": {
            "outputSelection": {
                "*": {"*": ["abi", "metadata", "evm.bytecode", "evm.sourceMap"]}
            }
        },
    },
    solc_version="0.6.0",
)
`
