### ISSUE TITLE
Lesson 4: FileNotFoundError: [Errno 2] No such file or directory: 'ganache-cli'

### ISSUE THREAD

**Issue by the-intro-vert** [smartcontractkit/full-blockchain-solidity-course-py#1039]
Hey guys, 
After writing the deploy script when I run the following command to deply the contract on ganache, the terminal threw an error saying:  **FileNotFoundError: [Errno 2] No such file or directory: 'ganache-cli'**

Please help me with this error. Below is the error that I'm getting from the past 5 hours. Please have a look.

----------------------------------------------------------------------------------

rishavsharma@Rishavs-Air brownie_simple_storage % brownie run /scripts/deploy.py
Brownie v1.16.4 - Python development framework for Ethereum

BrownieSimpleStorageProject is the active project.

Launching 'ganache-cli --port 8545 --gasLimit 12000000 --accounts 10 --hardfork istanbul --mnemonic brownie'...
  File "brownie/_cli/__main__.py", line 64, in main
    importlib.import_module(f"brownie._cli.{cmd}").main()
  File "brownie/_cli/run.py", line 43, in main
    network.connect(CONFIG.argv["network"])
  File "brownie/network/main.py", line 50, in connect
    rpc.launch(active["cmd"], **active["cmd_settings"])
  File "brownie/network/rpc/__init__.py", line 75, in launch
    self.process = self.backend.launch(cmd, **kwargs)
  File "brownie/network/rpc/ganache.py", line 73, in launch
    return psutil.Popen(cmd_list, stdin=DEVNULL, stdout=out, stderr=out)
  File "psutil/__init__.py", line 1312, in __init__
    self.__subproc = subprocess.Popen(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ganache-cli'

**Comment by the-intro-vert** [comment]
Hey there,
Thanks for your reply :)

Yes, I am using a macOS. I tried doing what you advised but I am still getting the same error.

<img width="1429" alt="Screenshot 2022-02-13 at 4 18 46 PM" src="https://user-images.githubusercontent.com/63146727/153749726-e0c5c37b-060a-4a84-8a87-547612e7ca62.png">

**Comment by the-intro-vert** [comment]
> Hey there, Thanks for your reply :)
> 
> Yes, I am using a macOS. I tried doing what you advised but I am still getting the same error.
> 
> <img alt="Screenshot 2022-02-13 at 4 18 46 PM" width="1429" src="https://user-images.githubusercontent.com/63146727/153749726-e0c5c37b-060a-4a84-8a87-547612e7ca62.png">
> 
> And when I changed my python interpreter, another issue popped up. I don't know if this would we of any help. Please let me know if you need me to try anything else. I am banging my head from last night. Heeeelp!!!
> 
> <img alt="Screenshot 2022-02-13 at 4 21 18 PM" width="1033" src="https://user-images.githubusercontent.com/63146727/153749792-0acee060-ea4b-4c3d-9ae0-f91251e6ac25.png">
@bot-eth-dev

**Comment by PatrickAlphaC** [comment]
Have you installed `ganache-cli`? https://www.npmjs.com/package/ganache-cli

**Comment by PatrickAlphaC** [comment]
What happens when you run:

```
ganache-cli --version
```

**Comment by the-intro-vert** [comment]
I am getting the same error @PatrickAlphaC
It says `zsh: command not found: ganache-cli

<img width="661" alt="Screenshot 2022-02-16 at 11 01 05 PM" src="https://user-images.githubusercontent.com/63146727/154322316-3f8400b3-a88e-4a62-bfbd-ba5a66f90a6e.png">
`

**Comment by PatrickAlphaC** [comment]
Did you gloabally install?

```
npm install -g ganache-cli
```

**Comment by kjones86** [comment]
I am having the same issue @the-intro-vert. I think I posted this on your personal account @PatrickAlphaC thinking that I waS posting it here, sorry about that! I think the issue is with npm. It says that we can fix by creating a directory for global installations, setting npm to config the directory and add the npm-global/bin to the path of OS. The steps didn't work for me because the file I created could not be located (grr) but maybe they will work for you. I am interested in seeing if that helps. Here is the link https://docs.npmjs.com/getting-started/fixing-npm-permissions.

**Comment by the-intro-vert** [comment]
> https://docs.npmjs.com/getting-started/fixing-npm-permissions

I did all these things for like 5 days. The final result doesn't change.

I agree with @kjones86 (and thank you so much for taking out time to give such wonderful suggestion) that the problem is with NPM. Now, I am trying to follow the recommendation by him. Hopefully this thing will work out.

I am grateful to receive personal guidance from you @PatrickAlphaC Patrick. I hope we'll figure the solution for this problem :)

**Comment by the-intro-vert** [comment]
I hereby confirm that the suggestion that @kjones86 gave WORKED!!!!!
I **installed nvm** and **then installed a different version of npm** that was **v14.19.0**. I ran the command again and it worked like charm.

Thank you K. Jones for helping us out :)

You are a saviour my friend. I have been struggling with this issue for almost a week now. Thanks again.
