### ISSUE TITLE
Brownie is not detecting the GUI

### ISSUE THREAD

**Issue by DieKant** [smartcontractkit/full-blockchain-solidity-course-py#105]
Title, course at 5:37:??, it does start the ganache-cli as usual tho, so there is no errors in deploying contracts and mocks but I don't understand why it behaves like this.

I can attach a video of the problem if needed

**Comment by PatrickAlphaC** [comment]
Could you paste an output of what it exports?

**Comment by DieKant** [comment]
![image](https://user-images.githubusercontent.com/61691496/134987642-4f9366e6-cdc8-4604-afd5-f2f75ecdd9cb.png)
This is the output I get

**Comment by Hamze24w** [comment]
I have the same issue

**Comment by DieKant** [comment]
Hi @PatrickAlphaC, @Hamze24w 

I figured out why it doesn't work, the ganache GUI and CLI MUST HAVE the same network id and ip:port, just need to change this parameters on one of the two versions and it works like in the course

So the issue is solved and I think this issue can be closed
