### ISSUE TITLE
if folder is named 'web3' - gives error

### ISSUE THREAD

**Issue by mekhiya** [smartcontractkit/full-blockchain-solidity-course-py#1196]
Can you please explain why it gives error in first case :

**Case 1)  first created brownie project at location**
/f/web3/brownie_simple_storage 

`brownie run scripts\deploy.py`

throws error
**ModuleNotFoundError: No module named 'web3.brownie_simple_storage'**

![error-message](https://user-images.githubusercontent.com/8952786/156229355-99cdcdf4-5a7b-4fe4-9cda-316f977604c6.jpg)

**Case 2) changed name of the folder from "web3" to "web3-projects"**

 /f/web3-projects/brownie_simple_storage

`brownie run scripts\deploy.py`

ALL WORKS FINE.

I wasted so much time on this, just found this by flook.

How does naming folder name to web3, cause problem ?????

**Comment by cromewar** [comment]
web3 is a reserved word like saying `int` or `for` so brownie is going to freak out if you name it like that.
Better explanation: web3 does exists on your python installed  packages, and brownie does not now where is it if you use the exact same name on your project folder.

**Comment by mekhiya** [comment]
Understood. Thank you for info!
