### ISSUE TITLE
Lesson 3: How to find the ETH/USD price feed address on Rinkeby?

### ISSUE THREAD

**Issue by eiyen** [smartcontractkit/full-blockchain-solidity-course-py#1200]
Video Progress: [2:45:06](https://youtu.be/M576WGiDBdQ?t=9906)

### Question Description

I can't find the address through [the provided link](https://docs.chain.link/docs/reference-contracts/) because the interface has changed after 6 months of updates.

Interface 6 months ago: 
![image](https://user-images.githubusercontent.com/52303623/156879481-33311d22-357c-4299-b5b8-d720aaf6b827.png)

Now the Interface:
![image](https://user-images.githubusercontent.com/52303623/156879494-ac5f7f0c-5193-43de-9a13-1d2e1e31ba5a.png)

### What I've Tried

I can only get the address through the [chainlink solidity sample](https://docs.chain.link/docs/get-the-latest-price/#solidity). However, only the ETH/USD converion rates can be fetched through this method.

And I've searched a lot of keywords but can't find the solution.

Those are my questions. Any help would be appreciated.

**Comment by kjones86** [comment]
You're in the right place, just scroll down to eth/usd. You can also get the data pricefeed from the code in the repository.

**Comment by eiyen** [comment]
> You're in the right place, just scroll down to eth/usd. 

Yes, you're right! It's indeed in [Ethereum Data Feeds](https://docs.chain.link/docs/ethereum-addresses/). The reason why I can't find the address is because I didn't switch on the global mode of my VPN.

> You can also get the data pricefeed from the code in the repository.

That's ture, they're exactly the same address.

Thanks a lot for your answer!
