### ISSUE TITLE
Can't deploy to rinkeby.

### ISSUE THREAD

**Issue by CWalton16** [smartcontractkit/full-blockchain-solidity-course-py#1202]
Ive been trying to deploy a contract to the Rinkeby testnet but nothing seems to happen.

The contract im trying to deploy is from called simpleStorage.sol which is simple and doesn't rely on any external addresses.

Everything works perfectly on my local ganache cli, so  I know the contract itself is fine, but when I run the same deploy script on rinkeby nothing seems to happen and I get the following output in the terminal before having to stop the script after like 1hr+

Thanks in advance.

```
    (base) MacBook-Pro:Lesson5_SimpleStorage_Brownie $ brownie run scripts/deploy.py --network rinkeby
    Brownie v1.16.4 - Python development framework for Ethereum
    
    Lesson5SimplestorageBrownieProject is the active project.
    
    Running 'scripts/deploy.py::main'...
    Deploying contracts...
    Current developer account: 0x45003E..... 
    Balance: 0.3



```

 ```Python
 from brownie import accounts, config, network, SimpleStorage
    import os
    
    def deploy_simple_storage():
    
        #Method 1: Load account
        account = get_account()
        print("Current developer account:", account)
        print("Balance:", account.balance()/(10**18))
        print("\n\n")
    
        #Deploy the contract - No need to get the abi e.t.c...
        simple_storage = SimpleStorage.deploy({"from": account})
        print("Contract is deployed.")

    
    
    def get_account():
    
        #If network is a development one then take straight from the accounts arrays
        if (network.show_active() == "development"):
            return accounts[0]
        else:
            return accounts.add(config["wallets"]["from_key"])
    
    
    def main():
        print("Deploying contracts...")
        deploy_simple_storage()

```

**UPDATE:** 
I have even tried to add the account 'manually' via
`brownie accounts new 0`
And changing the account in the deploy.py script to be:
`account = accounts.load("0")`

I have also opened a brownie console on the Rinkeby network and simply tried to transfer eth and that doesn't seem to work either.
```
$ brownie console --network rinkeby
>>> account = accounts.load("0")
Enter password for "0": 
>>> print(account.balance()/(10**18))
0.4
>>> account.transfer("0xAnotherPublicAddress", "0.1 ether")
```
I am left waiting for eternity until I have to force quit the execution. Nothing shows up on the Rinkeby blockchain explorer and when I log into the associated infer account it shows there's been 100+ calls today.

**Comment by CWalton16** [comment]
Hi, so from the looks of it I have the correct implementation with the difference of using ${PRIVATE_KEY} instead of a hexadecimal literal. My question is if I didn't import it correctly then how would my script print my balance or 0.3 eth on Rinkeby correctly?

**Comment by CWalton16** [comment]
**SOLVED:**
Not sure how but I managed to resolve this is issue by using x86 python environments via conda as the ARM64 python3 environments  don't seem to allow me to do this

**Comment by cromewar** [comment]
So it was a problem with the environment at the end, nice to know and nice catch.
Closing this now.
