### ISSUE TITLE
Two simple questions.

### ISSUE THREAD

**Issue by fps8k** [smartcontractkit/full-blockchain-solidity-course-py#1217]
### **Hello there, I started writing solidity following the teachings of the teacher here. Up to the brownie point and I have two simple questions.**

1. > - Must all code inside the python files in the brownie project directory be in functions?

```
i.e
def function_name():
    # code
```

2. > - Assuming I have a file named X.sol and in it a contract named "contract Y { // code here}", and I have compiled this file, what do I import into my brownie project?

```
from brownie import X

or

from brownie import Y
```

**Comment by cromewar** [comment]
Hello @fps8k 
1. Yes, python need at least a `main()` function in order to work usually refer to [this](https://www.freecodecamp.org/news/if-name-main-python-example/).
2. `from brownie import Y` but is better to use the exact same name on the contract file and on the contract name.
