### ISSUE TITLE
lesson 1 issue 

### ISSUE THREAD

**Issue by Jimel-Lalla** [smartcontractkit/full-blockchain-solidity-course-py#124]
I keep getting this whenever I press the people button after I deploy the code looks good. This is after coding the array where you have four buttons showing addperson, store, people and retrieve.

 [call] from: 0x5B38Da6a701c568545dCfcB03FcB875f56beddC4to: SimpleStorage.people(uint256)data: 0x9e7...00000
call to SimpleStorage.people errored: VM error: invalid opcode.

invalid opcode
	
	The execution might have thrown.

Debug the transaction to get more information.

![error in code](https://user-images.githubusercontent.com/91536830/135556655-af496c52-f0d1-40b1-9df8-822bf7f7371f.JPG)

**Comment by PatrickAlphaC** [comment]
@Jimel-Lalla what was the resolution here?
