### ISSUE TITLE
pip install web3 not working

### ISSUE THREAD

**Issue by anonymous23437** [smartcontractkit/full-blockchain-solidity-course-py#1243]
ERROR: Command errored out with exit status 1:
   command: 'C:\Program Files\Python310\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\SmartCom\\AppData\\Local\\Temp\\pip-install-srqukzfj\\bitarray_23686d8ec9554d73aff7a38f75b83508\\setup.py'"'"'; __file__='"'"'C:\\Users\\SmartCom\\AppData\\Local\\Temp\\pip-install-srqukzfj\\bitarray_23686d8ec9554d73aff7a38f75b83508\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\SmartCom\AppData\Local\Temp\pip-wheel-lewwb3by'
       cwd: C:\Users\SmartCom\AppData\Local\Temp\pip-install-srqukzfj\bitarray_23686d8ec9554d73aff7a38f75b83508\
  Complete output (13 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.10
  creating build\lib.win-amd64-3.10\bitarray
  copying bitarray\test_bitarray.py -> build\lib.win-amd64-3.10\bitarray
  copying bitarray\test_util.py -> build\lib.win-amd64-3.10\bitarray
  copying bitarray\util.py -> build\lib.win-amd64-3.10\bitarray
  copying bitarray\__init__.py -> build\lib.win-amd64-3.10\bitarray
  running build_ext
  building 'bitarray._bitarray' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for bitarray

**Comment by tayyipcanbay** [comment]
You have to install this:C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
ı got the same error it works for me
