### ISSUE TITLE
Dont know why web3 is not installing

### ISSUE THREAD

**Issue by shreyanshk804** [smartcontractkit/full-blockchain-solidity-course-py#1263]
ERROR: Command errored out with exit status 1:
     command: 'c:\users\kiit\appdata\local\programs\python\python38\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\KIIT\\AppData\\Local\\Temp\\pip-install-e3ut1n3e\\cytoolz_65cd00d0b8b545b4a19681fef245d796\\setup.py'"'"'; 
__file__='"'"'C:\\Users\\KIIT\\AppData\\Local\\Temp\\pip-install-e3ut1n3e\\cytoolz_65cd00d0b8b545b4a19681fef245d796\\setup.py'"'"';f 
= getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\KIIT\AppData\Local\Temp\pip-record-_d15dk00\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\kiit\appdata\local\programs\python\python38\Include\cytoolz'
         cwd: C:\Users\KIIT\AppData\Local\Temp\pip-install-e3ut1n3e\cytoolz_65cd00d0b8b545b4a19681fef245d796\
    Complete output (49 lines):
    ALERT: Cython not installed.  Building without Cython.
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\compatibility.py -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\_signatures.py -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\_version.py -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\__init__.py -> build\lib.win-amd64-3.8\cytoolz
    creating build\lib.win-amd64-3.8\cytoolz\curried
    copying cytoolz\curried\exceptions.py -> build\lib.win-amd64-3.8\cytoolz\curried
    copying cytoolz\curried\operator.py -> build\lib.win-amd64-3.8\cytoolz\curried
    copying cytoolz\curried\__init__.py -> build\lib.win-amd64-3.8\cytoolz\curried
    copying cytoolz\dicttoolz.pyx -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\functoolz.pyx -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\itertoolz.pyx -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\recipes.pyx -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\utils.pyx -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\cpython.pxd -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\dicttoolz.pxd -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\functoolz.pxd -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\itertoolz.pxd -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\recipes.pxd -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\utils.pxd -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\__init__.pxd -> build\lib.win-amd64-3.8\cytoolz
    creating build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\dev_skip_test.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_compatibility.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_curried.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_curried_toolzlike.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_dev_skip_test.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_dicttoolz.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_docstrings.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_doctests.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_embedded_sigs.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_functoolz.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_inspect_args.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_itertoolz.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_none_safe.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_recipes.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_serialization.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_signatures.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_tlz.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_utils.py -> build\lib.win-amd64-3.8\cytoolz\tests
    running build_ext
    building 'cytoolz.dicttoolz' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\kiit\appdata\local\programs\python\python38\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\KIIT\\AppData\\Local\\Temp\\pip-install-e3ut1n3e\\cytoolz_65cd00d0b8b545b4a19681fef245d796\\setup.py'"'"'; __file__='"'"'C:\\Users\\KIIT\\AppData\\Local\\Temp\\pip-install-e3ut1n3e\\cytoolz_65cd00d0b8b545b4a19681fef245d796\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\KIIT\AppData\Local\Temp\pip-record-_d15dk00\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\kiit\appdata\local\programs\python\python38\Include\cytoolz' Check the logs for full command output.

**Comment by cromewar** [comment]
Hello @shreyanshk804 
This is the cytools error, here you have the solution:
https://github.com/smartcontractkit/full-blockchain-solidity-course-py/blob/main/chronological-issues-from-video.md#python-related-issues
