### ISSUE TITLE
supportedChain is deprecated, please pass networks instead

### ISSUE THREAD

**Issue by capit0** [smartcontractkit/full-blockchain-solidity-course-py#1283]
I am at the final lesson and I get an error in my localhost console:

```
supportedChain is deprecated, please pass networks instead
useConfig @ context.ts:23
```

At first I thought it might have something to do with my code, but I copy pasted all of the code out of the github and I still got the message. Does anyone know what is wrong?

Also, I get the following parsing error:

```
Failed to parse source map from '/mnt/c/users/user/documents/blockchain/sizzlingstaking/front_end/node_modules/@metamask/detect-provider/src/index.ts' file: Error: ENOENT: no such file or directory, open '/mnt/c/users/user/documents/blockchain/sizzlingstaking/front_end/node_modules/@metamask/detect-provider/src/index.ts'
```

Is that a package issue?

**Comment by cromewar** [comment]
Yes SupportedChain is deprecated
first install this: https://www.npmjs.com/package/@metamask/detect-provider
also check usedapp docs to know how to use networks :
https://usedapp-docs.netlify.app/docs/core

**Comment by ico-Meng** [comment]
The second link of @cromewar can resolve this issue. Doc updated.

**Comment by cromewar** [comment]
I'm glad is solved.

**Comment by DanielCawley** [comment]
https://usedapp-docs.netlify.app/docs/core 
this link says page not found
