### ISSUE TITLE
Brownie does not import OpenZeppelin onlyOwner

### ISSUE THREAD

**Issue by DieKant** [smartcontractkit/full-blockchain-solidity-course-py#133]
Course at 6:32:??

It's probably just a distraction error but I can't seem to understand what I'm doing wrong, I can't compile Lottery.sol, these are my import and dependecies, what am I missing?

![image](https://user-images.githubusercontent.com/61691496/135723502-2cf40a5f-084d-494f-ba9d-0aa8fff25324.png)
![image](https://user-images.githubusercontent.com/61691496/135723529-160e04db-785c-4e3c-871c-43418ef6d0bd.png)

Thanks

**Comment by PatrickAlphaC** [comment]
Could you try copy pasting from the example code here?

**Comment by DieKant** [comment]
Hi Patrick, copy pasting your code didn't work, however,`<a href="https://github.com/OpenZeppelin/openzeppelin-contracts/releases"> at this link</a>` which contains the versions of the openzeppelin contract the version 3.4.0 does not exist.

Should I change it to another version?

**Comment by DieKant** [comment]
I copied the code a second time and it worked...... I really don't know what the frick is happening because I swear it's identical I checked letter per letter....

Well for anyone with the same issue try to copy and paste the code from this 2 links until it works ahhahahahaha
https://github.com/PatrickAlphaC/smartcontract-lottery/blob/main/contracts/Lottery.sol
https://github.com/PatrickAlphaC/smartcontract-lottery/blob/main/brownie-config.yaml

**Comment by PatrickAlphaC** [comment]
Sometimes weird stuff can sneak up on you! Glad you got it solved!

**Comment by quest313** [comment]
I had the same error and it was also driving me crazy... when I finally figured it out.. you had the same issue. dependencies was misspelled in your yaml.
