### ISSUE TITLE
Error installing ganache-cli on Windows 11 using yarn package manager (4:20:09) [works with npm install -g]

### ISSUE THREAD

**Issue by cryptomatcat** [smartcontractkit/full-blockchain-solidity-course-py#135]
Installing ganache-cli with yarn package manager on Windows 11 and doing the **ganache-cli --version** returned : 
**ganache-cli: command not found**.

Using **npm install -g ganache-cli** it worked perfectly.

**Comment by DieKant** [comment]
Hi, I had the same issue on windows 10 and even npm didn't work for me,I updated my PATH env variable adding C:\Users\YourUser\AppData\Local\Yarn\bin and it fixed the problem

Hope it helps

Best regards

**Comment by PatrickAlphaC** [comment]
Thanks both of you! Closing this issue for now, feel free to follow up.
