### ISSUE TITLE
Lesson 7: Returned 0 items while testing entrance fee with current price 

### ISSUE THREAD

**Issue by spo0ds** [smartcontractkit/full-blockchain-solidity-course-py#1402]
brownie-config.yaml

![Screenshot at 2022-04-13 19-24-25](https://user-images.githubusercontent.com/98577089/163195666-fa5b9f87-f924-446d-869d-b0101c004545.png)

test-lottery.py

![Screenshot at 2022-04-13 19-24-48](https://user-images.githubusercontent.com/98577089/163195694-b103648a-7998-4901-9b20-758b187dd857.png)

output while running test

![Screenshot at 2022-04-13 19-26-56](https://user-images.githubusercontent.com/98577089/163196065-3b937e22-ea21-41c7-aef0-6317d1e2aed6.png)

**Comment by cromewar** [comment]
Hello @spo0ds 
well the test is ignoring completely your script it seems,
could you please be sure the test script is located on the tests folder and also the file name start with the keyword `test`?

**Comment by spo0ds** [comment]
I made some naming error lol.I fixed it and it runs fine now.Thanks btw.Happy learning :)
