### ISSUE TITLE
account not printing()

### ISSUE THREAD

**Issue by akin-gianfrancesco** [smartcontractkit/full-blockchain-solidity-course-py#1406]
from brownie import accounts

def deploy_simple_storage():
    account = account[0]
    print(account)

def main():
    deploy_simple_storage()

------------------------

I can't manage to print the account details

**error message**

UnboundLocalError: local variable 'account' referenced before assignment

Think it has something to do with brownie being underlined yellow, not in green as seen @ 4:36

If anyone could help, much appreciated.

Cheers

**Comment by andraze** [comment]
I'm not sure about brownie being underlined yellow, but you use `account[0]` instead of **`accounts[0]`** (plural).
But you don't have a variable for `account[0]` → that's what the error message talks about.
Check if this works :)

```
from brownie import accounts

def deploy_simple_storage():
    account = accounts[0]
    print(account)

def main():
    deploy_simple_storage()
```

**Comment by akin-gianfrancesco** [comment]
Thank you! sometimes just need a break to see the silly, simple little problem
