### ISSUE TITLE
LESSON6 - Brownie - FundMe: ValueError: constructor Sequence has incorrect length, expected 1 but got 0

### ISSUE THREAD

**Issue by DorianDaSilva** [smartcontractkit/full-blockchain-solidity-course-py#1407]
Hello everyone, 

I have been trying to figure out why I get 
`ValueError: constructor Sequence has incorrect length, expected 1 but got 0` 
when running cmd line
`brownie run scripts/deploy.py --network rinkeby`

I have tried all solutions found online plus some experiments on my end but none returned the expected result.

Can anyone take a look at my code below and help me fix the script so I can deploy my contracts on Rinkeby testnet using brownie, please?

**Deploy.py script**   

    from brownie import FundMe
    from scripts.helpful_scripts import get_account

    def deploy_fund_me():
        account = get_account()
        fund_me = FundMe.deploy({"from": account})
        print(f"contract deployed to {fund_me.address}")

    def main():
        deploy_fund_me()

**Helpful_scripts.py script**

    from brownie import network, config, accounts

    def get_account():
        if network.show_active() == "development":
            return accounts[0]
        else:
            return accounts.add(config["wallets"]["from_key"])

**Brownie-config.yaml script**

    dependencies:
      - smartcontractkit/chainlink-brownie-contracts@1.1.1

    compiler:
      solc:
      remapping:
        - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'

    dotenv: .env
    wallets:
      from_key: ${PRIVATE_KEY}

**.env script**

    export PRIVATE_KEY=0xc8......13081
    export WEB3_INFURA_PROJECT_ID=6147.....5f55e

**Comment by IonMindGit** [comment]
**Below is my FundMe contract - It seems the issue is with the constructor**

     contract FundMe {

        using SafeMath96 for uint256;`

        mapping(address => uint256) public addressToAmountFunded;
        address[] public funders;
        address public owner;
        AggregatorV3Interface public priceFeed;

        constructor(address _priceFeed) {
            priceFeed = AggregatorV3Interface(_priceFeed);
            owner = msg.sender;
        }

        function fund() public payable {
            uint256 minimumUSD = 50 * 10**18;
            require(
                getConversionRate(msg.value) >= minimumUSD,
                "You need to spend more ETH!"
            );
            addressToAmountFunded[msg.sender] += msg.value;
            funders.push(msg.sender);
        }

        function getVersion() public view returns (uint256) {
            return priceFeed.version();
        }

        function getPrice() public view returns (uint256) {
            (, int256 answer, , , ) = priceFeed.latestRoundData();
            return uint256(answer * 10000000000);
        }

        // 1000000000
        function getConversionRate(uint256 ethAmount)
            public
            view
            returns (uint256)
        {
            uint256 ethPrice = getPrice();
            uint256 ethAmountInUsd = (ethPrice * ethAmount) / 1000000000000000000;
            return ethAmountInUsd;
        }

        function getEntranceFee() public view returns (uint256) {
            // minimumUSD
            uint256 minimumUSD = 50 * 10**18;
            uint256 price = getPrice();
            uint256 precision = 1 * 10**18;
            // return (minimumUSD * precision) / price;
            // We fixed a rounding error found in the video by adding one!
            return ((minimumUSD * precision) / price) + 1;
        }

        modifier onlyOwner() {
            require(msg.sender == owner);
            _;
        }

        function withdraw() public payable onlyOwner {
            payable(msg.sender).transfer(address(this).balance);

            for (
                uint256 funderIndex = 0;
                funderIndex < funders.length;
                funderIndex++
            ) {
                address funder = funders[funderIndex];
                addressToAmountFunded[funder] = 0;
            }
            funders = new address[](0);
        }
    }
`
