### ISSUE TITLE
Lesson 7: Error when deploying: 'The execution failed due to an exception.'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually

### ISSUE THREAD

**Issue by shashankvivek** [smartcontractkit/full-blockchain-solidity-course-py#1410]
I am getting below error when ending the lottery.  Can someone please help me understand and resolve this ? I have my code [here](https://github.com/shashankvivek/blockchain/tree/main/smartLottery_contract_revisited)

I tried to look over internet but no luck there !

It seems like the problem is happening on `lottery.endLottery({"from": account})`  inside `scripts\deploy_lottery.py`

> 'The execution failed due to an exception.'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually

```
Funded link to contract
  LinkToken.transfer confirmed   Block: 31008876   Gas used: 52458 (90.91%)

  File "C:\Users\snitw\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\_cli\run.py", line 51, in main
    return_value, frame = run(
  File "C:\Users\snitw\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\project\scripts.py", line 103, in run
    return_value = f_locals[method_name](*args, **kwargs)
  File ".\scripts\deploy_lottery.py", line 51, in main
    end_lottery()
  File ".\scripts\deploy_lottery.py", line 42, in end_lottery
    end_tx = lottery.endLottery({"from": account})
  File "C:\Users\snitw\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\network\contract.py", line 1710, in __call__
    return self.transact(*args)
  File "C:\Users\snitw\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\network\contract.py", line 1583, in transact
    return tx["from"].transfer(
  File "C:\Users\snitw\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\network\account.py", line 644, in transfer
    receipt, exc = self._make_transaction(
  File "C:\Users\snitw\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\network\account.py", line 727, in _make_transaction
    raise VirtualMachineError(e) from None
  File "C:\Users\snitw\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\exceptions.py", line 93, in __init__
    raise ValueError(str(exc)) from None
ValueError: Gas estimation failed: 'The execution failed due to an exception.'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.
```

My `fund_with_link` function

```
def fund_with_link(contract_address,account=None,link_token=None,amount=100000000000000000): #0.1 Link
    account = account if account else get_account()
    link_token = link_token if link_token else get_contract("link_token")
    tx = link_token.transfer(contract_address, amount , {"from": account})
    tx.wait(1)
    print("Funded link to contract")
    return tx
```

**Comment by muhammadgaffar** [comment]
have you used proper `vrf coordinator`, `key has`, and `fee` correctly in your brownie config? https://docs.chain.link/docs/vrf-contracts/v1/

**Comment by cromewar** [comment]
Yes this problem is most likely related to a bad configuration on `brownie-config.yaml` regarding the link token fee.

**Comment by shashankvivek** [comment]
@cromewar @muhammadgaffar : I have double checked it. You can verify that as well in the provided githum link of mine

**Comment by muhammadgaffar** [comment]
I have checked your file. the problem lies on the contract. you have not specified the fee for RNG in your contract.

`constructor (
        address _priceFeed,
        address _vrfCordinator,
        address _link,
        uint256 _fee,
        bytes32 _keyHash) 
        public 
        VRFConsumerBase(_vrfCordinator,_link){
        usdEntryFee = 50 *(10**18);
        ethUsdPriceFeed =  AggregatorV3Interface(_priceFeed);
        lottery_state = LOTTERY_STATE.CLOSED;
        keyHash = _keyHash; 
    }
`

specify the fee `fee = _fee;` before keyhash. that fee is for random number generator gas fee.

**Comment by muhammadgaffar** [comment]
I have checked your file. the problem lies on the contract. you have not specified the fee for RNG in your contract.

```    
constructor (
        address _priceFeed,
        address _vrfCordinator,
        address _link,
        uint256 _fee,
        bytes32 _keyHash) 
        public 
        VRFConsumerBase(_vrfCordinator,_link){
        usdEntryFee = 50 *(10**18);
        ethUsdPriceFeed =  AggregatorV3Interface(_priceFeed);
        lottery_state = LOTTERY_STATE.CLOSED;
        fee = _fee;
        keyHash = _keyHash; 
    }
```

specify the fee `fee = _fee`; before keyhash. that fee is for random number generator gas fee.
