### ISSUE TITLE
Lesson 11, 11:24:00 create_metadata.py prints URL, but opens "The image "URL" cannot be displayed because it contains errors" 

### ISSUE THREAD

**Issue by snowieoxs** [smartcontractkit/full-blockchain-solidity-course-py#1411]
Lesson 11, 11:24:00 create_metadata.py prints URL, but opens "The image "URL" cannot be displayed because it contains errors" 

Been looking at this issue for a while now! when I open the URL I am greeted with the message "The image "URL" cannot be displayed because it contains errors" I do have IPFS daemon running, I have tried running all the scripts in different orders, I think the file path is right, I have made 3 different collectables... but it seems like there is a issue with IPFS taking any of this in, even though I have it running...
maybe I am supposed to have something in the config or .env for IPFS to take the images, but I'm not sure! think I saw a post about somebody manually uploading them, lol, said he uploaded them manually, but trying to figure out how to do it programmatically. here are some screen shots, and a copy paste of the create_metadata.py at the bottom. 

Thanks for reading!

![Screenshot from 2022-04-16 15-57-52](https://user-images.githubusercontent.com/98249510/163691182-7a38d8c5-e305-4c19-969c-023427b2e10c.png)

![Screenshot from 2022-04-16 15-38-11](https://user-images.githubusercontent.com/98249510/163690755-cbb3d60e-b870-4f0e-906e-7a3feaee1212.png)
![Screenshot from 2022-04-16 15-38-56](https://user-images.githubusercontent.com/98249510/163690758-59e46370-4a75-413d-a355-be0e295fbd68.png)

Copy paste of create_metadata.py

from brownie import AdvancedCollectible, network
from scripts.helpful_scripts import get_breed
from metadata.sample_metadata import metadata_template
from pathlib import Path
import requests
import json
import os

def main():
    advanced_collectible = AdvancedCollectible[-1]
    number_of_advanced_collectibles = advanced_collectible.tokenCounter()
    print(f"You have created {number_of_advanced_collectibles} collectibles!")
    for token_id in range(number_of_advanced_collectibles):
        breed = get_breed(advanced_collectible.tokenIdToBreed(token_id))
        metadata_file_name = (
            f"./metadata/{network.show_active()}/{token_id}-{breed}.json"
        )
        collectible_metadata = metadata_template
        if Path(metadata_file_name).exists():
            print(f"{metadata_file_name} already exists! Delete it to overwrite")
        else:
            print(f"Creating Metadata file: {metadata_file_name}")
            collectible_metadata["name"] = breed
            collectible_metadata["description"] = f"An adorable {breed} pup!"
            print(collectible_metadata)
            image_path = "./img/" + breed.lower().replace("_", "-") + ".png"
            image_uri = upload_to_ipfs(image_path)
            # collectible_metadata["image"] = image_uri

def upload_to_ipfs(filepath):
    print("function upload to ipfs is executed")
    with Path(filepath).open("rb") as fp:
        image_binary = fp.read()
        ipfs_url = "http://127.0.0.1:5001"
        endpoint = "/api/v0/add"
        response = requests.post(ipfs_url + endpoint, files={"file": image_binary})
        ipfs_hash = response.json()["Hash"]
        # "./img/PUG.png" -> "PUG.png"
        filename = filepath.split("/")[-1:][0]
        image_uri = f"https://ipfs.io/ipfs/{ipfs_hash}?filename={filename}"
        print("next line should be a link")
        print(image_uri)
        return image_uri
        # upload stuff...

**Comment by cromewar** [comment]
Hello @snowieoxs 
Well as you are trying to do this programatically remember that ipfs service requires a constant node running, so as you are connecting to localhost do you already have the ipds running on your machine?

**Comment by snowieoxs** [comment]
I did see that it is necessary to have the node node running, but assumed that it was as simple as running the daemon in a separate terminal in vs code, and turning it off after the tutorial would be sufficient for the lesson, been digging around in the ipfs documentation, learned a bit about ipfs... but still can't figure it out.

**Comment by snowieoxs** [comment]
oh my goodness, finally figured it out... I restarted the tutorial and noticed that the dogs images were actually showing up in vscode, where as mine were not, just blank... I manually moved the dog pics from my image folder to the image folder in the nft demo... and It worked... I had just typed in the file name before... thats why the doggies were not showing up, thank you, and closed

**Comment by cromewar** [comment]
I'm glad is solved now, this would have being really difficult to catch but you did it, Nice!
