### ISSUE TITLE
Lesson 11: ImportError: cannot import name 'LinkToken' from 'brownie'

### ISSUE THREAD

**Issue by RohanNero** [smartcontractkit/full-blockchain-solidity-course-py#1412]
When I try to run `brownie run scripts/advanced_collectible/deploy_and_create.py` in the terminal I get returned:

> ImportError: cannot import name 'LinkToken' from 'brownie'

I've uninstalled and reinstalled brownie, closed and reopened the terminal and vscode, and deleted my build folder and recompiled.
I've also copy and pasted directly over my code from Patrick's github nft-mix and the error still pops up. 

Any help would be greatly appreciated!

**Comment by cromewar** [comment]
Hello @RohanNero 
Do you have the link token mock on the test folder? 
you can get it from chainlink-mix.

**Comment by RohanNero** [comment]
Hello @cromewar, 
I just copied and pasted the files from inside the tests folder and the error is still popping up.

**Comment by ptn77** [comment]
@RohanNero Do you have the __init__.py file?

**Comment by RohanNero** [comment]
I had forgotten to copy over the Mock contracts into the test_contracts folder. _Sorry my brain is a little over-cooked._
