### ISSUE TITLE
Lesson 4: ModuleNotFoundError: No module named 'solcx' ( Still Error) 

### ISSUE THREAD

**Issue by Shasanka1** [smartcontractkit/full-blockchain-solidity-course-py#1473]
Hi,

I am currently working on Lesson 4 with installing and using solcx.

I have done the process of adding the code changes missed in the video, but I still managed to have issues with python not recognizing Solex. Here is my code. 

`from solcx import compile_standard, install_solc # <- import the install_solc method!
install_solc('0.6.0') # <- Add this line and run it at least once!

with open("SimpleStorage.sol", "r") as file:
    simple_storage_file = file.read()

compiled_sol = compile_standard(
    {
        "language": "solidity",
        "sources": {"simpleStorage.sol": {"content": simple_storage_file}},
        "settings": {
            "outputSelection": {
                "*": {"*": ["abi", "metadata", "evm.bytecode", "evm.sourceMap"]}
            }
        },
    },
    solc_version="0.6.0",
)

print("compiled_sol")`

Error 
`ModuleNotFoundError: No module named 'solcx'`

Thanks for readint his post. I hope anyone here can help.

**Comment by dibakarsutradhar** [comment]
Add `install_solc("0.6.0")` right before `compiled_sol = compile_standard(` line.

It would look something like this,
```
install_solc("0.6.0")
compliled_sol = compile_standard(
    {
        "language": "Solidity",
        "sources": {"SimpleStorage.sol": {"content": simple_storage_file}},
        "settings": {
            "outputSelection": {
                "*": {"*": ["abi", "metadata", "evm.bytecode", "evm.sourceMap"]}
            }
        },
    },
    solc_version="0.6.0",
)
```

Also, make sure that you have already installed `py-solc-x` using `pip3 install py-solc-x`

**Comment by Shasanka1** [comment]
Thanks for the reply @dibakarsutradhar. I also ran into another issue that has to deal with pip installation for python3+ libraries by using `--user` at the end of pip3 install.

The issue was posted in StackOverflow... 
[here](https://stackoverflow.com/questions/52949531/could-not-install-packages-due-to-an-environmenterror-errno-13)

Now, I am able to fully run the deploy.py. Thanks for helping.

**Comment by dibakarsutradhar** [comment]
@Shasanka1 glad I could help. If you don't have this issue anymore, I request you close this issue.

The later issue you mentioned looks like there's a solution provided in the StackOverFlow forum. If you are still having a problem with the pip installation `--user` command, try `pip3 install package_name --user` this method. Otherwise, I'd suggest you open a new issue.
