### ISSUE TITLE
Chapter 7: Lottery - Integration Test Error

### ISSUE THREAD

**Issue by damdafayton** [smartcontractkit/full-blockchain-solidity-course-py#1493]
I am having the same problem which was described here and wasn't able to be solved:
https://github.com/PatrickAlphaC/smartcontract-lottery/issues/68

[This is the error I get](https://drive.google.com/file/d/10mKo4QQaJlqDdubOwWgD0kEr8Ww3O6eJ/view)

Function I am calling
```
def test_can_pick_winner():
    if network.show_active() in LOCAL_BLOCKCHAIN_ENVIRONMENTS:
        pytest.skip
    lottery = deploy_lottery()
    lottery.startLottery(_from())
    lottery.enter(_from(lottery.getEntranceFee()))
    lottery.enter(_from(lottery.getEntranceFee()))
    fund_with_link(lottery)
    lottery.endLottery(_from())
    time.sleep(60)
    assert lottery.recentWinner() == get_account()
    assert lottery.balance() == 0
```

Result
```
Running on [rinkeby] network
Deployed Lottery!
Funded contract with LINK
tests/test_lottery_integration.py::test_can_pick_winner FAILED
```

**Comment by damdafayton** [comment]
I guess I solved it by the help of these posts:

https://ethereum.stackexchange.com/questions/114500/brownie-rinkeby-valueerror-gas-estimation-failed-you-must-set-the-gas-limit

https://stackoverflow.com/questions/71194882/execution-reverted-during-call-this-transaction-will-likely-revert-if-you-wish/71212745#71212745

Seems it was a VRFCoordinator version error. I have updated the contract address by VRF version 1 address and this error didn't occur again.

**Comment by achimstruve** [comment]
> I guess I solved it by the help of these posts:
> 
> https://ethereum.stackexchange.com/questions/114500/brownie-rinkeby-valueerror-gas-estimation-failed-you-must-set-the-gas-limit
> 
> https://stackoverflow.com/questions/71194882/execution-reverted-during-call-this-transaction-will-likely-revert-if-you-wish/71212745#71212745
> 
> Seems it was a VRFCoordinator version error. I have updated the contract address by VRF version 1 address and this error didn't occur again.

Yes, this helped me as well.
We have to use the v1 VRF Coordinator address and keyhash.
Both can be found here for Rinkeby:
https://docs.chain.link/docs/vrf-contracts/v1/

**Comment by PatrickAlphaC** [comment]
Thanks! Could you make a PR to the repo for the "chronological issues" section with the fix?

**Comment by achimstruve** [comment]
> Thanks! Could you make a PR to the repo for the "chronological issues" section with the fix?

The error occurs when people (like myself) try to get the VRF Coordinator address by themselves instead of just copying it from the repo. By getting the address on our own we can accidentally end up on the version 2 contract address page.
In other words, the repo should work just fine how it is. The repo is correct, because it has the v1 VRF Coordinator address in the brownie-config.yaml.

**Comment by achimstruve** [comment]
> Thanks! Could you make a PR to the repo for the "chronological issues" section with the fix?

I just made a PR to the repo for the "chronological issues" with a small note that should bring some more clarification for following people.

**Comment by PatrickAlphaC** [comment]
Thank you!
