### ISSUE TITLE
 python subprocess filenotfounderror: (winerror 2) the system cannot find the file specified

### ISSUE THREAD

**Issue by LouCse59** [smartcontractkit/full-blockchain-solidity-course-py#1509]
Fifth lesson from the course

My code is;
"def main():
print("Hello !")"

when I launch it with
"brownie run scripts/deploy.py"

I receive "FileNotFoundError: [WinError 2] File not found (...)"

Any help ?

Best

**Comment by allawitten** [comment]
You have to rewind the lesson a bit and install nodejs, yarn, ganache-cli which are required to run a script with Brownie. Once everything is installed it should work fine.
