### ISSUE TITLE
Cant Install Web3 with pip

### ISSUE THREAD

**Issue by RJNeel17** [smartcontractkit/full-blockchain-solidity-course-py#154]
Tried installing web3 as instructured but encountered the following issue:

$ python -m pip install web3
Requirement already satisfied: web3 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\web3-5.23.1-py3.10.egg (5.23.1)
Requirement already satisfied: aiohttp<4,>=3.7.4.post0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\aiohttp-3.7.4.post0-py3.10.egg (from web3) (3.7.4.post0)
Requirement already satisfied: eth-abi<3.0.0,>=2.0.0b6 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\eth_abi-2.1.1-py3.10.egg (from web3) (2.1.1)
Requirement already satisfied: eth-account<0.6.0,>=0.5.5 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\eth_account-0.5.5-py3.10.egg (from web3) (0.5.5)
Requirement already satisfied: eth-hash[pycryptodome]<1.0.0,>=0.2.0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\eth_hash-0.3.2-py3.10.egg (from web3) (0.3.2)
Requirement already satisfied: eth-typing<3.0.0,>=2.0.0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\eth_typing-2.2.2-py3.10.egg (from web3) (2.2.2)
Requirement already satisfied: eth-utils<2.0.0,>=1.9.5 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\eth_utils-1.10.0-py3.10.egg (from web3) (1.10.0)
Requirement already satisfied: hexbytes<1.0.0,>=0.1.0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\hexbytes-0.2.2-py3.10.egg (from web3) (0.2.2)
Requirement already satisfied: ipfshttpclient==0.8.0a2 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\ipfshttpclient-0.8.0a2-py3.10.egg (from web3) (0.8.0a2)
Requirement already satisfied: jsonschema<4.0.0,>=3.2.0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\jsonschema-3.2.0-py3.10.egg (from web3) (3.2.0)
Requirement already satisfied: lru-dict<2.0.0,>=1.1.6 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\lru_dict-1.1.7-py3.10-win-amd64.egg (from web3) (1.1.7)
Requirement already satisfied: protobuf<4,>=3.10.0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\protobuf-3.18.0-py3.10.egg (from web3) (3.18.0)
Collecting web3
  Using cached web3-5.24.0-py3-none-any.whl (487 kB)
  Using cached web3-5.23.0-py3-none-any.whl (485 kB)
  Using cached web3-5.22.0-py3-none-any.whl (484 kB)
  Using cached web3-5.21.0-py3-none-any.whl (482 kB)
  Using cached web3-5.20.1-py3-none-any.whl (479 kB)
  Using cached web3-5.20.0-py3-none-any.whl (480 kB)
  Using cached web3-5.19.0-py3-none-any.whl (470 kB)
Collecting ipfshttpclient==0.7.0a1
  Using cached ipfshttpclient-0.7.0a1-py3-none-any.whl (231 kB)
Collecting web3
  Using cached web3-5.18.0-py3-none-any.whl (469 kB)
  Using cached web3-5.17.0-py3-none-any.whl (469 kB)
Collecting pypiwin32>=223
  Using cached pypiwin32-223-py3-none-any.whl (1.7 kB)
Requirement already satisfied: requests<3.0.0,>=2.16.0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages (from web3) (2.26.0)
Collecting websockets<9.0.0,>=8.1.0
  Using cached websockets-8.1.tar.gz (58 kB)
Requirement already satisfied: multiaddr>=0.0.7 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\multiaddr-0.0.9-py3.10.egg (from ipfshttpclient==0.7.0a1->web3) (0.0.9)
Requirement already satisfied: parsimonious<0.9.0,>=0.8.0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\parsimonious-0.8.1-py3.10.egg (from eth-abi<3.0.0,>=2.0.0b6->web3) (0.8.1)
Requirement already satisfied: bitarray<1.3.0,>=1.2.1 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\bitarray-1.2.2-py3.10-win-amd64.egg (from eth-account<0.6.0,>=0.5.5->web3) (1.2.2)
Requirement already satisfied: eth-keyfile<0.6.0,>=0.5.0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\eth_keyfile-0.5.1-py3.10.egg (from eth-account<0.6.0,>=0.5.5->web3) (0.5.1)
Requirement already satisfied: eth-keys!=0.3.2,<0.4.0,>=0.2.1 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\eth_keys-0.3.3-py3.10.egg (from eth-account<0.6.0,>=0.5.5->web3) (0.3.3)
Requirement already satisfied: eth-rlp<2,>=0.1.2 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\eth_rlp-0.2.1-py3.10.egg (from eth-account<0.6.0,>=0.5.5->web3) (0.2.1)
Requirement already satisfied: rlp<3,>=1.0.0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\rlp-1.2.0-py3.10.egg (from eth-account<0.6.0,>=0.5.5->web3) (1.2.0)
Requirement already satisfied: pycryptodome<4,>=3.6.6 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\pycryptodome-3.10.1-py3.10-win-amd64.egg (from eth-hash[pycryptodome]<1.0.0,>=0.2.0->web3) (3.10.1)
Requirement already satisfied: cytoolz<1.0.0,>=0.9.0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\cytoolz-0.11.0-py3.10-win-amd64.egg (from eth-keyfile<0.6.0,>=0.5.0->eth-account<0.6.0,>=0.5.5->web3) (0.11.0)
Requirement already satisfied: toolz>=0.8.0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\toolz-0.11.1-py3.10.egg (from cytoolz<1.0.0,>=0.9.0->eth-keyfile<0.6.0,>=0.5.0->eth-account<0.6.0,>=0.5.5->web3) (0.11.1)
Requirement already satisfied: attrs>=17.4.0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\attrs-21.2.0-py3.10.egg (from jsonschema<4.0.0,>=3.2.0->web3) (21.2.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\pyrsistent-0.18.0-py3.10-win-amd64.egg (from jsonschema<4.0.0,>=3.2.0->web3) (0.18.0)
Requirement already satisfied: setuptools in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages (from jsonschema<4.0.0,>=3.2.0->web3) (57.4.0)
Requirement already satisfied: six>=1.11.0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\six-1.16.0-py3.10.egg (from jsonschema<4.0.0,>=3.2.0->web3) (1.16.0)
Requirement already satisfied: base58 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\base58-2.1.0-py3.10.egg (from multiaddr>=0.0.7->ipfshttpclient==0.7.0a1->web3) (2.1.0)
Requirement already satisfied: netaddr in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\netaddr-0.8.0-py3.10.egg (from multiaddr>=0.0.7->ipfshttpclient==0.7.0a1->web3) (0.8.0)
Requirement already satisfied: varint in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\varint-1.0.2-py3.10.egg (from multiaddr>=0.0.7->ipfshttpclient==0.7.0a1->web3) (1.0.2)
INFO: pip is looking at multiple versions of pycryptodome to determine which version is compatible with other requirements. This could take a while.
Collecting pycryptodome<4,>=3.6.6
  Using cached pycryptodome-3.10.4-cp35-abi3-win_amd64.whl (1.8 MB)
  Using cached pycryptodome-3.10.3-cp35-abi3-win_amd64.whl (1.8 MB)
  Using cached pycryptodome-3.10.1-cp35-abi3-win_amd64.whl (1.6 MB)
  Using cached pycryptodome-3.9.9.tar.gz (15.5 MB)
  Using cached pycryptodome-3.9.8.tar.gz (15.6 MB)
  Using cached pycryptodome-3.9.7.tar.gz (15.5 MB)
  Using cached pycryptodome-3.9.6.tar.gz (15.5 MB)
INFO: pip is looking at multiple versions of pycryptodome to determine which version is compatible with other requirements. This could take a while.
  Using cached pycryptodome-3.9.4.tar.gz (11.6 MB)
  Using cached pycryptodome-3.9.3.tar.gz (11.6 MB)
  Using cached pycryptodome-3.9.2.tar.gz (11.6 MB)
  Using cached pycryptodome-3.9.1.tar.gz (11.6 MB)
  Using cached pycryptodome-3.9.0.tar.gz (11.6 MB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Using cached pycryptodome-3.8.2.tar.gz (12.4 MB)

**Comment by pavelgor84** [comment]
After the Microsoft Build Tools were installed, I got the same long installation that ends up an error.

**Comment by RJNeel17** [comment]
UPDATE: Tried running again, just waited many hours. Received an error out as follows:

$ python -m pip install web3
Requirement already satisfied: web3 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\web3-5.23.1-py3.10.egg (5.23.1)
Requirement already satisfied: aiohttp<4,>=3.7.4.post0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\aiohttp-3.7.4.post0-py3.10.egg (from web3) (3.7.4.post0)
Requirement already satisfied: eth-abi<3.0.0,>=2.0.0b6 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\eth_abi-2.1.1-py3.10.egg (from web3) (2.1.1)
Requirement already satisfied: eth-account<0.6.0,>=0.5.5 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\eth_account-0.5.5-py3.10.egg (from web3) (0.5.5)
Requirement already satisfied: eth-hash[pycryptodome]<1.0.0,>=0.2.0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\eth_hash-0.3.2-py3.10.egg (from web3) (0.3.2)
Requirement already satisfied: eth-typing<3.0.0,>=2.0.0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\eth_typing-2.2.2-py3.10.egg (from web3) (2.2.2)
Requirement already satisfied: eth-utils<2.0.0,>=1.9.5 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\eth_utils-1.10.0-py3.10.egg (from web3) (1.10.0)
Requirement already satisfied: hexbytes<1.0.0,>=0.1.0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\hexbytes-0.2.2-py3.10.egg (from web3) (0.2.2)
Requirement already satisfied: ipfshttpclient==0.8.0a2 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\ipfshttpclient-0.8.0a2-py3.10.egg (from web3) (0.8.0a2)
Requirement already satisfied: jsonschema<4.0.0,>=3.2.0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\jsonschema-3.2.0-py3.10.egg (from web3) (3.2.0)
Requirement already satisfied: lru-dict<2.0.0,>=1.1.6 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\lru_dict-1.1.7-py3.10-win-amd64.egg (from web3) (1.1.7)
Requirement already satisfied: protobuf<4,>=3.10.0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\protobuf-3.18.0-py3.10.egg (from web3) (3.18.0)
Collecting web3
  Using cached web3-5.24.0-py3-none-any.whl (487 kB)
Requirement already satisfied: requests<3.0.0,>=2.16.0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages (from web3) (2.26.0)
Requirement already satisfied: websockets<10,>=9.1 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\websockets-9.1-py3.10-win-amd64.egg (from web3) (9.1)
Collecting eth-account<0.6.0,>=0.5.6
  Using cached eth_account-0.5.6-py3-none-any.whl (101 kB)
Collecting web3
  Using cached web3-5.23.0-py3-none-any.whl (485 kB)
  Using cached web3-5.22.0-py3-none-any.whl (484 kB)
  Using cached web3-5.21.0-py3-none-any.whl (482 kB)
Collecting ipfshttpclient==0.7.0
  Using cached ipfshttpclient-0.7.0-py3-none-any.whl (82 kB)
Collecting web3
  Using cached web3-5.20.1-py3-none-any.whl (479 kB)
  Using cached web3-5.20.0-py3-none-any.whl (480 kB)
Collecting websockets<9.0.0,>=8.1.0
  Using cached websockets-8.1.tar.gz (58 kB)
Collecting web3
  Using cached web3-5.19.0-py3-none-any.whl (470 kB)
Collecting ipfshttpclient==0.7.0a1
  Using cached ipfshttpclient-0.7.0a1-py3-none-any.whl (231 kB)
Collecting web3
  Using cached web3-5.18.0-py3-none-any.whl (469 kB)
  Using cached web3-5.17.0-py3-none-any.whl (469 kB)
Collecting pypiwin32>=223
  Using cached pypiwin32-223-py3-none-any.whl (1.7 kB)
Requirement already satisfied: multiaddr>=0.0.7 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\multiaddr-0.0.9-py3.10.egg (from ipfshttpclient==0.7.0a1->web3) (0.0.9)
Requirement already satisfied: parsimonious<0.9.0,>=0.8.0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\parsimonious-0.8.1-py3.10.egg (from eth-abi<3.0.0,>=2.0.0b6->web3) (0.8.1)
Requirement already satisfied: bitarray<1.3.0,>=1.2.1 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\bitarray-1.2.2-py3.10-win-amd64.egg (from eth-account<0.6.0,>=0.5.5->web3) (1.2.2)
Requirement already satisfied: eth-keyfile<0.6.0,>=0.5.0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\eth_keyfile-0.5.1-py3.10.egg (from eth-account<0.6.0,>=0.5.5->web3) (0.5.1)
Requirement already satisfied: eth-keys!=0.3.2,<0.4.0,>=0.2.1 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\eth_keys-0.3.3-py3.10.egg (from eth-account<0.6.0,>=0.5.5->web3) (0.3.3)
Requirement already satisfied: eth-rlp<2,>=0.1.2 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\eth_rlp-0.2.1-py3.10.egg (from eth-account<0.6.0,>=0.5.5->web3) (0.2.1)
Requirement already satisfied: rlp<3,>=1.0.0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\rlp-1.2.0-py3.10.egg (from eth-account<0.6.0,>=0.5.5->web3) (1.2.0)
Requirement already satisfied: pycryptodome<4,>=3.6.6 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\pycryptodome-3.10.1-py3.10-win-amd64.egg (from eth-hash[pycryptodome]<1.0.0,>=0.2.0->web3) (3.10.1)
Requirement already satisfied: cytoolz<1.0.0,>=0.9.0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\cytoolz-0.11.0-py3.10-win-amd64.egg (from eth-keyfile<0.6.0,>=0.5.0->eth-account<0.6.0,>=0.5.5->web3) (0.11.0)
Requirement already satisfied: toolz>=0.8.0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\toolz-0.11.1-py3.10.egg (from cytoolz<1.0.0,>=0.9.0->eth-keyfile<0.6.0,>=0.5.0->eth-account<0.6.0,>=0.5.5->web3) (0.11.1)
Requirement already satisfied: attrs>=17.4.0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\attrs-21.2.0-py3.10.egg (from jsonschema<4.0.0,>=3.2.0->web3) (21.2.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\pyrsistent-0.18.0-py3.10-win-amd64.egg (from jsonschema<4.0.0,>=3.2.0->web3) (0.18.0)
Requirement already satisfied: setuptools in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages (from jsonschema<4.0.0,>=3.2.0->web3) (58.2.0)
Requirement already satisfied: six>=1.11.0 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\six-1.16.0-py3.10.egg (from jsonschema<4.0.0,>=3.2.0->web3) (1.16.0)
Requirement already satisfied: base58 in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\base58-2.1.0-py3.10.egg (from multiaddr>=0.0.7->ipfshttpclient==0.7.0a1->web3) (2.1.0)
Requirement already satisfied: netaddr in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\netaddr-0.8.0-py3.10.egg (from multiaddr>=0.0.7->ipfshttpclient==0.7.0a1->web3) (0.8.0)
Requirement already satisfied: varint in c:\users\rjnee\appdata\local\programs\python\python310\lib\site-packages\varint-1.0.2-py3.10.egg (from multiaddr>=0.0.7->ipfshttpclient==0.7.0a1->web3) (1.0.2)
INFO: pip is looking at multiple versions of pycryptodome to determine which version is compatible with other requirements. This could take a while.
Collecting pycryptodome<4,>=3.6.6
  Downloading pycryptodome-3.11.0-cp35-abi3-win_amd64.whl (1.8 MB)
     |████████████████████████████████| 1.8 MB 2.2 MB/s
  Using cached pycryptodome-3.10.4-cp35-abi3-win_amd64.whl (1.8 MB)
  Using cached pycryptodome-3.10.3-cp35-abi3-win_amd64.whl (1.8 MB)
  Using cached pycryptodome-3.10.1-cp35-abi3-win_amd64.whl (1.6 MB)
  Using cached pycryptodome-3.9.9.tar.gz (15.5 MB)
  Using cached pycryptodome-3.9.8.tar.gz (15.6 MB)
  Using cached pycryptodome-3.9.7.tar.gz (15.5 MB)
INFO: pip is looking at multiple versions of pycryptodome to determine which version is compatible with other requirements. This could take a while.
  Using cached pycryptodome-3.9.6.tar.gz (15.5 MB)
  Using cached pycryptodome-3.9.4.tar.gz (11.6 MB)
  Using cached pycryptodome-3.9.3.tar.gz (11.6 MB)
  Using cached pycryptodome-3.9.2.tar.gz (11.6 MB)
  Using cached pycryptodome-3.9.1.tar.gz (11.6 MB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Using cached pycryptodome-3.9.0.tar.gz (11.6 MB)
  Using cached pycryptodome-3.8.2.tar.gz (12.4 MB)
  Using cached pycryptodome-3.8.1.tar.gz (11.5 MB)
  Using cached pycryptodome-3.8.0.tar.gz (11.5 MB)
  Using cached pycryptodome-3.7.3.tar.gz (9.3 MB)
  Using cached pycryptodome-3.7.2.tar.gz (7.2 MB)
  Using cached pycryptodome-3.7.1.tar.gz (7.2 MB)
  Using cached pycryptodome-3.7.0.tar.gz (7.2 MB)
  Using cached pycryptodome-3.6.6.tar.gz (7.1 MB)
INFO: pip is looking at multiple versions of protobuf to determine which version is compatible with other requirements. This could take 
a while.
Collecting protobuf<4,>=3.10.0
  Using cached protobuf-3.18.1-py2.py3-none-any.whl (174 kB)
  Using cached protobuf-3.18.0-py2.py3-none-any.whl (174 kB)
  Using cached protobuf-3.17.3-py2.py3-none-any.whl (173 kB)
  Using cached protobuf-3.17.2-py2.py3-none-any.whl (173 kB)
  Using cached protobuf-3.17.1-py2.py3-none-any.whl (173 kB)
  Using cached protobuf-3.17.0-py2.py3-none-any.whl (173 kB)
  Using cached protobuf-3.16.0-py2.py3-none-any.whl (173 kB)
INFO: pip is looking at multiple versions of protobuf to determine which version is compatible with other requirements. This could take 
a while.
  Using cached protobuf-3.15.8-py2.py3-none-any.whl (173 kB)
  Using cached protobuf-3.15.7-py2.py3-none-any.whl (173 kB)
  Using cached protobuf-3.15.6-py2.py3-none-any.whl (173 kB)
  Using cached protobuf-3.15.5-py2.py3-none-any.whl (173 kB)
  Using cached protobuf-3.15.4-py2.py3-none-any.whl (173 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Using cached protobuf-3.15.3-py2.py3-none-any.whl (173 kB)
  Using cached protobuf-3.15.2-py2.py3-none-any.whl (173 kB)
  Using cached protobuf-3.15.1-py2.py3-none-any.whl (173 kB)
  Using cached protobuf-3.15.0-py2.py3-none-any.whl (173 kB)
  Using cached protobuf-3.14.0-py2.py3-none-any.whl (173 kB)
  Using cached protobuf-3.13.0-py2.py3-none-any.whl (438 kB)
  Using cached protobuf-3.12.4-py2.py3-none-any.whl (443 kB)
  Using cached protobuf-3.12.2-py2.py3-none-any.whl (443 kB)
  Using cached protobuf-3.11.3-py2.py3-none-any.whl (434 kB)
  Using cached protobuf-3.11.2-py2.py3-none-any.whl (434 kB)
  Using cached protobuf-3.11.1-py2.py3-none-any.whl (434 kB)
  Using cached protobuf-3.11.0-py2.py3-none-any.whl (434 kB)
  Using cached protobuf-3.10.0-py2.py3-none-any.whl (434 kB)
INFO: pip is looking at multiple versions of parsimonious to determine which version is compatible with other requirements. This could take a while.
Collecting parsimonious<0.9.0,>=0.8.0
  Using cached parsimonious-0.8.1.tar.gz (45 kB)
  Using cached parsimonious-0.8.0.tar.gz (38 kB)
INFO: pip is looking at multiple versions of multiaddr to determine which version is compatible with other requirements. This could take a while.
Collecting multiaddr>=0.0.7
  Using cached multiaddr-0.0.9-py2.py3-none-any.whl (16 kB)
  Using cached multiaddr-0.0.8-py2.py3-none-any.whl (15 kB)
INFO: pip is looking at multiple versions of parsimonious to determine which version is compatible with other requirements. This could take a while.
  Using cached multiaddr-0.0.7-py2.py3-none-any.whl (15 kB)
INFO: pip is looking at multiple versions of lru-dict to determine which version is compatible with other requirements. This could take 
a while.
Collecting lru-dict<2.0.0,>=1.1.6
  Using cached lru-dict-1.1.7.tar.gz (10 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: pip is looking at multiple versions of multiaddr to determine which version is compatible with other requirements. This could take a while.
  Using cached lru-dict-1.1.6.tar.gz (9.4 kB)
INFO: pip is looking at multiple versions of attrs to determine which version is compatible with other requirements. This could take a while.
Collecting attrs>=17.4.0
  Using cached attrs-21.2.0-py2.py3-none-any.whl (53 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Using cached attrs-20.3.0-py2.py3-none-any.whl (49 kB)
INFO: pip is looking at multiple versions of lru-dict to determine which version is compatible with other requirements. This could take 
a while.
  Using cached attrs-20.2.0-py2.py3-none-any.whl (48 kB)
  Using cached attrs-20.1.0-py2.py3-none-any.whl (49 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Using cached attrs-19.3.0-py2.py3-none-any.whl (39 kB)
  Using cached attrs-19.2.0-py2.py3-none-any.whl (40 kB)
  Using cached attrs-19.1.0-py2.py3-none-any.whl (35 kB)
INFO: pip is looking at multiple versions of attrs to determine which version is compatible with other requirements. This could take a while.
  Using cached attrs-18.2.0-py2.py3-none-any.whl (34 kB)
  Using cached attrs-18.1.0-py2.py3-none-any.whl (28 kB)
  Using cached attrs-17.4.0-py2.py3-none-any.whl (31 kB)
INFO: pip is looking at multiple versions of jsonschema to determine which version is compatible with other requirements. This could take a while.
Collecting jsonschema<4.0.0,>=3.2.0
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: pip is looking at multiple versions of hexbytes to determine which version is compatible with other requirements. This could take 
a while.
Collecting hexbytes<1.0.0,>=0.1.0
  Using cached hexbytes-0.2.2-py3-none-any.whl (6.1 kB)
  Using cached hexbytes-0.2.1-py3-none-any.whl (6.0 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Rjnee\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\cli\base_command.py", line 173, in _main 
    status = self.run(options, args)
  File "C:\Users\Rjnee\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\cli\req_command.py", line 203, in wrapper    return func(self, options, args)
  File "C:\Users\Rjnee\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\commands\install.py", line 315, in run   
    requirement_set = resolver.resolve(
  File "C:\Users\Rjnee\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 
94, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\Rjnee\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\Rjnee\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 383, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000
