### ISSUE TITLE
.env trouble

### ISSUE THREAD

**Issue by PratyushNag** [smartcontractkit/full-blockchain-solidity-course-py#1554]
### Discussed in https://github.com/smartcontractkit/full-blockchain-solidity-course-py/discussions/1397

<div type='discussions-op-text'>

<sup>Originally posted by **Reus1196** April 12, 2022</sup>
![image](https://user-images.githubusercontent.com/98214304/163018342-c7d588ce-0d55-4f6c-b546-2cedf37cba55.png)
I was working OK with my .env and then it just started showing errors that I cannot solve. Any help?</div>

**Comment by cromewar** [comment]
Could you try removing the keyword export? and see if that helps.

**Comment by cromewar** [comment]
Hum something may be messing up with your vscode, may bien an extension or a configuration... could you share your setting.json @PratyushNag ?

**Comment by PratyushNag** [comment]
![image](https://user-images.githubusercontent.com/83463746/175262402-21d54a1c-a4bd-49e2-a4f8-4c6a4c71a0d0.png)

**Comment by PratyushNag** [comment]
I finally got it to work, turns out this errors happens if the brownie-config file is not saved, if you make changes to the .env file make sure you save the .env file as well as the config file. Even if you haven't changed anything in the config file, saving it again solves this error for me. Hope this helps others struggling with the same error

**Comment by dankorea** [comment]
> Hum something may be messing up with your vscode, may bien an extension or a configuration... could you share your setting.json @PratyushNag ?

Oh...this problem kept messing me for 2 days until i rename the .env to x.env then changed it back to .env, when i saved all red lines disappeared.  done! so amazing....!
