### ISSUE TITLE
LESSON 7: IMPORT ERROR

### ISSUE THREAD

**Issue by AlrohfAZ** [smartcontractkit/full-blockchain-solidity-course-py#1630]
Ran the code and this is the error I keep getting;
ImportError while importing test module 'C:\Users\Morounfola\AppData\Local\Programs\Python\Python38\SmartContract-lottery\tests\test_Lottery.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests\test_Lottery.py:3: in <module>
    from brownie import Lottery, accounts, config, network
E   ImportError: cannot import name 'Lottery' from 'brownie' (C:\Users\Morounfola\AppData\Local\Programs\Python\Python38\lib\site-packages\brownie\__init__.py)
=================================================== short test summary info ===================================================
FAILED tests/test_Lottery.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
====================================================== 1 error in 1.49s =======================================================
The code is below.
`#0.0317789204065159
#310000000000000000
from brownie import Lottery, accounts, config, network
from web3 import Web3

def test_get_entrance_fee():
    account = accounts[0]
    lottery = lottery.deploy(
        config["networks"][network.showactive()]["eth_usd_price_feed"],
        {"from": account},
    )
    assert lottery.getEntranceFee() > Web3.toWei(0.028, "ether")
    assert lottery.getEntranceFee() < Web3.toWei(0.038, "ether")`

**Comment by AfolabiOlaoluwa** [comment]
You may want to look at how you named your file name. Example of why you get error is the in the name `test_Lottery.py`. That's a capital letter L standing in the way and violated naming conventions in Python. 

Also look at what you are importing if it's the right file.

**Comment by AlrohfAZ** [comment]
That actually was part of the issue, already resolved it though thank you.
