### ISSUE TITLE
rinkeby

### ISSUE THREAD

**Issue by paul-frdev** [smartcontractkit/full-blockchain-solidity-course-py#1643]
I'm unable to fund my MM account via the Rinkeby Faucet.

An "insufficient funds for gas * price + value" error persists.

Please send some test eth to the test account on the Rinkeby Test Net: 0x573dBc2b32993fe46020C9A8293ad29eF36FFa5a

**Comment by MuhammadAwais0** [comment]
you can try to use some other faucet to fund your rinkeby account, alchemy has their own faucet too, try to use that by creating acc there and then funding your wallet.
