### ISSUE TITLE
Lesson Lesson 6: Brownie Fund Me ValueError(f"Dotenv specified in config but not found at path: {env_path}")

### ISSUE THREAD

**Issue by ellyblueeyes** [smartcontractkit/full-blockchain-solidity-course-py#1674]
Hello there, I am trying to run this contract but I get this error 

(base) elly@elly-Lenovo-G50-80:~/demos/web3_py_simple_storage/brownie_fund_me$ brownie run scripts/deploy.py
Brownie v1.19.1 - Python development framework for Ethereum

  File "brownie/_cli/__main__.py", line 64, in main
    importlib.import_module(f"brownie._cli.{cmd}").main()
  File "brownie/_cli/run.py", line 42, in main
    active_project.load_config()
  File "brownie/project/main.py", line 474, in load_config
    _load_project_config(self._path)
  File "brownie/_config.py", line 199, in _load_project_config
    raise ValueError(f"Dotenv specified in config but not found at path: {env_path}")
ValueError: Dotenv specified in config but not found at path: /home/elly/demos/web3_py_simple_storage/brownie_fund_me/.env

Below I added all the files: 

1. FundMe.sol

// SPDX-License-Identifier: MIT

pragma solidity ^0.6.6;

import "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol";
import "@chainlink/contracts/src/v0.6/vendor/SafeMathChainlink.sol";

contract FundMe {
    using SafeMathChainlink for uint256;

    mapping(address => uint256) public addressToAmountFunded;
    address[] public funders;
    address public owner;
    AggregatorV3Interface public priceFeed;

    // if you're following along with the freecodecamp video
    // Please see https://github.com/PatrickAlphaC/fund_me
    // to get the starting solidity contract code, it'll be slightly different than this!
    constructor() public {
        owner = msg.sender;
    }

    function fund() public payable {
        uint256 minimumUSD = 50 * 10**18;
        require(
            getConversionRate(msg.value) >= minimumUSD,
            "You need to spend more ETH!"
        );
        addressToAmountFunded[msg.sender] += msg.value;
        funders.push(msg.sender);
    }

    function getVersion() public view returns (uint256) {
        AggregatorV3Interface priceFeed = AggregatorV3Interface(
            0xbb18dd19aeda4a56a474a5e795e826de
        );
        return priceFeed.version();
    }

    function getPrice() public view returns (uint256) {
        AggregatorV3Interface priceFeed = AggregatorV3Interface(
            0xbb18dd19aeda4a56a474a5e795e826de
        );
        (, int256 answer, , , ) = priceFeed.latestRoundData();
        return uint256(answer * 10000000000);
    }

    // 1000000000
    function getConversionRate(uint256 ethAmount)
        public
        view
        returns (uint256)
    {
        uint256 ethPrice = getPrice();
        uint256 ethAmountInUsd = (ethPrice * ethAmount) / 1000000000000000000;
        return ethAmountInUsd;
    }

    function getEntranceFee() public view returns (uint256) {
        // minimumUSD
        uint256 minimumUSD = 50 * 10**18;
        uint256 price = getPrice();
        uint256 precision = 1 * 10**18;
        // return (minimumUSD * precision) / price;
        // We fixed a rounding error found in the video by adding one!
        return ((minimumUSD * precision) / price) + 1;
    }

    modifier onlyOwner() {
        require(msg.sender == owner);
        _;
    }

    function withdraw() public payable onlyOwner {
        msg.sender.transfer(address(this).balance);

        for (
            uint256 funderIndex = 0;
            funderIndex < funders.length;
            funderIndex++
        ) {
            address funder = funders[funderIndex];
            addressToAmountFunded[funder] = 0;
        }
        funders = new address[](0);
    }
}

2. Brownie-config.yaml
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.2.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1' 
dotenv:  .env
wallets:
  from_key: ${PRIVATE_KEY}       
3. Deploy.py
from brownie import FundMe
from scripts.helpful_scripts import get_account

def deploy_fund_me():
    account=get_account()
    fund_me=FundMe.deploy({"from": account})
    print(f"Contract deployed to {fund_me.address}")

def main():
    deploy_fund_me()   

require('dotenv').config({path:__dirname+'/./../../.env'})    

4. Helpful_scripts.py
from brownie import network, config, accounts

def get_account():
    if network.show_active()=="development":
        return accounts[0]
    else:
        return accounts.add(config["wallets"]["from_key"])

**Comment by AlrohfAZ** [comment]
Try checking if the .env file is in the brownie_fund_me folder and not in one of its subfolders.

**Comment by AlrohfAZ** [comment]
Can you format the codes so they can appear better, I think it's because you stored them under remappings, should be something like this;
``` 
dependencies:
smartcontractkit/chainlink-brownie-contracts@0.2.1
compiler:
solc:
remappings:
    '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1'
dotenv: .env
wallets:
from_key: ${PRIVATE_KEY}
``````
If it's not that, you can also check if the .env file is in the brownie fund me folder and not one of its subfolders.

**Comment by ellyblueeyes** [comment]
It was a space in front of the . when I created the env file.
Thanks!
