### ISSUE TITLE
Lesson 5: Brownie Simple Storage -> Brownie compile Error.

### ISSUE THREAD

**Issue by begin2ee** [smartcontractkit/full-blockchain-solidity-course-py#1708]
when i input "brownie compile" at the terminal, it says like that.

Brownie v1.19.1 - Python development framework for Ethereum
Project has been compiled. Build artifacts saved at C:\Users\USER\OneDrive\바탕 화면\demos\brownie_simple_storage\build\contracts 

But there is nothing at all. How can i solve this problem?
Help me please...
--------------------------------------------------------------------------------------------------------
[Error Message]
<img width="715" alt="image" src="https://user-images.githubusercontent.com/108245208/191018385-dc13284d-7646-494b-8806-241a8ef0d674.png">
[There is no any .json File]
![image](https://user-images.githubusercontent.com/108245208/191018764-7c16e99f-caee-4513-9777-fbe5b2fac37d.png)

**Comment by cromewar** [comment]
The problem is you have the contract inside contract folder which  is inside of build, you should move the contract to contracts folder outside build folder.
