### ISSUE TITLE
Multipling an 18 decimal number 2 times in a row

### ISSUE THREAD

**Issue by DieKant** [smartcontractkit/full-blockchain-solidity-course-py#189]
Title, in the Lottery.sol contract at https://github.com/PatrickAlphaC/smartcontract-lottery/blob/main/contracts/Lottery.sol we get to a point ( line 35 ) where usdEntryFee is assigned as a 18 decimal number and then we multiply that variable again in by 10^18 ( line 55 ), I don't understand why it gets multiplied again when it's already a 18 decimal number, can someone explain me?

**Comment by cwazuidema** [comment]
I got stuck here as well, until I saw:

_Remember that Solidity does not work with float numbers._

Now I understand how getEntranceFee() works, thanks @vsevdrob!
