### ISSUE TITLE
Lesson 6 (Brownie FundMe) - Having trouble interacting with deployed FundMe contract

### ISSUE THREAD

**Issue by noisetheory** [smartcontractkit/full-blockchain-solidity-course-py#190]
Hi Everyone.

I am having trouble interacting with the deployed "FundMe" contract in Lesson 5, via fund_and_withdraw.py. The specific time in the video is 5:44:38

The problem occurs at line "fund_me.getEntranceFee()" - i even tried other functions such as "getVersion()" but no luck.

The contracts appear to deploy successfully and the transactions for contract creation are viewable in my ganache UI.

Any ideas?

The output from terminal is below:

PS C:\Users\XXXXX\Downloads\brownie_fund_me> brownie run .\scripts\deploy.py --network ganache-local
```
INFO: Could not find files for the given pattern(s).
Brownie v1.16.4 - Python development framework for Ethereum

BrownieFundMeProject is the active project.
Running 'scripts\deploy.py::main'...
The active network is ganache-local
Deploying Mocks...
Transaction sent: 0xfeda920b7936699419d47e25fb22b5bbe160603e8424fee4b86fc9fbe7c5eb52
  Gas price: 20.0 gwei   Gas limit: 473790   Nonce: 0
  MockV3Aggregator.constructor confirmed   Block: 1   Gas used: 430719 (90.91%)
  MockV3Aggregator deployed at: 0x4Ee6FA77002090365f8750BB70ba713229cC0921

Mocks Deployed!
Transaction sent: 0xf07a5a5ece530f98f3c48807aac9cee196fcae6a67e9a69265704e2616874301
  Gas price: 20.0 gwei   Gas limit: 424509   Nonce: 1
  FundMe.constructor confirmed   Block: 2   Gas used: 385918 (90.91%)
  FundMe deployed at: 0x28E997DF1Fee9C0145975DCA4ACe227FcA976dE6

Contract Deployed to 0x28E997DF1Fee9C0145975DCA4ACe227FcA976dE6
```

PS C:\Users\XXXXX\Downloads\brownie_fund_me> brownie run .\scripts\fund_and_withdraw.py --network ganache-local
```
INFO: Could not find files for the given pattern(s).
Brownie v1.16.4 - Python development framework for Ethereum

BrownieFundMeProject is the active project.

Running 'scripts\fund_and_withdraw.py::main'...
  File "C:\Python310\lib\site-packages\eth_brownie-1.16.4-py3.10.egg\brownie\_cli\run.py", line 49, in main
    return_value, frame = run(
  File "C:\Python310\lib\site-packages\eth_brownie-1.16.4-py3.10.egg\brownie\project\scripts.py", line 103, in run
    return_value = f_locals[method_name](*args, **kwargs)
  File ".\scripts\fund_and_withdraw.py", line 13, in main
    fund()
  File ".\scripts\fund_and_withdraw.py", line 8, in fund
    entrance_fee = fund_me.getVersion()
  File "C:\Python310\lib\site-packages\eth_brownie-1.16.4-py3.10.egg\brownie\network\multicall.py", line 115, in _proxy_call
    result = ContractCall.__call__(*args, **kwargs)  # type: ignore
  File "C:\Python310\lib\site-packages\eth_brownie-1.16.4-py3.10.egg\brownie\network\contract.py", line 1729, in __call__
    return self.call(*args, block_identifier=block_identifier)
  File "C:\Python310\lib\site-packages\eth_brownie-1.16.4-py3.10.egg\brownie\network\contract.py", line 1533, in call
    raise VirtualMachineError(e) from None
VirtualMachineError: revert
```

Thanks for any assistance!

**Comment by DaveWKrupa** [comment]
I also ran into this problem even though my FunMe.deploy was passing in the value from a variable. But in my case the problem was that I had deployed a MockV3Aggregator, then I closed Ganache. When I reopened Ganache it no longer had the MockV3Aggregator contract, but Brownie was still referencing the contract I made previously. Thus using  an address that no longer existed.

Need to clean out the 1337 folder in VS Code when reopening ganache.

**Comment by Seek4samurai** [comment]
Just remember whenever you try to redeploy the contract at the first place. Remove 1337 folder and also removing it's entry in map.json in build/deployments/map.json or even better remove the whole build folder and then try redeploying it over again, with `brownie run scripts/deploy.py --network ganache-local` once done this means your contract has been deployed over your ganache-local blockchain and after this you can run `brownie run scripts/fund_and_withdraw.py --network ganache-local` over your ganache-local blockchain.

**Comment by tibasoliver** [comment]
I had the same problem, however in my code there was harcoded rinkeby contract . I removed from functions e everything went well. Try do the same if you find something similar in FundMe.sol.

**Comment by Cassain2019** [comment]
Dear Everyone !
I am also facing the same issue, and tried a lot to find the solution but no success yet.


Running 'scripts\fund_and_withdraw.py::main'...
  File "C:\Users\Kashif\AppData\Roaming\Python\Python310\site-packages\brownie\_cli\run.py", line 49, in main
    return_value, frame = run(
  File "C:\Users\Kashif\AppData\Roaming\Python\Python310\site-packages\brownie\project\scripts.py", line 103, in run
    return_value = f_locals[method_name](*args, **kwargs)
  File ".\scripts\fund_and_withdraw.py", line 22, in main
    fund()
  File ".\scripts\fund_and_withdraw.py", line 8, in fund
    entrance_fee = fund_me.getEntranceFee()
  File "C:\Users\Kashif\AppData\Roaming\Python\Python310\site-packages\brownie\network\multicall.py", line 115, in _proxy_call   
    result = ContractCall.__call__(*args, **kwargs)  # type: ignore
  File "C:\Users\Kashif\AppData\Roaming\Python\Python310\site-packages\brownie\network\contract.py", line 1729, in __call__      
    return self.call(*args, block_identifier=block_identifier)
  File "C:\Users\Kashif\AppData\Roaming\Python\Python310\site-packages\brownie\network\contract.py", line 1533, in call
    raise VirtualMachineError(e) from None
VirtualMachineError: revert

**Comment by casafurix** [comment]
> To fix this issue, do the following:
> 
> 1. Go to your `deploy.py` file and check the `price_feed_address` variable. Probably you forgot to use it here:
> 
> ```
> fund_me = FundMe.deploy(
>         "0x9326BFA02ADD2366b30bacB125260Af641031331",
>         {"from": account},
>         publish_source=config["networks"][network.show_active()].get("verify"),
>     )
> ```
> 
> 2. Replace the first parameter on the deploy function with the `price_feed_address` variable.
> 
> That's it. Hope I could help you.

dude, you're freaking amazinggg!! thanks a lottttt

**Comment by dinpran** [comment]
i still am not able to solve this error can anyone fix this i use price_feed_address only

**Comment by dinpran** [comment]
> I also ran into this problem even though my FunMe.deploy was passing in the value from a variable. But in my case the problem was that I had deployed a MockV3Aggregator, then I closed Ganache. When I reopened Ganache it no longer had the MockV3Aggregator contract, but Brownie was still referencing the contract I made previously. Thus using an address that no longer existed.
> 
> Need to clean out the 1337 folder in VS Code when reopening ganache.

can you please tell me how to solve this problem i also closed ganache

**Comment by tubarao312** [comment]
> Dear Everyone ! I am also facing the same issue, and tried a lot to find the solution but no success yet.
> 
> Running 'scripts\fund_and_withdraw.py::main'... File "C:\Users\Kashif\AppData\Roaming\Python\Python310\site-packages\brownie_cli\run.py", line 49, in main return_value, frame = run( File "C:\Users\Kashif\AppData\Roaming\Python\Python310\site-packages\brownie\project\scripts.py", line 103, in run return_value = f_locals[method_name](*args, **kwargs) File ".\scripts\fund_and_withdraw.py", line 22, in main fund() File ".\scripts\fund_and_withdraw.py", line 8, in fund entrance_fee = fund_me.getEntranceFee() File "C:\Users\Kashif\AppData\Roaming\Python\Python310\site-packages\brownie\network\multicall.py", line 115, in _proxy_call result = ContractCall.**call**(*args, **kwargs) # type: ignore File "C:\Users\Kashif\AppData\Roaming\Python\Python310\site-packages\brownie\network\contract.py", line 1729, in **call** return self.call(*args, block_identifier=block_identifier) File "C:\Users\Kashif\AppData\Roaming\Python\Python310\site-packages\brownie\network\contract.py", line 1533, in call raise VirtualMachineError(e) from None VirtualMachineError: revert

Hey, how did you end up fixing this issue? Thanks!

**Comment by prongs394** [comment]
> > Dear Everyone ! I am also facing the same issue, and tried a lot to find the solution but no success yet.
> > Running 'scripts\fund_and_withdraw.py::main'... File "C:\Users\Kashif\AppData\Roaming\Python\Python310\site-packages\brownie_cli\run.py", line 49, in main return_value, frame = run( File "C:\Users\Kashif\AppData\Roaming\Python\Python310\site-packages\brownie\project\scripts.py", line 103, in run return_value = f_locals[method_name](*args, **kwargs) File ".\scripts\fund_and_withdraw.py", line 22, in main fund() File ".\scripts\fund_and_withdraw.py", line 8, in fund entrance_fee = fund_me.getEntranceFee() File "C:\Users\Kashif\AppData\Roaming\Python\Python310\site-packages\brownie\network\multicall.py", line 115, in _proxy_call result = ContractCall.**call**(*args, **kwargs) # type: ignore File "C:\Users\Kashif\AppData\Roaming\Python\Python310\site-packages\brownie\network\contract.py", line 1729, in **call** return self.call(*args, block_identifier=block_identifier) File "C:\Users\Kashif\AppData\Roaming\Python\Python310\site-packages\brownie\network\contract.py", line 1533, in call raise VirtualMachineError(e) from None VirtualMachineError: revert
> 
> Hey, how did you end up fixing this issue? Thanks!

hi. i have this problem as well.
i can deploy the contract but when i call the getEntranceFee function i get the same "VirtualMachineError: revert" error as above.
when deploying the contract i am using the price_feed_address.
