### ISSUE TITLE
Lesson 6 : Brownie verify

### ISSUE THREAD

**Issue by DS-Coding0** [smartcontractkit/full-blockchain-solidity-course-py#1902]
If i want to verify the contract trough Etherscan API i get this Error:

  File "C:\Program, line line, in in
    return_value, frame = run(
  File "C:\Program, line line, in in
    return_value = f_locals[method_name](*args, **kwargs)
  File ".\scripts\deploy.py", line 11, in main
    deploy_fund_me()
  File ".\scripts\deploy.py", line 6, in deploy_fund_me
    fund_me = FundMe.deploy({"from": account}, publish_source=True)
  File "C:\Program, line line, in in
    return tx["from"].deploy(
  File "C:\Program, line line, in in
    contract.publish_source(deployed_contract, silent=silent)
  File "C:\Program, line line, in in
    data = response.json()
  File "C:\Program, line line, in in
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
JSONDecodeError: Expecting value: line 3 column 1 (char 4)
    
    

Transaction is sent and FundMe is successful deployed.

But after that i get this error.

Etherscan API is set correct.

**Comment by Ngawang-Gurung** [comment]
Use command:
```
brownie networks modify sepolia explorer=https://api-sepolia.etherscan.io/api
```

Previously it was explorer=https://api-sepolia.etherscan.io/

References:
https://ethereum.stackexchange.com/questions/152644/verification-of-contract-using-brownie
