### ISSUE TITLE
Stuck at start of lesson 9

### ISSUE THREAD

**Issue by DieKant** [smartcontractkit/full-blockchain-solidity-course-py#204]
I'm trying to compile the OurToken contract and it gives me this error but I don't understand why since the version of the compiler I set in vs code is 0.8.0+commit.c7dfd78e

The OurToken contract is a perfect copy of the one in the tutorial
![image](https://user-images.githubusercontent.com/61691496/137531768-b3e5ea1b-9931-4c5a-bfde-4e4f655ef583.png)

**Comment by DoctorNasa** [comment]
You will re-check the smart-contract file version which one inherits, For essay, you will make file contract as FLATTENER File
and deploy on https://remix.ethereum.org/.
