### ISSUE TITLE
"Import solcx could not be resolved"

### ISSUE THREAD

**Issue by yellowcheese773** [smartcontractkit/full-blockchain-solidity-course-py#21]
I have a very annoying problem. I can't import from solcx although I have installed it, when I do `pip3 list` it even shows solc and solcx as packages in the list. 
<img width="830" alt="Bildschirmfoto 2021-09-15 um 11 37 37" src="https://user-images.githubusercontent.com/80122924/133410551-068211e5-65b1-4bf5-acc0-32576a5e9f70.png">

I have installed Python correctly. When I type `python3 --version` it shows `Python 3.9.7` 

I have installed pip correctly. When I type `pip --version` it shows `pip 18.1 from /Library/Python/2.7/site-packages/pip (python 2.7)`

I have also installed pip3. When I type `pip3 --version` it shows `pip 21.2.4 from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip (python 3.9)`

I have installed py-solc-x. When I install it, it shows that:

<img width="815" alt="Bildschirmfoto 2021-09-15 um 11 44 40" src="https://user-images.githubusercontent.com/80122924/133410907-0337ddd3-8c70-41c8-a597-356aa7521cf7.png">

Despite all that, it don't want to import it. 

<img width="1156" alt="Bildschirmfoto 2021-09-15 um 11 42 00" src="https://user-images.githubusercontent.com/80122924/133410441-21bb4237-3367-42ec-b919-5c5c0470aa69.png">

I try since 2 days to solve this problem. I did almost everything. I am new to Python and the Chainlink Developer was right, installing these things is the hardest. 
I would be really thankful if somebody could help me out.

**Comment by moonwake769** [comment]
I prefer to use Python [virtual environment](https://docs.python.org/3/library/venv.html) while installing `pip` packages for different projects. You can also try this method:
Run this commands in the folder where the scripts are saved:
```
python3 -m venv venv
source venv/bin/activate
pip3 install py-solc-x
```

**Comment by yellowcheese773** [comment]
> I prefer to use Python [virtual environment](https://docs.python.org/3/library/venv.html) while installing `pip` packages for different projects. You can also try this method:
> Run this commands in the folder where the scripts are saved:
> 
> ```
> python3 -m venv venv
> source venv/bin/activate
> pip3 install py-solc-x
> ```

OMG, THANK YOU VERY MUCH, it fuc*ing worked.

1 small question: So I created this new virtual environment, when I want for example install eth-brownie does this also goes to the new environment? 
So do I need to do:
```
python3 -m venv venv 
source venv/bin/activate
pip3 install eth-brownie
```
Or can I just do `pip3 install etc-brownie`?

**Comment by PatrickAlphaC** [comment]
Please install browine with `pipx` instead of `pip`.

```
python3 -m pip install --user pipx
python3 -m pipx ensurepath
# close the terminal with the trash can
pipx install eth-brownie
```

**Comment by PatrickAlphaC** [comment]
And just remember, you'll have to activate the virtual environment everytime you work with your project!

**Comment by yellowcheese773** [comment]
> And just remember, you'll have to activate the virtual environment everytime you work with your project!

Thanks for your help. How exactly I do activate it? 

And I did run the script. It worked. Its definitely tougher then Remix.

**Comment by moonwake769** [comment]
> > I prefer to use Python [virtual environment](https://docs.python.org/3/library/venv.html) while installing `pip` packages for different projects. You can also try this method:
> > Run this commands in the folder where the scripts are saved:
> > ```
> > python3 -m venv venv
> > source venv/bin/activate
> > pip3 install py-solc-x
> > ```
> 
> OMG, THANK YOU VERY MUCH, it fuc*ing worked.
> 
> 1 small question: So I created this new virtual environment, when I want for example install eth-brownie does this also goes to the new environment?
> So do I need to do:
> 
> ```
> python3 -m venv venv 
> source venv/bin/activate
> pip3 install eth-brownie
> ```
> 
> Or can I just do `pip3 install etc-brownie`?

Yes, exactly. Just run this command in the same folder with the scripts to activate the virtual environment everytime you work with your project as @PatrickAlphaC said:
`source venv/bin/activate`

If you do only `pip3 install etc-brownie` without activating the virtual environment, it'll be saved in `/usr/local/lib/python3.9/site-packages`, which is not very good for large projects and might accur the errors as you experianced.

**Comment by yellowcheese773** [comment]
i

> > > I prefer to use Python [virtual environment](https://docs.python.org/3/library/venv.html) while installing `pip` packages for different projects. You can also try this method:
> > > Run this commands in the folder where the scripts are saved:
> > > ```
> > > python3 -m venv venv
> > > source venv/bin/activate
> > > pip3 install py-solc-x
> > > ```
> > 
> > 
> > OMG, THANK YOU VERY MUCH, it fuc*ing worked.
> > 1 small question: So I created this new virtual environment, when I want for example install eth-brownie does this also goes to the new environment?
> > So do I need to do:
> > ```
> > python3 -m venv venv 
> > source venv/bin/activate
> > pip3 install eth-brownie
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Or can I just do `pip3 install etc-brownie`?
> 
> Yes, exactly. Just run this command in the same folder with the scripts to activate the virtual environment everytime you work with your project as @PatrickAlphaC said:
> `source venv/bin/activate`
> 
> If you do only `pip3 install etc-brownie` without activating the virtual environment, it'll be saved in `/usr/local/lib/python3.9/site-packages`, which is not very good for large projects and might accur the errors as you experianced.

I want to quickly recap this. So when I do want to install for example eth-brownie or other pip packages I need to do it like that?
```
python3 -m venv venv 
source venv/bin/activate
pip3 install XXX
```
In this particular case with eth-brownie I have to do: 
```
python3 -m venv venv 
source venv/bin/activate
pipx install eth-brownie
```
And before installing eth-brownie I need to do:
```
python3 -m pip install --user pipx
python3 -m pipx ensurepath
```
Is this correct? Or am I missing something?

**Comment by noahliechti** [comment]
For me the error got solved when I run `python3 deploy.py` instead of `python deploy.py`. (without any virtual env's)

**Comment by thigur** [comment]
It's still an issue, unfortunately.

running python3 delploy.py gives this:
solcx.exceptions.SolcNotInstalled: solc 0.8.14 has not been installed. Use solcx.install_solc('0.8.14') to install.
