### ISSUE TITLE
Lesson 11 error while importing contracts from browine

### ISSUE THREAD

**Issue by DieKant** [smartcontractkit/full-blockchain-solidity-course-py#292]
In lesson 11 (before 10:47:15) when I try to run my deploy_and_create.py(for the advanced_collectible) I get this error where I can't import mocks from brownie

![image](https://user-images.githubusercontent.com/61691496/139593545-8effe48a-1cf4-477c-a4b5-966f89034234.png)

I can't understand what I'm missing, can someone help me pls?

**Comment by cromewar** [comment]
Did you add LinkToken.sol on contracts/tests? if you did, don't forget to compile the project again.

**Comment by DieKant** [comment]
Thank you very much @cromewar, I was indeed missing the contracts in the test folder which I forgot about

**Comment by cromewar** [comment]
I'm glad you solved it

**Comment by snowieoxs** [comment]
Is there a way to do this without adding them manually?, I did this but manually copied/pasted them in... and has me thinking about the brownie-mix folder I created a couple lessons ago... so when I start a new lesson I make a new directory, and use the "brownie init" command... it starts with blank folders, is the idea here to build in the brownie-mix folder? or somehow connect the new directory to the brownie mix folders? think I have read about it in the past, with the topic of "ven" but not sure...

**Comment by cromewar** [comment]
@snowieoxs This should help:
`brownie bake chainlink-mix`.
