### ISSUE TITLE
TypeError: from field must match key's 0x1973268d75BaFcf21C6D2dFF604a0d64d0158E50,  but it was 0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1

### ISSUE THREAD

**Issue by amaanullah-web** [smartcontractkit/full-blockchain-solidity-course-py#293]
I get this error i do not know what is happening please help me out with this problem
  from solcx import compile_standard, install_solc
  import json
  from web3 import Web3
  import os
  
  
  with open("./SimpleStorage.sol") as file:
      simple_storage_file = file.read()
      print(simple_storage_file)
  
  # Compile our solidity code
  install_solc("0.6.0")
  compiled_sol = compile_standard(
      {
          "language": "Solidity",
          "sources": {"SimpleStorage.sol": {"content": simple_storage_file}},
          "settings": {
              "outputSelection": {
                  "*": {"*": ["abi", "metadata", "evm.bytecode", "evnm.sourceMap"]}
              }
          },
      },
      solc_version="0.6.0",
  )
  with open("compiled_code.json", "w") as file:
      json.dump(compiled_sol, file)
  
  
  # get bytecode
  bytecode = compiled_sol["contracts"]["SimpleStorage.sol"]["SimpleStorage"]["evm"][
      "bytecode"
  ]["object"]
  
  # get abi
  abi = compiled_sol["contracts"]["SimpleStorage.sol"]["SimpleStorage"]["abi"]
  
  # for connecting to ganache
  w3 = Web3(Web3.HTTPProvider("http://127.0.0.1:8545"))
  chain_id = 1337
  my_address = "0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1"
  private_key = os.getenv("PRIVATE_KEY")
  
  
  # Create our first contract
  
  SimpleStorage = w3.eth.contract(abi=abi, bytecode=bytecode)
  
  # Getting the transaction counts
  nonce = w3.eth.getTransactionCount(my_address)
  
  # Build a transaction
  transaction = SimpleStorage.constructor().buildTransaction(
      {"chainId": chain_id, "from": my_address, "nonce": nonce}
  )
  
  # Sign a transaction
  signed_txn = w3.eth.account.sign_transaction(transaction, private_key=private_key)
  print("Deploying...")
  # Send a transaction
  send_txn = w3.eth.send_raw_transaction(signed_txn.rawTransaction)
  txn_receipt = w3.eth.get_transaction_receipt(send_txn)
  print("Deployed")
  
  # Working with contracts
  # Addresses
  # ABI
  simple_storage = w3.eth.contract(address=txn_receipt.contractAddress, abi=abi)
  print(simple_storage.functions.retrieve().call())
  
  store_txn = simple_storage.functions.store(15).buildTransaction(
      {"chainId": chain_id, "from": my_address, "nonce": nonce + 1}
  )
  
  store_signed_txn = w3.eth.account.sign_transaction(store_txn, private_key=private_key)
  print("Updating")
  send_store_txn = w3.eth.send_raw_transaction(store_signed_txn.rawTransaction)
  receipt_store_txn = w3.eth.get_transaction_receipt(send_store_txn)
  print("Updated")
  print(simple_storage.functions.retrieve().call())

**Comment by cromewar** [comment]
I seems you are using different key fot the same deployment, check if you have anything different with this: https://github.com/PatrickAlphaC/web3_py_simple_storage

**Comment by cromewar** [comment]
Y  Try this, go to ganache-ui and change the server configuration, changing the hostname and also the chain ID should be enough.

**Comment by cherick04** [comment]
@cromewar Ok, so I tried this approach and didn't work. For testing purposes, I deleted the workspace through the GUI where the 0xdbf...C505 address was, created a new workspace and tried to deploy my code connecting to this new workspace and it's still showing me the error where the 0x...C505 address is expected. In other words, I can't even connect to ganache instance through the GUI anymore!
I found this [post ](https://forum.openzeppelin.com/t/ganache-problems-not-completely-resetting-contracts-but-they-were-not-caused-by-ganache/1426/4) on OpenZeppelin where they seem to indicate to delete some json file manually. I'm just not sure if this applies in my case, and if it does, I can't seem to find this file

**Comment by cherick04** [comment]
@cromewar Figured it out! I had changed the .bashrc file and forgot I had my PRIVATE_KEY stored there, so the contract was always reading this, thus expecting the address associated with it! Rookie mistake... thank you though!!

**Comment by cromewar** [comment]
This things happens a lot @cherick04 I'm you solved the problem, so I'm closing this issue now.

**Comment by JCDC9919** [comment]
For those on Windows, an issue I had with this same error was forgetting to delete the environment variable set up in the previous task.

**Comment by rekatop** [comment]
hello friends, I am getting the same error but I could not fix the error. I am getting "TypeError: from field must match key's 0x6C4D37343C5e4AfaafB37033B29A4D12bD96b2A1, but it was 0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1" error.
It seems visual code storing the first address in somewhere but I could not figure out what is happening. Any help appreciated..

**Comment by cromewar** [comment]
@rekatop this is because is not getting the correct  private key, one is the default which comes with ganache and the other one is from your metamask account, so ins complaining because the obviously don't match.
So be sure you have the env variables exported

**Comment by shivansh7299** [comment]
Hi guys, even I'm having same issue. I tried deleting the environment  variable and I also deleted the workspace I created on ganache UI but now when I entered the private key and account key vs code is showing and taking the old private key which does not exists.

**Comment by JCDC9919** [comment]
@shivansh7299 did you try restarting and running a fresh terminal in VS
Code once you deleted out the old env variable?

**Comment by shivansh7299** [comment]
Yes I did that and it works!!!Thank you so much.

**Comment by JCDC9919** [comment]
@shivansh7299 you're welcome 👌

**Comment by IamXtova** [comment]
> @cromewar Figured it out! I had changed the .bashrc file and forgot I had my PRIVATE_KEY stored there, so the contract was always reading this, thus expecting the address associated with it! Rookie mistake... thank you though!!

**Comment by IamXtova** [comment]
I'm still having this issue and I can't see any .bashrc file > @cromewar Figured it out! I had changed the .bashrc file and forgot I had my PRIVATE_KEY stored there, so the contract was always reading this, thus expecting the address associated with it! Rookie mistake... thank you though!!

**Comment by cromewar** [comment]
No problem man, I'm glad it helped you @IamXtova

**Comment by IamXtova** [comment]
I still haven't figured it out. I still get Typeerror: from field must match keys

**Comment by akshually** [comment]
@IamXtova I had the same issue because I restarted my Ganache and it seems the private key and public keys were not matching anymore. Verify if both of them match before running

**Comment by cromewar** [comment]
Does this make sense for you @IamXtova ??

**Comment by IamXtova** [comment]
I found out I had opened another file in the same directory that was conflicting with the address I had gotten from ganache. I closed the file, and my code is working now. It's all sorted, thank you

**Comment by hdmodha** [comment]
Having the same issue, I deleted env variables and inserted new private_key in .env file after running ganache-cli --deterministic, then restarted and it worked.

**Comment by Amandeep404** [comment]
Hey can someone help me...I am facing the same issues on windows but unable to correct it.
Shows the same error as everyone else here :
```
TypeError: from field must match key's 0x090dC592fDF4d7adB16CCCf15262335DE66eD316, but it was 0x7052b17De0ccc1De68437b03b197bF3057E45807
```

Help will be Appreciated !!
