### ISSUE TITLE
Lesson 7 : Error "Call the contract method without broadcasting a transaction."

### ISSUE THREAD

**Issue by irwingtello** [smartcontractkit/full-blockchain-solidity-course-py#302]
Hello :D! , im struggling with this error , i dont know what is my fault

![aa](https://user-images.githubusercontent.com/28800239/139850119-5b1e02c3-b0e3-4d71-9695-4a882b3572a4.png)

This is how looks my project
![aaa](https://user-images.githubusercontent.com/28800239/139850639-b1d25cf3-954f-4bb5-b66b-28afe4201bc7.png)

And i added alchemy network like this:
brownie networks add development mainnet-fork cmd=ganache-cli host=http://127.0.0.1 fork=URL  accounts=10 mnemonic=brownie port=8545

i downloaded the interface[AggregatorV3Interface] contract fom here npm install @chainlink/contracts --save

My solidity code:
![aaaa](https://user-images.githubusercontent.com/28800239/139851062-937546f1-fede-4fa4-80a1-35de1e8376b1.png)

I stopped at 6:27:10 [Video] , im stuck :(

**Comment by ZakAyesh** [comment]
Hey! Could you make your project, as is, a public GitHub repo and link to it?
Also once you do, this question would make a great StackOverflow post if you don't mind making it there (linking to the GitHub repo and perhaps this issue for the pictures). 

https://stackoverflow.com/questions/ask?tags=chainlink

**Comment by irwingtello** [comment]
Sure, thanks!, i detected my error ,but i have a doubt about AggregatorV3 version
