### ISSUE TITLE
Lesson 11 Pinata api keys error

### ISSUE THREAD

**Issue by DieKant** [smartcontractkit/full-blockchain-solidity-course-py#316]
Hi all

I'm having an issue with the pinata api, when I try to upload my files this error pops up
![image](https://user-images.githubusercontent.com/61691496/140617415-1ed595cd-0bc9-47e2-a0ce-7bdec087109a.png)

my keys are stored like this in my .env

export PINATA_API_KEY=d88a99cdc680f3723da6
(secret key is also stored like this)

I'm I missing something?, The code is a perfect copy of the one at [this link](https://github.com/PatrickAlphaC/nft-demo/blob/main/scripts/upload_to_pinata.py) without the final if

**Comment by cromewar** [comment]
Sometimes you should re-export the variables, also make sure you are using them on the brownie-config file. The error seems to be you are setting up the variables without `""` as you see it says they must be strings.

**Comment by DieKant** [comment]
Hi , @cromewar

Thanks for the tip, I got it working by importing the keys form the .env with ${SOME_KEY} into the brownie-config file instead of using os.getenv
