### ISSUE TITLE
Lesson 4 - Keeping getting a weird INFO error but the program works fine, wondering if it is a serious issue.

### ISSUE THREAD

**Issue by agad98** [smartcontractkit/full-blockchain-solidity-course-py#329]
Whenever I run `C:/Python310/python.exe c:/Users/Ahmed/Documents/demos/web3_py_simple_storage/deploy.py` I get `INFO: Could not find files for the given pattern(s).`

Is this serious? I still get the compiled_code.json file outputted though

**Comment by cromewar** [comment]
You don't have anything to worry about is not an actual error, it happens due to the translation between cmd and powershell on windows.
