### ISSUE TITLE
Another Issue with Brownie, please help, can't get it to run deploy.py

### ISSUE THREAD

**Issue by agad98** [smartcontractkit/full-blockchain-solidity-course-py#340]
**Lesson 5: when trying to get Brownie to run the deploy.py with print in it**

When I run `brownie run scripts/deploy.py`

I get 
```
INFO: Could not find files for the given pattern(s).
Brownie v1.17.1 - Python development framework for Ethereum

BrownieSimpleStorageProject is the active project.

Launching 'ganache-cli.cmd --port 8545 --gasLimit 12000000 --accounts 10 --hardfork istanbul --mnemonic brownie'...
  File "C:\Python310\lib\site-packages\eth_brownie-1.17.1-py3.10.egg\brownie\_cli\__main__.py", line 64, in main
    importlib.import_module(f"brownie._cli.{cmd}").main()
  File "C:\Python310\lib\site-packages\eth_brownie-1.17.1-py3.10.egg\brownie\_cli\run.py", line 44, in main
    network.connect(CONFIG.argv["network"])
  File "C:\Python310\lib\site-packages\eth_brownie-1.17.1-py3.10.egg\brownie\network\main.py", line 50, in connect
    rpc.launch(active["cmd"], **active["cmd_settings"])
  File "C:\Python310\lib\site-packages\eth_brownie-1.17.1-py3.10.egg\brownie\network\rpc\__init__.py", line 75, in launch
    self.process = self.backend.launch(cmd, **kwargs)
  File "C:\Python310\lib\site-packages\eth_brownie-1.17.1-py3.10.egg\brownie\network\rpc\ganache.py", line 73, in launch
    return psutil.Popen(cmd_list, stdin=DEVNULL, stdout=out, stderr=out)
  File "c:\python310\lib\site-packages\psutil-5.8.0-py3.10-win-amd64.egg\psutil\__init__.py", line 1312, in __init__
    self.__subproc = subprocess.Popen(*args, **kwargs)
  File "C:\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
Launching 'ganache-cli.cmd --port 8545 --gasLimit 12000000 --accounts 10 --hardfork istanbul --mnemonic brownie'...
  File "C:\Python310\lib\site-packages\eth_brownie-1.17.1-py3.10.egg\brownie\_cli\__main__.py", line 64, in main
    importlib.import_module(f"brownie._cli.{cmd}").main()
  File "C:\Python310\lib\site-packages\eth_brownie-1.17.1-py3.10.egg\brownie\_cli\run.py", line 44, in main
    network.connect(CONFIG.argv["network"])
  File "C:\Python310\lib\site-packages\eth_brownie-1.17.1-py3.10.egg\brownie\network\main.py", line 50, in connect
    rpc.launch(active["cmd"], **active["cmd_settings"])
  File "C:\Python310\lib\site-packages\eth_brownie-1.17.1-py3.10.egg\brownie\network\rpc\__init__.py", line 75, in launch
    self.process = self.backend.launch(cmd, **kwargs)
  File "C:\Python310\lib\site-packages\eth_brownie-1.17.1-py3.10.egg\brownie\network\rpc\ganache.py", line 73, in launch
    return psutil.Popen(cmd_list, stdin=DEVNULL, stdout=out, stderr=out)
  File "c:\python310\lib\site-packages\psutil-5.8.0-py3.10-win-amd64.egg\psutil\__init__.py", line 1312, in __init__
    self.__subproc = subprocess.Popen(*args, **kwargs)
  File "C:\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by agad98** [comment]
- Brownie Version: v1.17.1
- Ganache-cli installed
- solc installed
- Python Version 3.10
- OS: Windows 10

Ganache-CLI is installed, if I run 
`npm install ganache-cli@latest --global`

I get:
```
removed 97 packages, changed 1 package, and audited 5 packages in 1s

found 0 vulnerabilities
```

but If i call on it with `ganache-cli` I still get the error
```
ganache-cli : The term 'ganache-cli' is not recognized as the name of a       
cmdlet, function, script file, or operable program. Check the spelling of     
the name, or if a path was included, verify that the path is correct and try  
again.
At line:1 char:1
+ ganache-cli
+ ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ganache-cli:String) [], Comma  
   ndNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by AnneCh** [comment]
Are you following the Youtube tutorial about blockchain/Python/Solidity, 16h? I'm doing it and I have the exact same problem, I'm stuck with Brownie not wanting to run the deploy.py script.... My error message is a bit different but it also shows this weird "INFO: Could not find files for the given pattern(s)." at the start of each terminal run.

Anyone can help?

**Comment by agad98** [comment]
Yes! I may have an idea or two on how I got it to work. First of all, what operating system are you using? 

I'm on Windows 10, my issue was (I believe) that I was using PowerShell for that portion of that lesson. It is hard to tell what Patrick is using because he's on a MacOS environment. I have like, 5 Macs lying around, I could have used them, but unfortunately my main PC is a Windows. 

Anyway, try switching to cmd from the dropdown menu shown below, that kinda did it for me.

![Screenshot 2021-11-11 163340](https://user-images.githubusercontent.com/67938589/141378761-8fe3915a-980d-468e-8fb6-c0da8add6a79.png)

First, I would so just open a cmd from the Start menu, check sequentially if you have the following. Yarn, if not then get it first, and run the command FROM that cmd window, not VSCode. Then check for Ganache-Cli, if not get it (just google and use the text in the option that says 'Use yarn'). 

Good luck!

**Comment by AnneCh** [comment]
Hi! 
Thank you for your answer! 
I'm on Windows 10 as well, I do have Yarn and Ganache-cli, but running through the cmd window still doesn't do it for me... Thanks anyway! If I find a solution on my side, I'll update my answer here in case that helps someone.

Have a good day!

**Comment by mebedel** [comment]
have you done
1. npm install yarn first then 
2. 2.npm install ganache-cli@latest --global and after that 
3. 3.installing brownie

**Comment by AnneCh** [comment]
I have indeed... here is where I'm stuck : https://ethereum.stackexchange.com/questions/113427/cannot-run-the-script-through-brownie-deploy-py?noredirect=1&lq=1

**Comment by mebedel** [comment]
how did you install brownie did you use pipx or pip?

**Comment by mebedel** [comment]
the problem might also be path related i had something similar it took me over 5 days 
1.i deleted all pythons 
2. nodejs 
3. vscode
4. checked all my folders for python, pip, pipx, brownie and deleted everything i found 
5. then i went to temporary files searched all python,pipx, pip, brownie and deleted them
6. then i went to sysdm.cpl to enviroment variables (i checked paths to files that i might have missed on my delete spree)
7. after deleting all the files that i found using env variables 
8. i also deleted all python related paths
9. i hope this helps
10.

**Comment by mebedel** [comment]
![Näyttökuva (70)](https://user-images.githubusercontent.com/90156945/142554666-8af7d7b9-aa82-4ea3-949f-be31f1efe031.png)

click that spot where arrow is pointing and try to check if you have multiable options for python 
for me it stopped recognising brownie but after changing python path it recognised brownie again

**Comment by mebedel** [comment]
this is last resort 

the problem might also be path related i had something similar it took me over 5 days 
1.i deleted all pythons 
2. nodejs 
3. vscode
4. checked all my folders for python, pip, pipx, brownie and deleted everything i found 
5. then i went to temporary files searched all python,pipx, pip, brownie and deleted them
6. then i went to sysdm.cpl to enviroment variables (i checked paths to files that i might have missed on my delete spree)
7. after deleting all the files that i found using env variables 
8. i also deleted all python related paths
9. i hope this helps

**Comment by AnneCh** [comment]
Hi! Thanks for the help, I think I'll have to use the last resort... 
A week ago, I had Python 3.10 but yarn wouldn't run on it, so I downgraded to Python 3.9. But, when I tried to install brownie through pipx, an error message came back saying that it couldn't find Python310. I deleted everything and tried again, but the same message came back. Using pip was the only way I could get to Brownie, but then again, the script won't run.

Thank you for detailing the files to be deleted, I must have forgotten some on the way. I'll do that more thoroughly and try again. This weekend I'll have access to another computer (also Windows 10) and try on it, see if the same problem occurs.

**Comment by AnneCh** [comment]
Ok so I uninstalled every single thing and some of the issue seems to be gone. I think I have a problem with the compiler now, as brownie doesn't automatically compile the .sol file that I made. But man, thank you. I definitely had missed some files in deleting everything, and your message helped me figure out which ones (temporary files mostly).

**Comment by mebedel** [comment]
Let me know if anything comes up cos this helps me to learn also.

here is little tips:
1. Follow videos installing order. 
2. Check the message with pictures if you have other project that need venv cos vscodes auto runs scripts\activate.bat from cmd (I have no idea why I almost used last resort all over again yesterday 😭)
3. Be calm and check typos I have wasted hours because there was typo in brownie-config.yaml 


Good luck.

**Comment by mebedel** [comment]
Take screen shot cos am not on the pc

**Comment by mebedel** [comment]
Also check brownie-config files for typos

**Comment by AnneCh** [comment]
<img width="1280" alt="20 11 21" src="https://user-images.githubusercontent.com/49056897/142725126-c884bc70-a57a-4f59-859c-bc14820d4f89.png">

here you go! 

I'll check the config files today, although I'm not sure what kind of typos I should be looking for (still totally new to all that :D), thank you so much for the help!

**Comment by mebedel** [comment]
Am on this course 
https://m.youtube.com/watch?v=M576WGiDBdQ

**Comment by mebedel** [comment]
he is using solidity 0.6.6 most of the time

**Comment by AnneCh** [comment]
Yeah I'm on the same course and with version 0.6 it kept not working,
throwing multiple errors and the only way i found to move forward was to
use another version

**Comment by AnneCh** [comment]
<img width="1280" alt="20 11 21 2" src="https://user-images.githubusercontent.com/49056897/142732344-bdf4d036-4b06-4f55-bd06-cadf08685017.png">
Somehow the compile works now and the .json file has been created once I ran the script.
