### ISSUE TITLE
Pip install web3

### ISSUE THREAD

**Issue by adrnlm** [smartcontractkit/full-blockchain-solidity-course-py#353]
![image](https://user-images.githubusercontent.com/42228438/141651027-5473afe9-e25f-4d17-bbad-ce07393fd4ce.png)

I can't seem to install web3 and its been giving me these errors

![image](https://user-images.githubusercontent.com/42228438/141651038-f8732674-871e-4447-9072-c8036b013463.png)
![image](https://user-images.githubusercontent.com/42228438/141651044-6a3000dc-ddcf-44cb-ae45-ebd6ebbf3c3f.png)

**Comment by Edu-BS** [comment]
I had the same problem and I solved it here https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory/57698471#57698471
In my case I ran the following code:
`sudo dnf install python3-devel`

**Comment by adrnlm** [comment]
Thank you for that.

**Comment by mebedel** [comment]
if you have windows here is solution

**Comment by mebedel** [comment]
https://www.youtube.com/channel/UC7IeXmyzdIM1HWKoHfi_lng

**Comment by hetdagli234** [comment]
I have the same issue but in mac, none of the above mentioned solutions work for me.

**Comment by mebedel** [comment]
This issue is closed make a new issue so pro users of Mac can help you good luck
