### ISSUE TITLE
python dotenv error

### ISSUE THREAD

**Issue by gunomnifluencer** [smartcontractkit/full-blockchain-solidity-course-py#357]
Hello,

when I trying to import dotenv I got message : 
_Import "dotenv" could not be resolved_

is there alternative besides dotenv?

please help,
Thanks

**Comment by DieKant** [comment]
Hi @gunomnifluencer

Are you trying to import the .env varaibles directly from python? Or you don't understand how to pull the variables in the .env inside your python script?

**Comment by gunomnifluencer** [comment]
this problem has fixed,

I just forgot to close and re-open terminal after install pip dotenv

thank you
