### ISSUE TITLE
Solidity extension on VSCode causing SSH disconnection issue?

### ISSUE THREAD

**Issue by toddabraham** [smartcontractkit/full-blockchain-solidity-course-py#36]
But....the SSH disconnection issue remains.  It seems as long as I'm working in my deploy.py file, no issues occur, the connection is stable.

However, as soon as I touch my .sol file, the issue occurs....

![image](https://user-images.githubusercontent.com/26919212/133651283-8ff26f27-36a5-4478-96b5-3df058676297.png)

_Originally posted by @toddabraham in https://github.com/smartcontractkit/full-blockchain-solidity-course-py/discussions/24#discussioncomment-1343298_

**Comment by PatrickAlphaC** [comment]
Responded in the comment. 

Looks like this is something wrong with your VSCode...

**Comment by PatrickAlphaC** [comment]
Closing for now, feel free to follow up
