### ISSUE TITLE
Cannot import name 'MockV3Aggregator' from 'brownie'

### ISSUE THREAD

**Issue by Green-Tea** [smartcontractkit/full-blockchain-solidity-course-py#363]
![Code_WqCV6pKMdW](https://user-images.githubusercontent.com/35417429/141776897-8fe05601-fb72-4703-8345-bf2cd347d0f0.png)

I believe I have  done the import line correctly:
`from brownie import FundMe, network, config, MockV3Aggregator`

Even tried copy pasting the code, still have the same issue

**Comment by RohanNero** [comment]
Did you figure it out?
