### ISSUE TITLE
INFO: Could not find files for the given pattern(s)

### ISSUE THREAD

**Issue by adrnlm** [smartcontractkit/full-blockchain-solidity-course-py#371]
![image](https://user-images.githubusercontent.com/42228438/142009743-c6905319-a036-41e5-98e5-4b1ae82d812a.png)

I've been seeing this issue pop up but it has not been affecting my results. I'm worried that it could be an issue as I'm running subsystem for linux on windows in order to use bash. Would there be a way around this to satisfy this warning/ info?

**Comment by cromewar** [comment]
Hello @adrnlm you have nothing to worry about, that's not an actual problem, is related to the instruction translation between windows consoles, I suppose you are using git terminal or ubuntu terminal.

Anyways if you want to get rid of it, you may install windows terminal from microsoft store.

Best regards, Cromewar.
