### ISSUE TITLE
how do applications buy bitcoin/cryptocurrency??

### ISSUE THREAD

**Issue by AtharvaGangji** [smartcontractkit/full-blockchain-solidity-course-py#386]
I just want to ask that, if i want to `invest in bitcoin` then i need to signup on an application like [coindcx](https://coindcx.com) or [coinbase](https://coinbase.com). And then i can buy bitcoin from them by giving money, but from where do these applications buy bitcoin from and give us???

**Comment by cromewar** [comment]
To know how new bitcoins are created please refer to this link: https://river.com/learn/who-creates-new-bitcoin/

Best regards, Cromewar.
