### ISSUE TITLE
Lesson 7: test_can_pick_winner fails even when run on the rinkeby network

### ISSUE THREAD

**Issue by mattheweller** [smartcontractkit/full-blockchain-solidity-course-py#393]
Hi there, after completing lesson 7, I disappointingly could not get  test_can_pick_winner to pass, even when I ran it with the following command:

`brownie test -k test_can_pick_winner --network rinkeby -s` while using the [source repo](https://github.com/PatrickAlphaC/smartcontract-lottery) and still got the same AssertionError: '0x0000000000000000000000000000000000000000'

My .env is the same as it's been for the other projects:

```
export PRIVATE_KEY=...(Redacted)
export WEB3_INFURA_PROJECT_ID=...(Redacted)
export ETHERSCAN_TOKEN=...(Redacted)
```

I'm mainly looking for things that I could try to troubleshoot.  I can't think what might be  the cause. Thanks!

**Comment by ForgetfulLenny** [comment]
Hi. Increasing the time.sleep (60) -> time.sleep (180) parameter in the def test_can_pick_winner () function helped me.

**Comment by mattheweller** [comment]
Hey - thanks! Setting `time.sleep(180)` in both the deploy function and the test worked for me!
