### ISSUE TITLE
Lesson 13 deploying to Kovan

### ISSUE THREAD

**Issue by ignaciocanosa** [smartcontractkit/full-blockchain-solidity-course-py#400]
I get this error deploying the last lesson to Kovan

KeyError: 'smartcontractkit/chainlink-brownie-contracts@0.2.2/BufferChainlink'

Any idea what I might be doing wrong? Details below...

Cheers!

Brownie v1.16.4 - Python development framework for Ethereum

DefiStakeYieldBrownieProject is the active project.

Running 'scripts\deploy.py::main'...
Transaction sent: 0xb296e1f3bd511d80d0b6105846a271f098f2d180ef241842056562289d6b7ebe
  Gas price: 2.750000007 gwei   Gas limit: 702941   Nonce: 36
  DappToken.constructor confirmed   Block: 28445494   Gas used: 639038 (90.91%)
  DappToken deployed at: 0xc413801bD4AE07fF2622a3a32B012720B4ac4D31

Transaction sent: 0x662aee8345e74eb140b8976f97cbbcb28e5124593d572de7ef6ed11dfbaf9806
  Gas price: 2.750000007 gwei   Gas limit: 1198897   Nonce: 37
  TokenFarm.constructor confirmed   Block: 28445496   Gas used: 1089907 (90.91%)
  TokenFarm deployed at: 0xeEb741322EF52530f1fDA908aDcD1E1eD7A3c575

  File "C:\Users\Pedro, line line, in in
    return_value, frame = run(
  File "C:\Users\Pedro, line line, in in
    return_value = f_locals[method_name](*args, **kwargs)
  File ".\scripts\deploy.py", line 95, in main
    deploy_token_farm_and_dapp_token(update_front_end_flag=True)
  File ".\scripts\deploy.py", line 15, in deploy_token_farm_and_dapp_token
    token_farm = TokenFarm.deploy(
  File "C:\Users\Pedro, line line, in in
    return tx["from"].deploy(
  File "C:\Users\Pedro, line line, in in
    contract.publish_source(deployed_contract, silent=silent)
  File "C:\Users\Pedro, line line, in in
    contract_info = self.get_verification_info()
  File "C:\Users\Pedro, line line, in in
    build_json = self._project._build.get(name)
  File "C:\Users\Pedro, line line, in in
    return self._interfaces[key]
KeyError: 'smartcontractkit/chainlink-brownie-contracts@0.2.2/BufferChainlink'

**Comment by DieKant** [comment]
Hi @ignaciocanosa 

I think I had this [very same issue](https://github.com/smartcontractkit/full-blockchain-solidity-course-py/issues/354), I solved it by upgrading brownie to the latest version.
To do this you need to run the command "pipx upgrade eth-brownie" on your terminal

**Comment by ignaciocanosa** [comment]
Thanx @DieKant ... Solved using Python 9 in sted of 10 and installing latest Brownie version.
