### ISSUE TITLE
Method eth_maxPriorityFeePerGas not supported

### ISSUE THREAD

**Issue by naticio** [smartcontractkit/full-blockchain-solidity-course-py#405]
I get this error after building, signing and trying to send a transaction.

**Method eth_maxPriorityFeePerGas not supported, code': -3200**

 does anybody know how to fix it? thanks

File "/Users/Nat-Serrano/Library/Mobile Documents/com~apple~CloudDocs/demos/web3_py_simple_storage/env/lib/python3.9/site-packages/web3/manager.py", line 171, in formatted_response
    raise ValueError(response["error"])
ValueError: {'message': 'Method eth_maxPriorityFeePerGas not supported.', 'code': -32000, 'data': {'stack': 'Error: Method eth_maxPriorityFeePerGas not supported.\n    at GethApiDouble.handleRequest (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/subproviders/geth_api_double.js:70:16)\n    at next (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:136:18)\n

**Comment by cromewar** [comment]
hello @naticio as you can see on this thread https://github.com/smartcontractkit/full-blockchain-solidity-course-py/discussions/409 your hsould update your web3 version.

**Comment by naticio** [comment]
thanks, I already have web3 5.25, I assume it's something related to env...should I just skip it because we'll use other tools to handle web3??

Requirement already satisfied: web3 in ./env/lib/python3.9/site-packages (5.25.0)

**Comment by cromewar** [comment]
You will use brownie which manages web3 stuff for you so yes... but anyways try using another virtualenv.

**Comment by shonendumm** [comment]
@naticio The error is solved here
https://github.com/PatrickAlphaC/web3_py_simple_storage/issues/8#issuecomment-974851350

https://stackoverflow.com/questions/70051896/python-web3-and-ganache-error-method-eth-maxpriorityfeepergas-not-supported/70053558#70053558

**Comment by cromewar** [comment]
Thanks @shonendumm  your are awesome.

**Comment by naticio** [comment]
that was it, thanks! @shonendumm
