### ISSUE TITLE
from agent: agent refused operation

### ISSUE THREAD

**Issue by depling** [smartcontractkit/full-blockchain-solidity-course-py#410]
I can not hack the method to clone a repository to my box.  When I try I get a pop-up call telling me my key is locked and inaccessible and calling for a password to unlock it.  I am unable to tell from the dialog whether it is github cli or my local system asking, but neither password works.  There is a difference between when I attempt to just 'gh repo clone' and when I attempt 'sudo gh repo clone', which I find weird.  In the case of 'sudo', the github cli asks if I want to reauthenticate, but doing so makes no difference.

**Comment by cromewar** [comment]
As you said you never should use sudo for github stuff, in your case I suggest you con configure a ssh key for your github account, follow this guide: https://docs.github.com/en/enterprise-server@3.0/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account
