### ISSUE TITLE
Lesson 13, error with test_issue_token test: "VirtualMachineError: revert: Index out of range"

### ISSUE THREAD

**Issue by DieKant** [smartcontractkit/full-blockchain-solidity-course-py#426]
Hi all

When I try to execute the test I get this error, I copy pasted the code form the repo to see if I wrote something bad in the contract or on the test but that wasn't the problem, the error seems to occur when when I call "token_farm.issueTokens({"from": account})"

![image](https://user-images.githubusercontent.com/61691496/142946907-53dde6ed-af5a-4f6a-ad61-a4103e1b07a3.png)

Can someone help me please?

**Comment by mebedel** [comment]
it happened to me am in lesson 7. 
It happenend if i didnt wait for a while before the next test. 
I think local ganache cannot deal with many request in  a row.
Your case might also diffrent from mine

**Comment by mebedel** [comment]
in lesson 7 i had a typo. I didn't write def test_function() instead i wrote def function() and i ran tests one after another and it led to error you mentioned. 
1. do a simple test first just to see if it goes through
2. if it does go through you might have typo somewhere in the code  
hopefully am not too confusing

**Comment by DieKant** [comment]
> it happened to me am in lesson 7. It happenend if i didnt wait for a while before the next test. I think local ganache cannot deal with many request in a row. Your case might also diffrent from mine

Hi @mebedel 

What t is different is that I'm running the test on his own with the -k option so I don't have to wait for "Other tests",
I tryed to add a wait(1) to the issueToken transaction as it causes problems sometimes but this wasn't the case either

@PatrickAlphaC could you check this out please?

**Comment by PatrickAlphaC** [comment]
Hm... Odd. 

Yes could you make this a stack exchange ETH question and then post the link to it here?

Please copy-paste and format the error message instead of using a screenshot

**Comment by DieKant** [comment]
> Hm... Odd.
> 
> Yes could you make this a stack exchange ETH question and then post the link to it here?
> 
> Please copy-paste and format the error message instead of using a screenshot

I solved this error, I had written <= instead of < in the issueToken for loop but now the assert is failing

[here's the link to the question](https://ethereum.stackexchange.com/questions/114334/brownie-python-test-fails-assert-phase)

**Comment by PatrickAlphaC** [comment]
Nice work!!!
