### ISSUE TITLE
Rinkeby Faucet Offline

### ISSUE THREAD

**Issue by bobobear97** [smartcontractkit/full-blockchain-solidity-course-py#459]
Hello,

I'm trying to get some Eth on the Rinkeby Test Network but when I go to the site it states that Rinkeby is Offline. Does anyone know why this is?

My address is pasted below if someone could maybe share some of their test Eth.

0x9628431c47914a172b4BaEA40f5F18F2cF59d3eb

Thanks!

**Comment by bobobear97** [comment]
Follow Up:

I was able to get test eth on the Kovan test network, is there a reason as to why I can't use Kovan over Rinkeby as my testnetwork?

**Comment by cromewar** [comment]
Rinkeby faucet is not working you could use chainlinks faucet, anyways I'll send you ether to your rinkeby wallet.

**Comment by bobobear97** [comment]
Thanks for the help, I received your eth and was able to get some from chainlinks faucet!
