### ISSUE TITLE
Lesson 6 - solc_version=compiler_config["solc"].get("version", None), AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by XRP97** [smartcontractkit/full-blockchain-solidity-course-py#484]
Hi -  an error while running (brownie compile); please advise. 

dependencies:

 - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler:
  solc:
  remappings:
    - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'

![Screen Shot 2021-12-03 at 8 58 17 AM](https://user-images.githubusercontent.com/77907623/144615184-5d4be456-9e03-4246-a45e-62b515e995e9.png)

**Comment by cromewar** [comment]
Hello there @XRP97 you have a indentation error on line 11, you should leave a empty space, something like this:
![image](https://user-images.githubusercontent.com/20199180/144684043-816454e3-9c7d-447a-a93f-2e0a6904305f.png)

**Comment by XRP97** [comment]
@cromewar Thank you.

**Comment by kellspell** [comment]
thanks guys
