### ISSUE TITLE
Errors with deploy.py

### ISSUE THREAD

**Issue by narainp** [smartcontractkit/full-blockchain-solidity-course-py#491]
My deploy.py file:

```Python
import json
from web3 import Web3
from solcx import compile_standard, install_solc

with open("./SimpleContract.sol", "r") as file:
    simple_storage_file = file.read()
    print(simple_storage_file)

    install_solc("0.6.0")

    # compile our solidity
    compiled_sol = compile_standard(
        {
            "language": "solidity",
            "sources": {"SimpleStorage.sol": {"content": simple_storage_file}},
            "settings": {
                "outputSelection": {
                    "*": {"*": ["abi", "metadata", "evm.bytecode", "evm.sourceMap"]}
                }
            },
        },
        solc_version="0.6.0",
    )
    print(compiled_sol)
```

executing deploy.py now has following errors:

raceback (most recent call last):
  File "deploy.py", line 22, in <module>
    solc_version="0.6.0",
  File "C:\Python37\lib\site-packages\solcx\main.py", line 401, in compile_standard
    error_dict=compiler_output["errors"],
solcx.exceptions.SolcError: Only "Solidity" or "Yul" is supported as a language.

**Comment by cromewar** [comment]
hello @narainp you have this line:

`"language": "solidity",`
Solidity must be uppercase, so you should have.

`"language": "Solidity",`

**Comment by moonwake769** [comment]
Hello @narainp ,

I noticed from your 'deploy.py' file, that you are trying to open and read 'SimpleContract.sol' contract, while you indicate in 'compile_standard' function:
'''
"sources": {"SimpleStorage.sol": {"content": simple_storage_file}},'. 
'''
I assume that 'SimpleContract.sol' and 'SimpleStorage.sol' are 2 different files.

**Comment by narainp** [comment]
Thanks. Resolved.
