### ISSUE TITLE
Lesson 13, error with npx while creating new react app

### ISSUE THREAD

**Issue by DieKant** [smartcontractkit/full-blockchain-solidity-course-py#494]
Hi all

I'm trying to create a new react project as in the tutorial with the command "npx create-react-app front_end --template typescript", but it outputs an error
This is the error

npx create-react-app front_end --template typescript        
npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Fedro\AppData\Roaming\npm-cache\_logs\2021-12-05T15_28_00_948Z-debug.log      
Installazione di [ 'create-react-app@latest' ] fallita con codice 1

So far all i found about it is [this article](https://newbedev.com/typeerror-cb-apply-is-not-a-function) and [this git issue](https://github.com/nodejs/help/issues/2874) but neither are fixing the issue

Can someone help me, ?
Thanks

**Comment by cromewar** [comment]
Does this works for you? 
https://stackoverflow.com/questions/63429304/npm-err-cb-apply-is-not-a-function

**Comment by DieKant** [comment]
Hi @cromewar

Unfortunally that stackoverflow article does not works for me

**Comment by cromewar** [comment]
A little question, how did you installed npm?
I always recommend to use WSL instead.

**Comment by DieKant** [comment]
Hi @cromewar

I installed npm, node and everything with a classic windows installation.

However the issue is solved, basically I analyzed deeper into that git issue I linked at the start of the thread, basically the procedure is as follows

-delete everything node/npm related, even path variables
-reinstall node/npm, rewrite path variable and move them to the 2 highest position in your path variable list
-restart pc
-reinstall yarn, etc... , rewrite path variable and move them to the highest position in your path variable list
-restart pc
-solved

Also I read your article about WLS just now and I might consider to switch to it

**Comment by cromewar** [comment]
That's great @DieKant and the solution was kinda specific, I'm glad you solved tough.
