### ISSUE TITLE
"Import Brownie could not be resolved"

### ISSUE THREAD

**Issue by yellowcheese773** [smartcontractkit/full-blockchain-solidity-course-py#50]
Its basically the same problem with solcx a few days ago, but its not working with a virtual environment either. 

So I copied every step from Patrick. 

i installed pipx:
`python3 -m pip install --user pipx `

Then: 
`python3 -m pipx ensurepath`

Then I've installed brownie and it works perfectly fine. 

<img width="1331" alt="Bildschirmfoto 2021-09-18 um 11 29 41" src="https://user-images.githubusercontent.com/80122924/133884630-855bf0e4-2baa-4c57-843a-2cc37f62090c.png">

I can even compile stuff, its working: 

<img width="1331" alt="Bildschirmfoto 2021-09-18 um 11 33 22" src="https://user-images.githubusercontent.com/80122924/133884665-4f1935a8-16ba-43d0-b1b6-2b188c3deac1.png">

Here comes the problem. "Import Brownie could not be resolved":
<img width="1331" alt="Bildschirmfoto 2021-09-18 um 11 41 32" src="https://user-images.githubusercontent.com/80122924/133884696-ec36eb3c-7ee4-4e9e-a203-668ee74b7b4a.png">

Then I remembered, maybe I need a virtual environment. So deleted the folder brownie_simple_storage and started again from scratch.

`mkdir brownie_simple_storage` 

Open the folder.

I created the virtual environment `python3 -m venv tutorial-env` activated it `source tutorial-env/bin/activate` after that I've installed everything on the virtual env, tried `brownie init` and it didn't work, it showed an Error. 

To solve this I deleted the virtual environment tried `brownie init` again and then brownie worked. 

So I did understand that `brownie init` must come first, after that comes the virtual environment, otherwise it won't work. 

So after `brownie init` I create the virtual environment `python3 -m venv venv` after that I activate it `source venv/bin/activate`, so it look like this: 

<img width="1331" alt="Bildschirmfoto 2021-09-18 um 12 52 22" src="https://user-images.githubusercontent.com/80122924/133886345-bea68f55-6733-47fa-9a39-d6606a84f7ad.png">

After that I try to install` python3 -m pip install --user pipx` on the venv, it don't work, I take out the `--user` it works. 

Then I do `python3 -m pipx ensurepath`, no error. 

I do install eth-brownie successfully. I do have pipx and pip installed successfully.

 `pip list`, `pipx list`:

<img width="941" alt="Bildschirmfoto 2021-09-18 um 12 58 47" src="https://user-images.githubusercontent.com/80122924/133886530-2f888b89-8531-49d4-8eed-1b9cd2290e0e.png">

`brownie --version`, `pip --version`, `pipx --version`:

<img width="954" alt="Bildschirmfoto 2021-09-18 um 13 06 32" src="https://user-images.githubusercontent.com/80122924/133886694-accb7954-ccfb-45e5-ae82-b4361d5fbc27.png">

Unfortunately its still not working, can't import from Brownie. I have a guess that maybe somethings wrong with the Path. 

I know its a really long Issue, but I wanted to show every detail. 

I would be really thankful if somebody could help me out.

**Comment by ChakibHi** [comment]
Did you try to run a script using for example "`brownie run scripts/deploy.py`"?

I always discard yellow problems from VS, and everything works, even if it says "**Import "brownie" could not be resolved**"

**Comment by yellowcheese773** [comment]
> brownie run scripts/deploy.py

It worked. It really fucking worked like that. Thank you very much. 

You know because last time in solcx when I compiled, it didn't work, so I thought it won't work here also, so I didn't even try to  do `brownie run scripts/deploy.py`.

<img width="1331" alt="Bildschirmfoto 2021-09-18 um 15 36 12" src="https://user-images.githubusercontent.com/80122924/133890767-d572120b-93d7-49c6-825c-188cdd8da9cc.png">

Thx man, big love

**Comment by ArsenPe** [comment]
To get rid of the yellow warning the suggestion for VS code from [here](https://ethereum.stackexchange.com/questions/114841/failed-brownie-import-when-running-scripts/114857) helped me:
- Ctrl+Shift+P (or Ctrl+Cmd+P on Mac) 
- Python: select Interpreter 
- Choose the python in your virtenv, e.g ` ~/.local/pipx/venvs/eth-brownie/bin/python`

**Comment by louisamira** [comment]
This seems like some voodoo magic to me. @ArsenPe can you give any more details on how you were able to change that? I've got this screenshot here as the closest I can get.

![Screen Shot 2021-12-19 at 10 25 22 AM](https://user-images.githubusercontent.com/17260244/146680626-77585e06-c15b-4fae-af53-4a741a0c8ac9.png)

**Comment by ArsenPe** [comment]
@louisamira: 
1. Click Python: Select Interpreter ![image](https://user-images.githubusercontent.com/75928581/146803603-92572427-7370-49ba-bcd2-c023a5cd6ca4.png)
2. Click Enter interpreter path... 
![image](https://user-images.githubusercontent.com/75928581/146803852-567758f2-818f-4912-ab6f-722de73d6827.png)

That's should be it :slightly_smiling_face:
