### ISSUE TITLE
Pip install Web3

### ISSUE THREAD

**Issue by Waji-nk** [smartcontractkit/full-blockchain-solidity-course-py#525]
I'm going through tutorial and pip is not installing web3, I tried different solutions on the internet but nothing is working. Here's the screenshot of error
<img width="1280" alt="Screenshot 2021-12-09 at 5 27 37 PM" src="https://user-images.githubusercontent.com/18221569/145396546-82ef8356-c2e6-491c-9e16-9b653ca773f7.png">

**Comment by moonwake769** [comment]
Hello @Waji-nk, could you try to run `pip3 install eth-brownie`? This is a package which also includes `web3`.

**Comment by Waji-nk** [comment]
> Hello @Waji-nk, could you try to run `pip3 install eth-brownie`? This is a package which also includes `web3`.

It looks like i was missing command line tools, i reinstall that from developer.apple and got it fixed
