### ISSUE TITLE
rinkeby faucet offline

### ISSUE THREAD

**Issue by Foma-78** [smartcontractkit/full-blockchain-solidity-course-py#536]
Hello,

I'm trying to get some Eth on the Rinkeby Test Network but when I go to the site it states that Rinkeby faucet offline. Does anyone know why this is?

My address is pasted below if someone could maybe share some of their test Eth.

0x4f1B53FA42690C210717F9437006a9D5C4e86c79

Help me please!

**Comment by cromewar** [comment]
Sent: https://rinkeby.etherscan.io/tx/0x6be20b35be1ec65a761f81180c1dda0e5ecad2375f5da6947b0b73fd9b8fb7de

**Comment by jethr0null** [comment]
@Foma-78 For future reference (and to possibly help others who might run come across this issue without first seeing the updated faucet links in the course [README](https://github.com/smartcontractkit/full-blockchain-solidity-course-py#readme)) you can also request testnet ETH from the Chainlink testnet [faucet](https://faucets.chain.link/rinkeby) (.1 ETH per request). I haven't personally found any other reliable faucets that fund larger amounts of ETH on the Rinkeby testnet. This one has been a good option for deploying/testing small contracts when I've needed to deploy to a testnet. If you don't need to interact with any contracts on the public blockchain there are also other deployment options such as a local blockchain (e.g. using Ganache) or the JavaScript VM deployment option in Remix for example.

**Comment by Tunchie522** [comment]
Please I also need some rinkeby facucet.Thanks 

0x3D0b6cd4507E7A4Fb85E8f92A0E43cC0c9d45316

**Comment by Tunchie522** [comment]
Can you help with some rinkeby eth on 0x3D0b6cd4507E7A4Fb85E8f92A0E43cC0c9d45316 please 
> Sent: https://rinkeby.etherscan.io/tx/0x6be20b35be1ec65a761f81180c1dda0e5ecad2375f5da6947b0b73fd9b8fb7de

**Comment by cromewar** [comment]
@Tunchie522 Sent https://rinkeby.etherscan.io/tx/0x172c1812fd55b97afbf80da75fe9a905319b3146d925b00736869c36774e81ea
