### ISSUE TITLE
Lesson 7: test_can_pick_winner fails with `ValueError: already known` error

### ISSUE THREAD

**Issue by noopurphalak** [smartcontractkit/full-blockchain-solidity-course-py#574]
I have reached 8:16:20 in the video.

The test_can_pick_winner test is written as follows:

```python
def test_can_pick_winner():
    if network.show_active() in helpful_scripts.LOCAL_BLOCKCHAIN_ENVIRONMENTS:
        pytest.skip()
    lottery = deploy_lottery.deploy_lottery()
    account = helpful_scripts.get_account()
    lottery.startLottery({"from": account}).wait(1)
    lottery.enter({"from": account, "value": lottery.getEntranceFee()}).wait(1)
    lottery.enter({"from": account, "value": lottery.getEntranceFee()}).wait(1)
    helpful_scripts.fund_with_link(lottery.address)
    lottery.endLottery({"from": account}).wait(1)
    time.sleep(180)
    assert lottery.recentWinner() == account
    assert lottery.balance() == 0
```
But I am getting the following error as given in the below screenshot:

![test_error](https://user-images.githubusercontent.com/8924488/146192048-c1e38b63-2530-4d6a-84d6-385b639ab3b8.png)

Can somebody help me with what is exactly happening?

**Comment by cromewar** [comment]
Hello @noopurphalak the already know error happens when the contract is already on the mempool and it was unfinished, just restart your computer and it should work.

**Comment by noopurphalak** [comment]
@cromewar thanks for your reply. After a few retries the contract was finally deployed and I was able to move ahead.
