### ISSUE TITLE
Lesson 5 error, not importing brownie

### ISSUE THREAD

**Issue by louisamira** [smartcontractkit/full-blockchain-solidity-course-py#594]
Code appears to be correct, and I've taken all the relevant steps to install everything -- but things are starting to fail and my suspicion is because `import brownie` is having issues.

![Screen Shot 2021-12-18 at 10 31 41 AM](https://user-images.githubusercontent.com/17260244/146646539-0144bb25-2723-4e9b-a3fb-d9d3bb199139.png)

Output is below...
```
x@y brownie_simple_storage % brownie accounts list
Brownie v1.17.2 - Python development framework for Ethereum

Found 1 account:
 └─freecodecamp-account: 0xE8081...9440c
x@y brownie_simple_storage % brownie run scripts/deploy.py
Brownie v1.17.2 - Python development framework for Ethereum

BrownieSimpleStorageProject is the active project.

Launching 'ganache-cli --port 8545 --gasLimit 12000000 --accounts 10 --hardfork istanbul --mnemonic brownie'...
hello as test

Running 'scripts/deploy.py::main'...
Terminating local RPC client...
x@y brownie_simple_storage % 
```

I would've expected the account to print (as shown in the video @ 4:38:33) -- but it didn't.

**Comment by cromewar** [comment]
This happens when you install brownie using pipx, if you want to get rid of this you should install brownie using just pip, regarding to the print statement, you should print `account.address`

**Comment by louisamira** [comment]
Ok, I can disregard the first part but the second part isn't working. I tried importing both "accounts" and "account" and changing the associated code as you outlined. Still can't get it to work.

![Screen Shot 2021-12-19 at 10 27 39 AM](https://user-images.githubusercontent.com/17260244/146680733-b582a34b-e236-44e9-abac-f4be9d1f2265.png)

```
Launching 'ganache-cli --port 8545 --gasLimit 12000000 --accounts 10 --hardfork istanbul --mnemonic brownie'...
  File "brownie/_cli/run.py", line 50, in main
    return_value, frame = run(
  File "brownie/project/scripts.py", line 53, in run
    module = _import_from_path(script)
  File "brownie/project/scripts.py", line 149, in _import_from_path
    _import_cache[import_str] = importlib.import_module(import_str)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen, line line, in in
  File "<frozen, line line, in in
  File "<frozen, line line, in in
  File "<frozen, line line, in in
  File "<frozen, line line, in in
  File "<frozen, line line, in in
  File "./scripts/deploy.py", line 1, in <module>
    from brownie import account
ImportError: cannot import name 'account' from 'brownie' (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/brownie/__init__.py)
Terminating local RPC client...
```

**Comment by louisamira** [comment]
well this was fun, turns out `deploy_simple_storage` needed to be `deploy_simple_storage()` -- I found this with a couple print debug statements within `def deploy_simple_storage():` and realized we were never stepping into it ;(

**Comment by cromewar** [comment]
@louisamira yep, also my bad, I didn't notice it, but you are right when you call function you should use `()`, anyways I'm glad your problem is solved now ;)
