### ISSUE TITLE
brownie installation not possible: "brownie : command not found" after isntalling pipx and pip

### ISSUE THREAD

**Issue by CedricVo91** [smartcontractkit/full-blockchain-solidity-course-py#595]
Hey there, I installed the following successfully:

python3 -m pip install --user pipx
python3 -m pipx ensurepath

However, pipx install eth-brownie gives me "pipx not found". I then installed pip install eth-brownie successfully.
BUT for brownie --version it always gives me "brownie : command not found"

Help very much needed. Thank you

**Comment by cromewar** [comment]
closing this thread as is the same as here: https://github.com/smartcontractkit/full-blockchain-solidity-course-py/discussions
