### ISSUE TITLE
JavaScript version course

### ISSUE THREAD

**Issue by B-Tanvir** [smartcontractkit/full-blockchain-solidity-course-py#606]
**Can we know when the JavaScript Version of this course will be available? Thanks for this great course.**

**Comment by cromewar** [comment]
The version depends on the stnadarts on the browsers but they aren't something you can choose ans you choose other packages so there is not a command to get the version. But you are most likely using ES6/7 standard

**Comment by ryan-efendy** [comment]
Any update on this?

cc: @PatrickAlphaC

**Comment by PatrickAlphaC** [comment]
Sooner than you think, not as quick as you'd like ;)
