### ISSUE TITLE
Lesson 3: get the latest price

### ISSUE THREAD

**Issue by kayblock** [smartcontractkit/full-blockchain-solidity-course-py#625]
Hello!

I have been having trouble with getting this code to work to return the latest price.
` // SPDX-License-Identifier: MIT
pragma solidity ^0.8.7;

import "@chainlink/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol";

contract PriceConsumerV3 {

    AggregatorV3Interface internal priceFeed;

    /**
     * Network: Kovan
     * Aggregator: ETH/USD
     * Address: 0x9326BFA02ADD2366b30bacB125260Af641031331
     */
    constructor() {
        priceFeed = AggregatorV3Interface(0x9326BFA02ADD2366b30bacB125260Af641031331);
    }

    /**
     * Returns the latest price
     */
    function getLatestPrice() public view returns (int) {
        (
            uint80 roundID, 
            int price,
            uint startedAt,
            uint timeStamp,
            uint80 answeredInRound
        ) = priceFeed.latestRoundData();
        return price;
    }
}`
I opened the Solidity project in remix https://docs.chain.link/docs/get-the-latest-price/
I didn't change anything about the code, but when I deploy to live it says:
"This contract may be abstract, not implement an abstract parent's methods completely or not invoke an inherited contract's constructor correctly."
I have already:
Gotten Kovan
Compiled code
tried opening the code again
Not on the VM, it's switched to Injected Web3

Help is appreciated!

**Comment by kayblock** [comment]
Had a big "Ah Ha!" moment, I just forgot to switch the contract.

**Comment by polyglotguru1** [comment]
"Ah Ha" moment, for you and me too. Thank you for helping me to get over this hurdle. Regards.
