### ISSUE TITLE
Web3 installation probelm

### ISSUE THREAD

**Issue by patval7** [smartcontractkit/full-blockchain-solidity-course-py#646]
Hello, this error occurs when I insert pip install web3 into terminal. Where´s the problem? Thank you

` ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python38\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-ikzgq0wx\\cytoolz_0528fac94e9849038e8f44a33e5ac28e\\setup.py'"'"'; __file__='"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-ikzgq0wx\\cytoolz_0528fac94e9849038e8f44a33e5ac28e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Admin\AppData\Local\Temp\pip-record-ny841pb2\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\Admin\AppData\Roaming\Python\Python38\Include\cytoolz'
         cwd: C:\Users\Admin\AppData\Local\Temp\pip-install-ikzgq0wx\cytoolz_0528fac94e9849038e8f44a33e5ac28e\
    Complete output (53 lines):
    [1/5] Cythonizing cytoolz/utils.pyx
    [2/5] Cythonizing cytoolz/dicttoolz.pyx
    [3/5] Cythonizing cytoolz/functoolz.pyx
    [4/5] Cythonizing cytoolz/itertoolz.pyx
    [5/5] Cythonizing cytoolz/recipes.pyx
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\compatibility.py -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\_signatures.py -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\_version.py -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\__init__.py -> build\lib.win-amd64-3.8\cytoolz
    creating build\lib.win-amd64-3.8\cytoolz\curried
    copying cytoolz\curried\exceptions.py -> build\lib.win-amd64-3.8\cytoolz\curried
    copying cytoolz\curried\operator.py -> build\lib.win-amd64-3.8\cytoolz\curried
    copying cytoolz\curried\__init__.py -> build\lib.win-amd64-3.8\cytoolz\curried
    copying cytoolz\dicttoolz.pyx -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\functoolz.pyx -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\itertoolz.pyx -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\recipes.pyx -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\utils.pyx -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\cpython.pxd -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\dicttoolz.pxd -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\functoolz.pxd -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\itertoolz.pxd -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\recipes.pxd -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\utils.pxd -> build\lib.win-amd64-3.8\cytoolz
    copying cytoolz\__init__.pxd -> build\lib.win-amd64-3.8\cytoolz
    creating build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\dev_skip_test.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_compatibility.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_curried.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_curried_toolzlike.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_dev_skip_test.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_dicttoolz.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_docstrings.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_doctests.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_embedded_sigs.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_functoolz.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_inspect_args.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_itertoolz.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_none_safe.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_recipes.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_serialization.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_signatures.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_tlz.py -> build\lib.win-amd64-3.8\cytoolz\tests
    copying cytoolz\tests\test_utils.py -> build\lib.win-amd64-3.8\cytoolz\tests
    running build_ext
    building 'cytoolz.dicttoolz' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files\python38\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-ikzgq0wx\\cytoolz_0528fac94e9849038e8f44a33e5ac28e\\setup.py'"'"'; __file__='"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-ikzgq0wx\\cytoolz_0528fac94e9849038e8f44a33e5ac28e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Admin\AppData\Local\Temp\pip-record-ny841pb2\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\Admin\AppData\Roaming\Python\Python38\Include\cytoolz' Check the logs for full command output.`

**Comment by cromewar** [comment]
This is the cytools error, pretty common amongst windows users, there are yo path to go:

1. Install visual studio community and the python development tools on it, also in some cases is necessary to install another visual C++ libraries.
2. Change your workflow to WSL, you'll find a guide on the "windows support" section on the course index.

**Comment by patval7** [comment]
Thank you, it works!
