### ISSUE TITLE
KeyError in  'eth_usd_price_feed'

### ISSUE THREAD

**Issue by ShubhamBhut** [smartcontractkit/full-blockchain-solidity-course-py#656]
I am constantly facing  **KeyError: 'eth_usd_price_feed'** in "brownie_fund_me"; I thought that it might be issue in brownie-config.yaml, so I copy pasted whole file from this repo.; but still having same 

The error:
![Screenshot (111)](https://user-images.githubusercontent.com/82067144/147721201-5dcce518-8f2c-495f-b98d-de5a532f10d7.png)

Here is the code of deploy.py

```
from brownie import FundMe, network, config, MockV3Aggregator
from scripts.helpful_scripts import get_account

def deploy_fund_me():
   account = get_account()

   if network.show_active() != "development!":
      print("lol")
      price_feed_address = config["networks"][network.show_active()]["eth_usd_price_feed"]
   else:
      print(f"The active network is {network.show_active()}")
      print("Deploying Mocks...")
      mock_aggregator = MockV3Aggregator.deploy(18, 2000000000000000000000, {"from":account})
      price_feed_address = mock_aggregator.address
      print("Mocks deployed!")


   fund_me = FundMe.deploy(price_feed_address, {"from":account}, publish_source=config["network"][network.show_active()].get("verify"),)
   print(f"Huzzah, your contract has been deployed to {fund_me.address}")


def main():
   deploy_fund_me()
```

my brownie-config.yaml file
![Screenshot (110)](https://user-images.githubusercontent.com/82067144/147721261-9129568d-af03-43dc-abc7-ed9f4a5ff72e.png)

**Comment by cromewar** [comment]
hello @ShubhamBhut could you share which command you are using to deploy? you know, brownie run scripts/.... I'm interested on which network you are using.

**Comment by ShubhamBhut** [comment]
I am using ```brownie run scripts/deploy.py``` (you can see in top line of error image for reference) and I am trying to deploy it on rinkeby and on local ganache-cli as mock.

**Comment by cromewar** [comment]
Oh I see the error now, let me explain it to you.

The default network is `development` and when you use `brownie run scripts/deploy.py` you are going to use that one. So if you see your `brownie-config.yaml` you don't have the `eth_price_feed` on that network, you have to add one as same you have on rinkeby.

**Comment by ShubhamBhut** [comment]
Oh right, so I removed ```default``` from ```brownie-config.yaml``` and I edited ```brownie-config.yaml``` slightly as well as rewrite some of ```deploy.py```  (to cancel-out silly mistakes, if there were any previously)

Now, its working perfectly. Sharing my current ```brownie-config.yaml```, in case anyone face same error in future
![Screenshot (113)](https://user-images.githubusercontent.com/82067144/147807724-011158bd-52fd-4b9c-beca-5d0057ec7436.png)

Thank you very much @cromewar

**Comment by cromewar** [comment]
You are welcome.

**Comment by DarrenWayn** [comment]
suddenly when I relearn and build brownie fund from scratch I face this issue, I have already removed the default network but it still cant function. it confuses me because I already copy-paste all the right code from my previous project,

Do you know why this is happening? @cromewar

**Comment by DarrenWayn** [comment]
i fix it, I re add the ganache-local with 5777 network id instead of 1377, I thinks ganache is updated for some reason, and also I forgot to add ganache-local on LOCAL_BLOCKCHAIN_ENVIROMENTS
