### ISSUE TITLE
Lesson 6: Mainnet Forking Issue

### ISSUE THREAD

**Issue by saumyatrivedi14** [smartcontractkit/full-blockchain-solidity-course-py#669]
Whenever I run this brownie keeps throwing error and doesn't finish forking the mainnet.
I tripled check the cmd and still it doesn't work.
I have my Ganache GUI turned off as we are using ganache-cli here.
I can't spot the issue here. :/

```
brownie networks add development mainnet-fork -dev cmd=ganache-cli host=http://127.0.0.1 fork=https://eth-mainnet.alchemyapi.io/v2/0YVm__0Hxx5cy5bUmlLtDVU_DQZC_t9Z accounts=10 mnemonic=brownie port=8545
Brownie v1.17.2 - Python development framework for Ethereum

Usage: brownie networks <command> [<arguments> ...] [options]
```

Thanks in advance!

**Comment by cromewar** [comment]
Hello @saumyatrivedi14  Did you exported you alchemy private key to your env variables?

**Comment by saumyatrivedi14** [comment]
No, I didn't find any private key in alchemy account for the app I created. There's only HTTP and WEBSOCKETS links that I can see.

**Comment by cromewar** [comment]
Yes my bad, now I notice you have the -dev modifier, try without it.

**Comment by saumyatrivedi14** [comment]
yup, that worked out! Thanks!
