### ISSUE TITLE
Error after Deploying Mocks 

### ISSUE THREAD

**Issue by yellowcheese773** [smartcontractkit/full-blockchain-solidity-course-py#67]
Hello,
everything did work perfectly fine before I putted in the MockV3Aggregator. 

I exactly followed every step from Patrick, netherless when I do `brownie run scripts/deploy.py` I get this error: 

<img width="990" alt="Bildschirmfoto 2021-09-21 um 00 51 48" src="https://user-images.githubusercontent.com/80122924/134087309-c78b8b53-6c7d-4623-a873-d6e7dea60fcd.png">

Something I noticed is, that the Terminal also shows this  3 source Problems: 

<img width="1002" alt="Bildschirmfoto 2021-09-21 um 00 53 14" src="https://user-images.githubusercontent.com/80122924/134087462-30658584-e4e3-474a-81e3-8c37e90c0ed2.png">

The 2 source Problem in FundMe.sol didn't gave me trouble, everything worked, after MockV3Aggregator came, I had trouble.

Here is the deploy.py, just wanted to provide it, if it helps: 
 
<img width="1331" alt="Bildschirmfoto 2021-09-21 um 01 03 47" src="https://user-images.githubusercontent.com/80122924/134087869-10c6f926-6d96-4373-8da0-c226b644e516.png">

I would be really thankful for help.

**Comment by PatrickAlphaC** [comment]
Hmm... thanks for this issue. What does your config look like?

**Comment by imkrish7** [comment]
Brownie v1.16.4 - Python development framework for Ethereum

New compatible solc version available: 0.6.0
Compiling contracts...
  Solc version: 0.6.0
  Optimizer: Enabled  Runs: 200
  EVM Version: Istanbul
CompilerError: solc returned the following errors:

/home/rackham/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@1.1.1/contracts/src/v0.6/interfaces/AggregatorV2V3Interface.sol:7:38: TypeError: Interfaces cannot inherit.
interface AggregatorV2V3Interface is AggregatorInterface, AggregatorV3Interface
                                     ^-----------------^

/home/rackham/.brownie/packages/smartcontractkit/chainlink-brownie-contracts@1.1.1/contracts/src/v0.6/interfaces/AggregatorV2V3Interface.sol:7:59: TypeError: Interfaces cannot inherit.
interface AggregatorV2V3Interface is AggregatorInterface, AggregatorV3Interface

I am getting this after brownie compile

**Comment by imkrish7** [comment]
My issue is resolve by changing `pragma solidity >=0.6.0` in mockAggregatorV3Interface

**Comment by PatrickAlphaC** [comment]
Awesome! Thanks for following up.

**Comment by mindnumbe** [comment]
I had this issue as well. To clarify, interface inheritance was added after 0.6.0. If you get this error and notice brownie is compiling using a solc version <=0.6.0, then add this line to your brownie-config.yaml to force the more recent compiler

> compiler:
        solc:
       version: 0.6.6

**Comment by sanspeur33** [comment]
I made the above changes pragma solidity >=0.6.0; to FundMe, MockV3Aggregator and SafeMathChainlink, and now I get this error.  
Warning: Visibility for constructor is ignored. If you want the contract to be non-deployable, making it "abstract" is sufficient.
  --> contracts/FundMe.sol:15:5:
   |
15 |     constructor() public {
   |     ^ (Relevant source part starts here and spans across multiple lines).


TypeError: "send" and "transfer" are only available for objects of type "address payable", not "address".
  --> contracts/FundMe.sol:61:9:
   |
61 |         msg.sender.transfer(address(this).balance);
