### ISSUE TITLE
brownie.exceptions.VirtualMachineError: revert

### ISSUE THREAD

**Issue by DarrenWayn** [smartcontractkit/full-blockchain-solidity-course-py#723]
![image](https://user-images.githubusercontent.com/22322944/148514827-02e769e5-62ae-4065-9ef6-286245f96781.png)

![image](https://user-images.githubusercontent.com/22322944/148514794-015bea47-3f00-48b5-bff8-ba59bd954024.png)

brownie.exceptions.VirtualMachineError: revert after running brownie test --network mainnet-fork-dev
anybody know how to fix this?

**Comment by cromewar** [comment]
Hello @DarrenWayn could you please run the test using `-s` and share here the complete error message, something like this:

`brownie test -s -k test_name`

This will help us to see more in deep where the code is failing.

**Comment by DarrenWayn** [comment]
when I run brownie test -s -k test_can_fund_and_withdraw --network  mainnet-fork-dev this error but this test looks fine when I run using ganache local and rinkeby
![image](https://user-images.githubusercontent.com/22322944/148627860-ed53654c-4146-4746-9afc-3701525346cd.png)

![Uploading image.png…]()

**Comment by DarrenWayn** [comment]
hi @cromewar thanks for replying heres the test, when i run only brownie test it passed both of them. but when i used mainnet-for-dev this happen.

I run brownie test -s -k test_can_fund_and_withdraw --network mainnet-dev-fork

![image](https://user-images.githubusercontent.com/22322944/148627724-3dcd2634-3b4c-4b2c-8ab7-5f1237b6ec2c.png)


and when i run

**Comment by cromewar** [comment]
mainnet-fork-dev this could be the problem then, try deleting it, and add it again, look for any typo when adding the network, the host name should start with htpp.

Also, remember to add the mainnet-fork-dev to your brownie-config.yaml and helpful_scripts.

**Comment by DarrenWayn** [comment]
I tried to delete and add mainnet-fork-dev and it succeed but the result still the same
![image](https://user-images.githubusercontent.com/22322944/148637580-ce49c7e7-4631-4367-a861-e1ec92e23103.png)

![image](https://user-images.githubusercontent.com/22322944/148637613-c1284bdb-3d4f-439e-b243-a51ea1202160.png)

i used alchemy like patric suggested

**Comment by cromewar** [comment]
Changing the port might help, @PatrickAlphaC any clue on this one?

**Comment by AnneCh** [comment]
I'm stuck on the same level, I've also deleted and added mainnet-fork-dev, twice, closed the terminal, re-opened, my helpful_scripts and .yaml both have mainnet-fork-dev, and I'm still getinng ```     def test_can_fund_and_withdraw():
        account = get_account()
        fund_me = deploy_fund_me()
>       entrance_fee = fund_me.getEntranceFee() + 100
E       brownie.exceptions.VirtualMachineError: revert

tests/test_fund_me.py:10: VirtualMachineError 
```

ACTUALLY...

I've tried deleting and re-adding mainnet-fork-dev with a port of 7545, following @cromewar 's latest comment, and this time it passed, even though it took forever to run :

```
anne@AnneSager:~/Documents/Programming/brownie_fund_me-1$ brownie test --network mainnet-fork-devBrownie v1.17.2 - Python development framework for Ethereum

=================================================== test session starts ===================================================
platform linux -- Python 3.8.10, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/anne/Documents/Programming/brownie_fund_me-1
plugins: eth-brownie-1.17.2, hypothesis-6.27.3, web3-5.25.0, xdist-1.34.0, forked-1.3.0
collected 2 items                                                                                                         

Launching 'ganache-cli --fork https://eth-mainnet.alchemyapi.io/v2/SkU8ZfWFwHtJzwJNwrMCSy_ux1kEIXOS --port 7545 --hardfork istanbul'...

tests/test_fund_me.py .s                                                                                            [100%]

============================================== 1 passed, 1 skipped in 17.45s ==============================================
Terminating local RPC client...
```

@DarrenWayn  you may wanna try that out as well

**Comment by DarrenWayn** [comment]
I already used 7545 port from the bery begining, it confuse me why this didnt work

**Comment by AnneCh** [comment]
my bad, I didn't pay enough attention. and with port 8545 you got the same issue?

**Comment by cromewar** [comment]
@DarrenWayn please try with @AnneCh  solution (port 8545) .

**Comment by DarrenWayn** [comment]
@cromewar i re added mainnet-fork-dev with the port 8545 and it works, now I am wondering why it works? why not 7545

**Comment by AnneCh** [comment]
I'm also wondering, just for the sake of understanding the principle :)

**Comment by cromewar** [comment]
Your computer use a bunch of different ports to connect to different things on your pc, r port 7545 is for TCP protocol, you can find more information about it here: https://www.auditmypc.com/tcp-port-7545.asp
