### ISSUE TITLE
Lesson 6-raise TypeError(f"{abi['name']} requires no arguments") TypeError: constructor requires no arguments

### ISSUE THREAD

**Issue by AnneCh** [smartcontractkit/full-blockchain-solidity-course-py#724]
Hi!

I used to follow this lesson on a Windows 10 environment, but just switched to using Linux (Ubuntu 20.4).
I then proceeded to reinstall each program necessary to follow the lesson (I had been taking notes so I reinstalled them in the order they appeared in the video).

When typing program --version on my terminal, here is what comes back for each of them:
**NodeJs version v16.3.1
Python version Python 3.8.10
NPM version 8.3.0
Yarn version 1.22.17
Brownie version 1.17.2
Pip version pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
Pipx version 0.17.0
Ganache CLI v6.12.2 (ganache-core: 2.13.2)**

I copied-pasted the folders I had previously, made sure they were similar to the original ones from Patrick's repo. I had previously stopped, on Windows 10, at the pytest section, so I started running my compiler using `brownie compile`, which didn't work at first, but I made it work after messing with the solc version and the compiler, and then proceeded to try to run the first script I had made through `brownie run scripts/deploy.py`. The Mocks were deployed properly and I could see the block being created and my ETH spent on my local Ganache window.

But right after comes this error message:

```
anne@AnneSager:~/Documents/Programming/brownie_fund_me-1$ brownie run scripts/deploy.py
Brownie v1.17.2 - Python development framework for Ethereum

BrownieFundMe1Project is the active project.
/home/anne/.local/pipx/venvs/eth-brownie/lib/python3.8/site-packages/brownie/network/main.py:44: BrownieEnvironmentWarning: Development network has a block height of 13
  warnings.warn(
Attached to local RPC client listening at '127.0.0.1:8545'...

Running 'scripts/deploy.py::main'...
The active network is development
Deploying Mocks...
Transaction sent: 0x09fb13ebe9642ab578611e6fb03a7f0a340844c144c834cedc057e433b23830c
  Gas price: 0.0 gwei   Gas limit: 6721975   Nonce: 12
  MockV3Aggregator.constructor confirmed   Block: 14   Gas used: 430659 (6.41%)
  MockV3Aggregator deployed at: 0x79f6CdBCdFb5556cf0B8CFc8F496C0605b37Ccc9

Mocks Deployed!
  File "brownie/_cli/run.py", line 50, in main
    return_value, frame = run(
  File "brownie/project/scripts.py", line 103, in run
    return_value = f_locals[method_name](*args, **kwargs)
  File "./scripts/deploy.py", line 29, in main
    deploy_fund_me()
  File "./scripts/deploy.py", line 19, in deploy_fund_me
    fund_me = FundMe.deploy(
  File "brownie/network/contract.py", line 528, in __call__
    return tx["from"].deploy(
  File "brownie/network/account.py", line 509, in deploy
    data = contract.deploy.encode_input(*args)
  File "brownie/network/contract.py", line 557, in encode_input
    data = format_input(self.abi, args)
  File "brownie/convert/normalize.py", line 15, in format_input
    raise TypeError(f"{abi['name']} requires no arguments")
TypeError: constructor requires no arguments
```

**What I've tried**

I've run `brownie run scripts/deploy.py --network rinkeby` to see if the same issue happens, the error message is the same but the mocks aren't being deployed. I've looked at manually adding Rinkeby to the network list but haven't done it yet, as it doesn't seem like the crux of my issue (but is an issue that may not have anything to do with the Type Error constructor one).

I've run `brownie run scripts/deploy.py --network ganache-local` , and the exact same thing happened as when running `brownie run scripts/deploy.py` .

I've looked up what the error message means, I understand it has to do with the abi, I assume with a problem in getting the abi? but I can't understand where to go from that information.

I've then run Start Debugging on the deploy.py file, and the first error came from the first line : 
``` 
Exception has occurred: ImportError
cannot import name 'MockV3Aggregator' from 'brownie' (/home/anne/.local/lib/python3.8/site-packages/brownie/__init__.py)
  File "/home/anne/Documents/Programming/brownie_fund_me-1/scripts/deploy.py", line 1, in <module>
    from brownie import MockV3Aggregator, network, config, FundMe
  ```
(the same error comes on the helpful_scripts.py
I've tried changing the Aggregator version, copying/pasting the MockV3Aggregator.sol in the /brownie/ folder, didn't change anything (so I removed it).

I've checked that my **brownie-config.yaml** is correctly indented and the data is correct : 

```
dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@0.2.2
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.2"
dotenv: .env
networks:
  default: development
  rinkeby:
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    verify: False
  mainnet-fork-dev:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: False
  development:
    verify: False
  ganache-local:
    host: http://0.0.0.0:8545
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}

```

I've also noticed that when I run the code `brownie run scripts/deploy.py` , in brownie/build/contracts/dependencies/smartcontractkit/chainlink-brownie-contracts@0.2.2, 4 .json files have been created:
AggregatorInterface.json
AggregatorV2V3Interface.json
AggregatorV3Interface.json
SafeMathChainlink.json

My question is, is it normal that 3 different types of Aggregator Interface seem to be working at once? In Patrick's screenshot of his directory, it shows only one.

I've also noticed that in my build/contracts/deployments folder, the folder 8777 was correctly created and filled with the new contract address where the Mocks were deployed running on my ganache-local, but no folder was created when the mocks were created running on ganache-cli. Is it normal? 

I'll keep on digging up the issue, seems like it comes from the MockV3Aggregator and/or  AggregatorV2V3Interface, but any help would be greatly appreciated.

**Files for reference**

deploy.py
```
from brownie import MockV3Aggregator, network, config, FundMe
from scripts.helpful_scripts import (
    get_account,
    deploy_mocks,
    LOCAL_BLOCKCHAIN_ENVIRONMENTS,
)


def deploy_fund_me():
    account = get_account()
    if network.show_active() not in LOCAL_BLOCKCHAIN_ENVIRONMENTS:
        price_feed_address = config["networks"][network.show_active()][
            "eth_usd_price_feed"
        ]
    else:
        deploy_mocks()
        price_feed_address = MockV3Aggregator[-1].address

    fund_me = FundMe.deploy(
        price_feed_address,
        {"from": account},
        publish_source=config["networks"][network.show_active()].get("verify"),
    )
    print(f"Contract deployed to {fund_me.address}")
    return fund_me


def main():
    deploy_fund_me()

```

helpful_scripts.py

```
from brownie import network, config, accounts, MockV3Aggregator

FORKED_LOCAL_ENVIRONMENTS = ["mainnet-fork", "mainnet-fork-dev"]
LOCAL_BLOCKCHAIN_ENVIRONMENTS = ["development", "ganache-local"]
DECIMALS = 8
STARTING_PRICE = 200000000000


def get_account():
    if (
        network.show_active() in LOCAL_BLOCKCHAIN_ENVIRONMENTS
        or network.show_active() in FORKED_LOCAL_ENVIRONMENTS
    ):
        return accounts[0]
    else:
        return accounts.add(config["wallets"]["from_key"])


def deploy_mocks():
    print(f"The active network is {network.show_active()}")
    print("Deploying Mocks...")
    if len(MockV3Aggregator) <= 0:
        MockV3Aggregator.deploy(DECIMALS, STARTING_PRICE, {"from": get_account()})
    print("Mocks Deployed!")

```
FundMe.sol

```
// SPDX-License-Identifier: MIT

pragma solidity ^0.6.6;

import "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol";
import "@chainlink/contracts/src/v0.6/vendor/SafeMathChainlink.sol";

contract FundMe {
    using SafeMathChainlink for uint256;

    mapping(address => uint256) public addressToAmountFunded;
    address[] public funders;
    address public owner;

    constructor() public {
        owner = msg.sender;
    }

    function fund() public payable {
        uint256 minimumUSD = 50 * 10**18;
        require(
            getConversionRate(msg.value) >= minimumUSD,
            "You need to spend more ETH!"
        );
        addressToAmountFunded[msg.sender] += msg.value;
        funders.push(msg.sender);
    }

    function getVersion() public view returns (uint256) {
        AggregatorV3Interface priceFeed = AggregatorV3Interface(
            0x8A753747A1Fa494EC906cE90E9f37563A8AF630e
        );
        return priceFeed.version();
    }

    function getPrice() public view returns (uint256) {
        AggregatorV3Interface priceFeed = AggregatorV3Interface(
            0x8A753747A1Fa494EC906cE90E9f37563A8AF630e
        );
        (, int256 answer, , , ) = priceFeed.latestRoundData();
        return uint256(answer * 10000000000);
    }

    // 1000000000
    function getConversionRate(uint256 ethAmount)
        public
        view
        returns (uint256)
    {
        uint256 ethPrice = getPrice();
        uint256 ethAmountInUsd = (ethPrice * ethAmount) / 1000000000000000000;
        return ethAmountInUsd;
    }

    modifier onlyOwner() {
        require(msg.sender == owner);
        _;
    }

    function withdraw() public payable onlyOwner {
        msg.sender.transfer(address(this).balance);

        for (
            uint256 funderIndex = 0;
            funderIndex < funders.length;
            funderIndex++
        ) {
            address funder = funders[funderIndex];
            addressToAmountFunded[funder] = 0;
        }
        funders = new address[](0);
    }
}
```

**Comment by cromewar** [comment]
Hello @AnneCh  the error is simpler than you think, look a this, on your contract you have the constructor as this:

`
    constructor() public {
        owner = msg.sender;
    }
`

And on your deploy script to try to do this:

```Python
 fund_me = FundMe.deploy(
        price_feed_address,
        {"from": account},
        publish_source=config["networks"][network.show_active()].get("verify"),
    )
```

AS you can see your constructor has no arguments, and when you try to deploy it you are sending price_feed_address as one, so this could happend when you imported all from your previous installation, try fixing this and it should work.

**Comment by AnneCh** [comment]
Hi @cromewar ! Thank you so much, I realize what I've done, I had taken the code from https://github.com/PatrickAlphaC/fund_me/blob/main/FundMe.sol and that constructor didn't have the same arguments.

Indeed, much simpler than what I've thought ... problem solved, thank you !!

**Comment by cromewar** [comment]
I'm glad is solved now
