### ISSUE TITLE
Windows terminal can't locate subl file

### ISSUE THREAD

**Issue by chuukwuemeka** [smartcontractkit/full-blockchain-solidity-course-py#727]
Please guys help me fix this. My windows terminal is not locating my subl file but when I run it on cmd it works perfectly. please assist me. thanks

**Comment by cromewar** [comment]
Hello @chuukwuemeka could you please share more info about the error, screenshots would help a lot.

**Comment by chuukwuemeka** [comment]
Hi, I figured it out. Took me some hours of sleep. Thanks

**Comment by cromewar** [comment]
Could you share info about how you solved it, this might be helpful for the community :D
