### ISSUE TITLE
Error when defining priceFeed of type AggregatorV3Interface

### ISSUE THREAD

**Issue by wombyz** [smartcontractkit/full-blockchain-solidity-course-py#740]
Doing the brownie FundMe tutorial. For some reason the updated priceFeed method isn't working. I assume it is due to the import error thrown?

Here is error in terminal:

```
CompilerError: solc returned the following errors:

contracts/FundMe.sol:15:9: DeclarationError: Undeclared identifier. Did you mean "_priceFeed"?
        priceFeed = AggregatorV3Interface(_priceFeed);
        ^-------^

contracts/FundMe.sol:28:16: DeclarationError: Undeclared identifier.
        return priceFeed.version();
```

Screenshot of my code, should match that in the tut exactly?

<img width="781" alt="Screenshot 2022-01-09 at 9 08 47 PM" src="https://user-images.githubusercontent.com/26636388/148674438-06adb22a-990e-4836-9da2-4debdceedb5e.png">

Also my .yaml if needed:
<img width="641" alt="Screenshot 2022-01-09 at 9 12 11 PM" src="https://user-images.githubusercontent.com/26636388/148674556-76c01aa3-c111-4177-93c0-3977e425ddb8.png">

This person also had the same issues when compiling:
https://github.com/smartcontractkit/full-blockchain-solidity-course-py/issues/219

Been driving me crazy over the past 2 days, want to progress with the course but when you can't build, run and play around with things yourself then you don't really learn anything :(

Would really appreciate any advice!

Mentioned the import error more in this thread:
https://github.com/smartcontractkit/chainlink-brownie-contracts/issues/8

**Comment by DarrenWayn** [comment]
use 1.1.1 instead of 0.2.2

**Comment by wombyz** [comment]
Thanks guys. @DarrenWayn I only changed the version in an attempt to get the error to go away! 

@bot-eth-dev your solution worked thanks, was able to compile finally. 

However, it is quite annoying to have my whole screen lit up red because of the "File import callback not supported" error. I'm not even OCD but it grinds my gears.

Is there a way to silence these warnings as the program runs fine regardless? 

<img width="171" alt="Screenshot 2022-01-10 at 6 22 28 PM" src="https://user-images.githubusercontent.com/26636388/148721434-2a46a791-59b5-4170-8ab4-b53ce68a1d9c.png">

Thanks again for your help!

**Comment by wombyz** [comment]
Legend man thanks so much!
