### ISSUE TITLE
solc 0.6.0 has not been installed. Use solcx.install_solc('0.6.0') to install.

### ISSUE THREAD

**Issue by msperry2014** [smartcontractkit/full-blockchain-solidity-course-py#75]
Hello, newb here - in Visual Studio Code I am attempting to use Python to compile my solidity code (SimpleStorage.sol).  When I issue the command 'python deploy.py' I get the following error:

Traceback (most recent call last):
  File "D:\Documents\Projects\BlockChain\web3_py_simple_storage\deploy.py", line 9, in <module>
    compiled_sol = compile_standard(
  File "C:\Python39\lib\site-packages\solcx\main.py", line 368, in compile_standard
    solc_binary = get_executable(solc_version)
  File "C:\Python39\lib\site-packages\solcx\install.py", line 194, in get_executable
    raise SolcNotInstalled(
solcx.exceptions.SolcNotInstalled: solc 0.6.0 has not been installed. Use solcx.install_solc('0.6.0') to install.

  And this is my deploy.py:

`from solcx import compile_standard

with open("./SimpleStorage.sol", "r") as file:
    simple_storage_file = file.read()
    print(simple_storage_file)

# Compile our Solidity

compiled_sol = compile_standard(
    {
        "language": "Solidity",
        "sources": {"SimpleStorage.sol": {"content": simple_storage_file}},
        "settings": {
            "outputSelection": {
                "*": {"*": ["abi", "metadata", "evm.bytecode", "evm.sourcemap"]}
            }
        },
    },
    solc_version="0.6.0",
)
print(compiled_sol)`

  I have double checked that in Visual Studio Code that the 'workspace compiler version' is set to 'Remote' (as is global actually).  I have Python 3.9.7 installed, along with the Solidity extension (v0.0.125).  What am I missing?

**Comment by PatrickAlphaC** [comment]
Yep! This was addressed in this thread here: https://github.com/smartcontractkit/full-blockchain-solidity-course-py/discussions/5#discussion-3566046
