### ISSUE TITLE
erc20 token creation error 

### ISSUE THREAD

**Issue by Mbazu-Daniel** [smartcontractkit/full-blockchain-solidity-course-py#758]
i got this error while trying to deploy my ERC20 token, I tried changing the version of OpenZappelin on my brownie-config.yaml file but still did not. Please how can i fix this issue?
![brownie error](https://user-images.githubusercontent.com/69504364/148979493-04a33926-9b80-46f2-9815-68d427560998.png)

**Comment by cromewar** [comment]
Hello @Mbazu-Daniel could you please share the `brownie-config.yaml` and the contract code?

**Comment by Mbazu-Daniel** [comment]
brownie-config.yaml

dependencies:
  # - <organization/repo>@<version>
  - OpenZeppelin/openzeppelin-contracts@4.4.0"
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.0"
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
  
  
  
 contract
 
 pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract OurToken is ERC20 {
    constructor(uint256 initialSupply) ERC20("OurToken", "OT") {
        _mint(msg.sender, initialSupply);
    }
}

**Comment by Mbazu-Daniel** [comment]
![config](https://user-images.githubusercontent.com/69504364/149330044-b9ddb1ba-3cef-4921-805d-fb2996178154.png)
![contract](https://user-images.githubusercontent.com/69504364/149330048-fbe302c8-af80-4176-ac49-17aeebc2da15.png)

**Comment by cromewar** [comment]
Could you try using OppenZeppelin 4.3.2?

**Comment by Mbazu-Daniel** [comment]
I just did now and I got same error

**Comment by cromewar** [comment]
Let's try something different.

1. Delete the build folder of your porject.
2. delete the .brownie folder on your home directory (is a hidden folder if you are on mac or linux).
3. change to the latest version 4.4.2 and try again.

**Comment by Mbazu-Daniel** [comment]
Am using Windows OS

I still got same error after deleting build

**Comment by cromewar** [comment]
Did you delete the .brownie folder? is on c:/users/youruser, somehow your brownie is not working so try deleting it, and if still don't work then reinstall brownie.

**Comment by Mbazu-Daniel** [comment]
I did all of this and still does not work out for me

**Comment by cromewar** [comment]
In this case I'll highly recommend you:

1. Try using a virtual env of python.
2. change the version of python (3.8) is the best.
3. Use WSL instead .

**Comment by Mbazu-Daniel** [comment]
How do i go about the WSL usage?

**Comment by cromewar** [comment]
Yeah you are right, sometimes it happens when you are a programmer.
