### ISSUE TITLE
Git blocking Brownie compile...

### ISSUE THREAD

**Issue by wombyz** [smartcontractkit/full-blockchain-solidity-course-py#761]
Hi, 

I've just started the smartcontract-lottery project and was off to a roaring start before I was unable to compile due a what appeared to be a git issue.

Thinking I had setup the project wrong with github, I fully deleted the project on my computer and the repo to start fresh.

When compiling the next time I was met with the same issue.

Unsure why it would be connecting to github at all when I hadn't done anything to make a repo for the project, I disconnected my git and VS code account.

Same issue.

Now I'm extremely frustrated as I wanted to move ahead today but another silly issue has popped up that is unrelated to the course itself :(

Here is the error that pops up:

```
XXXXXXX@XXXXXXXX smartcontract-lottery % brownie compile
Brownie v1.16.4 - Python development framework for Ethereum

  File "brownie/_cli/__main__.py", line 64, in main
    importlib.import_module(f"brownie._cli.{cmd}").main()
  File "brownie/_cli/compile.py", line 50, in main
    proj = project.load()
  File "brownie/project/main.py", line 750, in load
    return Project(name, project_path)
  File "brownie/project/main.py", line 182, in __init__
    self.load()
  File "brownie/project/main.py", line 237, in load
    self._compile(changed, self._compiler_config, False)
  File "brownie/project/main.py", line 89, in _compile
    _install_dependencies(self._path)
  File "brownie/project/main.py", line 756, in _install_dependencies
    install_package(package_id)
  File "brownie/project/main.py", line 778, in install_package
    return _install_from_github(package_id)
  File "brownie/project/main.py", line 851, in _install_from_github
    raise ConnectionError(msg)
ConnectionError: Status 404 when getting package versions from Github: 'Not Found'

Missing or forbidden.
If this issue persists, generate a Github API token and store it as the environment variable `GITHUB_TOKEN`:
https://github.blog/2013-05-16-personal-api-tokens/
```
As for the solution provided by terminal, I set up my token in my .env and referenced it in my yaml as I'm supposed to but to no avail.

Any help would be greatly appreciated, has been doing my head in for hours now!

Cheers,

Liam

**Comment by KingBobushcka** [comment]
same issue, when i run 'brownie compile' i get:
Brownie v1.16.4 - Python development framework for Ethereum

Compiling contracts...
  Solc version: 0.6.6
  Optimizer: Enabled  Runs: 200
  EVM Version: Istanbul
CompilerError: solc returned the following errors:

contracts/Lottery.sol:4:1: ParserError: Source "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol" not found: File outside of allowed directories.
import "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol";
^--------------------------------------------------------------------------^

**Comment by KingBobushcka** [comment]
never-mind now. I dk what I changed. I was messing around in my config file though, so it had to be from there. compiles perfect now.
