### ISSUE TITLE
issue with brownie install

### ISSUE THREAD

**Issue by micaelaperillo** [smartcontractkit/full-blockchain-solidity-course-py#825]
I'm running win 10 64 bit and python 3.9.10. I followed the tutorial: first I installed pipx, then I ran ensurepath, restarted the terminal and finally installed brownie with pipx. When I try to verify that it worked, typing "brownie", I get this:
`'brownie' is not recognized as an internal or external command, operable program or batch file.`
When I try to run `pipx install eth-brownie` again, I get this:
`'eth-brownie' already seems to be installed. Not modifying existing installation in 'C:\\Users\\Usuario\\.local\\pipx\\venvs\\eth-brownie'. Pass '--force' to force installation.`
What did I miss and how can I fix it? Any help would be great!

**Comment by RonaldTang07** [comment]
Possibility 1. how did you restart terminal? If you are using code vs, simply closing the program and reopen will not restart the terminal, instead the previous session will be continued. You need to click the trash bin bottom in the terminal toolbar to close the terminal and reopen an new one.

Possibility 2. Do you have brownie added to your environment PATH variable? Brownie .exe is usually installed in python scripts folder, e.g. like in C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts can you find brownie.exe in that folder?

**Comment by micaelaperillo** [comment]
Brownie wasn't installed to my environmental PATH variable, now it works. Thanks!
