### ISSUE TITLE
Not attaching to rpc process

### ISSUE THREAD

**Issue by jamesspillman** [smartcontractkit/full-blockchain-solidity-course-py#833]
Anytime I run brownie console or brownie run scripts/deploy.py I get

Brownie v1.17.2 - Python development framework for Ethereum

BrowniesimplestorageProject is the active project.
File "brownie/_cli/main.py", line 64, in main
importlib.import_module(f"brownie._cli.{cmd}").main()
File "brownie/_cli/console.py", line 58, in main
network.connect(CONFIG.argv["network"])
File "brownie/network/main.py", line 48, in connect
rpc.attach(host)
File "brownie/network/rpc/init.py", line 113, in attach
pid = self._find_rpc_process_pid(resolved_addr)
File "brownie/network/rpc/init.py", line 194, in _find_rpc_process_pid
return self._get_pid_from_net_connections(laddr)
File "brownie/network/rpc/init.py", line 234, in _get_pid_from_net_connections
raise ProcessLookupError(
ProcessLookupError: Could not attach to RPC process by querying 'proc.net_connections()'

**Comment by cromewar** [comment]
Hello @jamesspillman 
this is more likely a problem with your python setup, here is some hints:

1. use python version 3.8
2. use a virtualenv for python.
3. Be sure your firewall is not blocking something on  your pc (8545 port related).

**Comment by jamesspillman** [comment]
Thank you, my firewall was blocking it

**Comment by capit0** [comment]
Hello guys, I have the same problem. However, I made an exception in my firewall for port 8545, but it didn't help. I also use python 3.8 and a virtualenv. Is there any other solution?

**Comment by cromewar** [comment]
@capit0 may be you have a unfinished process running, like a instance of ganache which didn't stop correctly, could you try restarting your computer and trying again?

**Comment by cromewar** [comment]
Well ok you give me a really good hint there, ig you already have ganache running it means that brownie is unable to rather connect to that instance or use one from itself.
Solo please be sure you have the correct ports and chainid into ganache.

chain id: 1337
port: 8545

**Comment by capit0** [comment]
That did not solve it I am afraid, it just keeps outputting the same error.

**Comment by capit0** [comment]
If it helps, there does seem to be some sort of interaction, because this is what I see in ganache.
![Schermafbeelding 2022-02-15 142028](https://user-images.githubusercontent.com/99099339/154070488-9efff1c3-00d4-46eb-b5e5-e38991802376.png)

**Comment by cromewar** [comment]
I'll need more info on this @capit0 
1. Which Os you are using?
2. is your firewall blocking ganache in any way?
3. the problem occurs just when you run deploy or also when you run brownie console?
