### ISSUE TITLE
Can't use py-socl-x

### ISSUE THREAD

**Issue by DieKant** [smartcontractkit/full-blockchain-solidity-course-py#84]
Hi everyone

I'm having a problem with the soclx tool, if I try to run python deploy.py (at 3:44:36 of this course) I get an error that says:

solcx.exceptions.SolcNotInstalled: solc 0.6.0 has not been installed. Use solcx.install_solc('0.6.0') to install.

So at this point I run python on my vs code terminal but when executing the command I get a new error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'solcx' is not defined

Not only, every soclx command outputs the same error as above
I checked with pip list and the soclx tool is in the list, I have followed word by word all the instructions but I can't see what I've done wrong

Does anyone had the same issue and know ho to fix this? Thanks

**Comment by DieKant** [comment]
problem was solved by reading the docs in the section of video fixes, i suggest that the errors reported in that section have to be reported in the youtube video with an edit to the correct timestamp

**Comment by Cpadilla229** [comment]
what docs and on what section do I read them? need help please same issue saying solcx not installed
