### ISSUE TITLE
Lesson 13: React - Changing code does not recompile the development server and does not refresh localhost page 

### ISSUE THREAD

**Issue by cherick04** [smartcontractkit/full-blockchain-solidity-course-py#849]
After creating the react app within the existing folder (`npx create-react-app front_end --template typescript`), installing `yarn` and running `yarn start`, absolutely nothing happens when I change the code in for example App.tsx, App.css, index.tsx, etc.
I've been trying to look for a solution in different forums but I'm not having any luck. It seems like there is no watchers checking if there is a change in the code, so the development server stays the same. I've tried runnig `npm start` and `yarn start` and no luck. 

I also tried adding a `.env` file next to package.json and tsconfig.json, setting the variables `FAST_REFRESH=false` and `CHOKIDAR_USEPOLLING=true` as per some recommendations in the forum, but still no luck.

```
OS: Windows 10, using WSL in Visual Studio Code v1.63.2
npm -v
8.1.4
node -v
v17.2.0
yarn -v
1.22.17
```

**Comment by MeLlamoValen** [comment]
I solved the problem moving the files from Windows to WSL

**Comment by MeLlamoValen** [comment]
You can open the wsl filesystem in explorer with \\wsl$, and then you can copy-paste all your project files there

**Comment by cherick04** [comment]
@MeLlamoValen, beautiful!!! not only did your suggestion solve my problem, I see the compilation time dropped significantly as well! You rock dude! Thanks :)

**Comment by MeLlamoValen** [comment]
Thank you! I'm glad I could help you :)
