### ISSUE TITLE
Strange behaviour of the buildTransaction method

### ISSUE THREAD

**Issue by DieKant** [smartcontractkit/full-blockchain-solidity-course-py#85]
Hi everyone

I don't seem to understand but I opened ganache and the network id is 5777 but when I print the transaction variable (4:00:28)
it gives me this error:

web3.exceptions.ValidationError: The transaction declared chain ID 5777, but the connected node is on 1337
![image](https://user-images.githubusercontent.com/61691496/134594995-859a293d-0c64-41b1-bd9e-57a42b9d9205.png)

When I change the id to 1337 it works just fine but I don't understand why it behaves like this, I would't like if it can become a bigger problem in the future so it's better to ask now

Thanks

**Comment by AlbertoSinigaglia** [comment]
Hi, ganache shows that ID, but believe me that is 1337... you can change it in the settings, but AFAIK, is some kind of legacy issue between `ganache-cli` and the Ganache GUI, you can find some reference [here](https://ethereum.stackexchange.com/questions/90385/the-endpoint-returned-a-different-chain-id-0x539-ganache/90759#90759)

**Comment by DieKant** [comment]
Grazie Alberto!, I'll mainly use the cli version from now on
