### ISSUE TITLE
VirtualMachineError: revert

### ISSUE THREAD

**Issue by Jaqck** [smartcontractkit/full-blockchain-solidity-course-py#850]
Hi, Currently completing lesson 6 and experiencing and error when attempting to run the test script or run the Fund_and_withdraw script. I am not however experiencing this error when running the deploy.py script. 

When running the fund me or test script I am receiving the below error:

         brownie.exceptions.VirtualMachineError: revert

..\..\..\AppData\Local\Programs\Python\Python310\lib\site-packages\brownie\network\contract.py:1533: VirtualMachineError

Any advice on how to resolve this would be great. I have searched online but don't seem to find the issue I am experiencing. Thanks, Jack.

**Comment by cromewar** [comment]
Hello @Jaqck Could you please share your contract code and the script one too?

**Comment by Jaqck** [comment]
Hi I managed to fix this. It was an issue with the import of the Ownable variable from Openzeppelin. Reinputting the import fixed this issue. Thanks :)

**Comment by cromewar** [comment]
I'm glad is solved now.
