### ISSUE TITLE
Lesson 6: NameError: name 'account' is not defined

### ISSUE THREAD

**Issue by karlMoreno** [smartcontractkit/full-blockchain-solidity-course-py#851]
Hi, I have this weird error that my account variable isn't defined despite it being defined earlier in the function and so I don't believe there should be an issue of scope. 

this is my code:
<img width="1679" alt="Screen Shot 2022-01-23 at 12 39 57 PM" src="https://user-images.githubusercontent.com/86685561/150697167-1f16f072-53d2-4549-93c0-99304a1fffa9.png">

and this is my error report:
<img width="1257" alt="Screen Shot 2022-01-23 at 12 40 42 PM" src="https://user-images.githubusercontent.com/86685561/150697197-6999131a-0f35-464f-aee9-d57e3d7963ea.png">

**Comment by cromewar** [comment]
Hello @karlMoreno 
The return statement of your get_account() function should be:
`return accounts[0]` with s

**Comment by karlMoreno** [comment]
Thank you so much!
