### ISSUE TITLE
solc_version not working (Visual Studio Code Mac OSX)

### ISSUE THREAD

**Issue by j-ananto** [smartcontractkit/full-blockchain-solidity-course-py#869]
Hello!

I followed the code from 3:44:46 on the youtube video but it gives me the error message:

```
  File "deploy.py", line 19
    solc_version = "0.6.0"
               ^
SyntaxError: invalid syntax`
```

**Python Code:**

```
from solcx import compile_standard

with open("./SimpleStorage.sol", "r") as file:
    simple_storage_file = file.read()
    print(simple_storage_file)


compiled_sol = compile_standard(
    {
        "language": "Solidity",
        "sources": {"SimpleSotrage.sol": {"content": simple_storage_file}},
        "settings": {
            "outputSelection": {
                "*" : {"*" : ["abi", "metadata", "evm.bytecode", "evm.sourceMap"]}                    
            }
        }
    }    
    solc_version = "0.6.0"
)
print(compiled_sol)
```

*Side note: pip does not work work for me when I run it. I have to use pip3. Not sure if this is the issue.

Thank you!

**Comment by cromewar** [comment]
Hello @j-ananto you are missing some commas, the code should like like this:

```Python
compiled_sol = compile_standard(
    {
        "language": "Solidity",
        "sources": {"SimpleStorage.sol": {"content": simple_storage_file}},
        "settings": {
            "outputSelection": {
                "*": {
                    "*": ["abi", "metadata", "evm.bytecode", "evm.bytecode.sourceMap"]
                }
            }
        },
    },
    solc_version="0.6.0",
)
```

Using pip3 is not an error, it just means you have both python2 and python3 installed and is selecting which one to use.

**Comment by j-ananto** [comment]
Hi @cromewar,

Thank you for replying. I adjusted the code accordingly, and now it's giving me the following error upon running deploy.py.

```
jeremyadamananto@Jeremys-MBP web3_py_simple_storage % python deploy.py
Traceback (most recent call last):
  File "deploy.py", line 1, in <module>
    from solcx import compile_standard
ImportError: No module named solcx
```
Even though I already installed the py-solc-x module as follows:

```
jeremyadamananto@Jeremys-MBP web3_py_simple_storage % pip3 install py-solc-x
Requirement already satisfied: py-solc-x in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (1.1.1)
Requirement already satisfied: requests<3,>=2.19.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from py-solc-x) (2.27.1)
Requirement already satisfied: semantic-version<3,>=2.8.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from py-solc-x) (2.8.5)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests<3,>=2.19.0->py-solc-x) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests<3,>=2.19.0->py-solc-x) (1.26.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests<3,>=2.19.0->py-solc-x) (2.0.10)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests<3,>=2.19.0->py-solc-x) (3.3)
WARNING: You are using pip version 21.2.4; however, version 22.0.2 is available.
You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10 -m pip install --upgrade pip' command.
```

**Comment by cromewar** [comment]
@j-ananto 
Remember to install py-solc-x: pip install py-solc-x
If you already have installed it, be sure to select the correct python interpreter on vscode (bottom left corner).

**Comment by j-ananto** [comment]
Hey @cromewar,

I'm sorry but I'm using Python 3.10.2 and still gives the same error. I also did install py-solc-x.
Thanks for the help.


![Screen Shot 2022-02-05 at 11 34 32 PM](https://user-images.githubusercontent.com/97825753/152671688-2174ce71-6640-436c-871c-d5631f5d8075.png)

**Comment by cromewar** [comment]
Is not recommended at all to use python 3.10 for now, it has a lot of incompatibilities with web3 libraries, I strongly  suggest you to use python 3.8 instead, give it a try ;)

**Comment by j-ananto** [comment]
Hi @cromewar,

It worked! After uninstalling Python 3.10 and installing Python 3.8.9 to match the Python Interpreter in VS Code, the code ran as it should, like in the video.

Also, I added a few lines of code, after finding this document posted by repository contributors:

https://github.com/smartcontractkit/full-blockchain-solidity-course-py/blob/main/chronological-issues-from-video.md 

Thanks for all the help!

**Comment by cromewar** [comment]
I'm glad is solved, closing this thread now.
