### ISSUE TITLE
Lesson 10 You have 0 worth of  ETH borrowed after I borrowed some DAI (9.40.29)

### ISSUE THREAD

**Issue by DarrenWayn** [smartcontractkit/full-blockchain-solidity-course-py#894]
![image](https://user-images.githubusercontent.com/22322944/151695975-c93f2ef7-8f63-4140-9e5c-f5a1add639b8.png)
is there anything wrong?

**Comment by DarrenWayn** [comment]
def get_asset_price(price_feed_address):
    # ABI
    # Address
    dai_eth_price_feed = interface.AggregatorV3Interface(price_feed_address)
    latest_price = dai_eth_price_feed.latestRoundData()[1]
    converted_latest_price = Web3.fromWei(latest_price, "ether")
    print(f"The DAI/ETH price is {converted_latest_price}")
    return float(converted_latest_price)
    # 0.000383355870000000

I fix it, the problem is i use  return float(latest_price) instead of  return float(converted_latest_price)

**Comment by cromewar** [comment]
I'm glad you solved it so fast, closing this thread now.
