### ISSUE TITLE
Adding a ganache-local on brownie

### ISSUE THREAD

**Issue by WyzzR** [smartcontractkit/full-blockchain-solidity-course-py#902]
When adding ganache-local to the network at 5:38:46, the host
> brownie network add Ethereum ganache-local host=http://0.0.0.0:8545 chainid=1337

Whereas brownie is listening on 127.0.0.1:8545. This lead to the error of get_account() having list index out of range error because it has an empty list.
Note: I also had to change ganache's server from 0.0.0.0 to 127.0.0.1

I've spent a long time trying to figure out the problem and almost gave up, would mean a lot if you could add it to the list of issues to help other people.

**Comment by cromewar** [comment]
Hello @WyzzR Please share the following:

1. the command you are using to add the network to brownie
2. a screenshot of your ganache ui.

**Comment by WyzzR** [comment]
At 5:39:01 the video said to type in `host=http://0.0.0.0:8545`

![2022-01-31(3)](https://user-images.githubusercontent.com/97843576/151757600-2b79a12e-c578-4ebb-8cd8-82f0de3d7230.png)

However 2 minutes before that, at 5:37:07, just where the cursor is it says `local RPC client listening '127.0.0.1:8545'`

![2022-01-31 (2)](https://user-images.githubusercontent.com/97843576/151758166-7a7d2e94-a658-4a21-9d17-6ccd5870c801.png)

This is weird because the ganache RPC server is at `http://0.0.0.0:8545` as you can see at 5:38:50 (after the previous picture)

![2022-01-31 (3)](https://user-images.githubusercontent.com/97843576/151758651-a75bb1d7-eddc-48ea-8518-c68136cd754c.png)



So my problem was that brownie was listening on `127.0.0.1:8545` but my ganache and the network settings on brownie was set to `0.0.0.0:8545`. The weird part is that in the video it works even though the RPC servers are different. 
I have been looking for ways to solve it but haven't found any so it seams that I am the only one to have this problem.

Hope this helps

**Comment by cromewar** [comment]
Depends on the operating system: 0.0.0.0 and 127.0.0.1 points to the same direction which is local host, but this is not always recognized by all OS. So you must just put what ever ganache throws you, not necessarily the exact same as Patrick.

So on your ganache, which ip is giving to you?

**Comment by WyzzR** [comment]
So here my ganache and the network I added to brownie is 0.0.0.0

![2022-01-31 (9)](https://user-images.githubusercontent.com/97843576/151807632-2b78a5c6-0ee7-4fa7-b519-eb0f0029cf21.png)

The problem is because the accounts is an empty list, I think. From the ss below, the object accounts works but when it try to call `accounts[0]` there is an out of index error.

![2022-01-31 (11)](https://user-images.githubusercontent.com/97843576/151807938-6845007a-28a1-4e00-a87f-6e883d76e4e5.png)

However if I keep the same code and change both brownie's and ganache host to 127.0.0.0 then it works

![2022-01-31 (13)](https://user-images.githubusercontent.com/97843576/151808956-dc1a4b86-5c41-4761-b124-19a8efae9b1a.png)



Also, a different problem, do you know why there is `INFO: Could not find files for the given pattern(s).` after every time I run a brownie command? It hasn't caused any problems but Patrick did not have it.

**Comment by WyzzR** [comment]
Sorry for the late reply, and thank you very much.
I'm just thinking that it caused me a lot of trouble and I could not find an answer anywhere, other people can also have the same problem. So maybe adding it to the list of issues would help newcomers. I guess that they can read this but I was new to github and didn't even know this existed.

Thank you again, you can probably close this.
