### ISSUE TITLE
Lesson 6: ValueError: Unknown URI - must be a path to an IPC socket, a websocket beginning with 'ws' or a URL beginning with 'http'

### ISSUE THREAD

**Issue by ARusDian** [smartcontractkit/full-blockchain-solidity-course-py#921]
I got problem when deploying the smartcontract with created networks,it says unknown URI, I have sets my ganache and it still wont working properly

##Here proof when i success making network
```
SUCCESS: A new network 'ganache-local' has been added
  └─ganache-local
    ├─id: ganache-local
    ├─chainid: 5777
    └─host: HTTP://0.0.0.0:8545

```
and then after i start the command 
`brownie run .\scripts\deploy.py --network ganache-local`

it shows error here
`Brownie v1.17.2 - Python development framework for Ethereum

BrowniefundmeProject is the active project.
  File "d:\belajarsolidity\solidityfcc\browniesimplestorage\venv\lib\site-packages\brownie\_cli\__main__.py", line 64, in main
    importlib.import_module(f"brownie._cli.{cmd}").main()
  File "d:\belajarsolidity\solidityfcc\browniesimplestorage\venv\lib\site-packages\brownie\_cli\run.py", line 44, in main
    network.connect(CONFIG.argv["network"])
  File "d:\belajarsolidity\solidityfcc\browniesimplestorage\venv\lib\site-packages\brownie\network\main.py", line 40, in connect
    web3.connect(host, active.get("timeout", 30))
  File "d:\belajarsolidity\solidityfcc\browniesimplestorage\venv\lib\site-packages\brownie\network\web3.py", line 66, in connect
    raise ValueError(
ValueError: Unknown URI - must be a path to an IPC socket, a websocket beginning with 'ws' or a URL beginning with 'http'`

please help me to understand why it isnt work properly

**Comment by WyzzR** [comment]
I think that the `http://0.0.0.0:8545` has to be lowercase.
Also, the `chainid` on my ganache was 1337 idk why its different for you and if are are having problems with the get_account() function change the host to `http://127.0.0.1:8545` on brownie and ganche.

I'm new here but a bit further than you in the video.
