### ISSUE TITLE
Can't install web3

### ISSUE THREAD

**Issue by MohamedZouh** [smartcontractkit/full-blockchain-solidity-course-py#96]
Hi, I try to install web3 but an error is accuring whatever the solution I try, I did a lot of searching in the net and the near issue that like to mine consiste as solution to install visuel studio build tools, but it didn't work with me, bellow you can see the error.
```
ERROR: Command errored out with exit status 1:
     command: 'c:\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\pc\\AppData\\Local\\Temp\\pip-install-uusfbzla\\varint_767bca6b5fd04b2eb5ebc4420507b387\\setup.py'"'"'; 
__file__='"'"'C:\\Users\\pc\\AppData\\Local\\Temp\\pip-install-uusfbzla\\varint_767bca6b5fd04b2eb5ebc4420507b387\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\pc\AppData\Local\Temp\pip-record-3m2pw_cn\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\python39\Include\varint'
         cwd: C:\Users\pc\AppData\Local\Temp\pip-install-uusfbzla\varint_767bca6b5fd04b2eb5ebc4420507b387\     
    Complete output (9 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib
    copying varint.py -> build\lib
    running install_lib
    byte-compiling c:\python39\Lib\site-packages\varint.py to varint.cpython-39.pyc
    error: [Errno 13] Permission denied: 'c:\\python39\\Lib\\site-packages\\__pycache__\\varint.cpython-39.pyc.1328308953584'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python39\python.exe' -u -c 'import io, os, sys, setuptools, 
tokenize; sys.argv[0] = '"'"'C:\\Users\\pc\\AppData\\Local\\Temp\\pip-install-uusfbzla\\varint_767bca6b5fd04b2eb5ebc4420507b387\\setup.py'"'"'; __file__='"'"'C:\\Users\\pc\\AppData\\Local\\Temp\\pip-install-uusfbzla\\varint_767bca6b5fd04b2eb5ebc4420507b387\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\pc\AppData\Local\Temp\pip-record-3m2pw_cn\install-record.txt' --single-version-externally-managed --compile
```
Can any one help me please.

**Comment by PatrickAlphaC** [comment]
Can you try `sudo` in front of that command? 

And what command is that?

**Comment by lowgrind** [comment]
https://www.youtube.com/watch?v=rcI1_e38BWs

i think this is exactly what you need. It helped me.

**Comment by MohamedZouh** [comment]
> Can you try `sudo` in front of that command?
> 
> And what command is that?

First thank you PatrickAlphaC for your answer.
concernenat sudo I think that It will not work because I use windows, and For The commande that I used is `pip3 install web3`

**Comment by MohamedZouh** [comment]
> https://www.youtube.com/watch?v=rcI1_e38BWs
> 
> i think this is exactly what you need. It helped me.

Thanks @lowgrind for your answer, I had already see that video, and I excute its solution but it didn't work.

**Comment by MohamedZouh** [comment]
I tried that command `python3 -m pip install web3`
In the console I get that response That I understand from that web3 is installed correctlly (see bellow):

- [ Collecting web3
  Downloading web3-5.24.0-py3-none-any.whl (487 kB)
     |████████████████████████████████| 487 kB 384 kB/s
Collecting eth-abi<3.0.0,>=2.0.0b6
  Using cached eth_abi-2.1.1-py3-none-any.whl (27 kB)
Collecting protobuf<4,>=3.10.0
  Using cached protobuf-3.18.0-cp39-cp39-win_amd64.whl (912 kB)
Requirement already satisfied: requests<3.0.0,>=2.16.0 in c:\users\pc\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from web3) (2.26.0)
Collecting eth-typing<3.0.0,>=2.0.0
  Using cached eth_typing-2.2.2-py3-none-any.whl (6.2 kB)
Collecting aiohttp<4,>=3.7.4.post0
  Using cached aiohttp-3.7.4.post0-cp39-cp39-win_amd64.whl (634 kB)
Collecting pywin32>=223
  Using cached pywin32-301-cp39-cp39-win_amd64.whl (9.3 MB)
Collecting eth-account<0.6.0,>=0.5.6
  Using cached eth_account-0.5.6-py3-none-any.whl (101 kB)
Collecting eth-utils<2.0.0,>=1.9.5
  Using cached eth_utils-1.10.0-py3-none-any.whl (24 kB)
Collecting lru-dict<2.0.0,>=1.1.6
  Using cached lru-dict-1.1.7.tar.gz (10 kB)
Collecting ipfshttpclient==0.8.0a2
  Using cached ipfshttpclient-0.8.0a2-py3-none-any.whl (82 kB)
Collecting hexbytes<1.0.0,>=0.1.0
  Using cached hexbytes-0.2.2-py3-none-any.whl (6.1 kB)
Collecting websockets<10,>=9.1
  Using cached websockets-9.1-cp39-cp39-win_amd64.whl (90 kB)
Collecting jsonschema<4.0.0,>=3.2.0
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting eth-hash[pycryptodome]<1.0.0,>=0.2.0
  Using cached eth_hash-0.3.2-py3-none-any.whl (8.8 kB)
Collecting multiaddr>=0.0.7
  Using cached multiaddr-0.0.9-py2.py3-none-any.whl (16 kB)
Collecting attrs>=17.3.0
  Using cached attrs-21.2.0-py2.py3-none-any.whl (53 kB)
Collecting multidict<7.0,>=4.5
  Using cached multidict-5.1.0-cp39-cp39-win_amd64.whl (48 kB)
Collecting typing-extensions>=3.6.5
  Using cached typing_extensions-3.10.0.2-py3-none-any.whl (26 kB)
Collecting chardet<5.0,>=2.0
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting yarl<2.0,>=1.0
  Using cached yarl-1.6.3-cp39-cp39-win_amd64.whl (125 kB)
Collecting async-timeout<4.0,>=3.0
  Using cached async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
Collecting parsimonious<0.9.0,>=0.8.0
  Using cached parsimonious-0.8.1.tar.gz (45 kB)
Collecting eth-rlp<2,>=0.1.2
  Using cached eth_rlp-0.2.1-py3-none-any.whl (5.0 kB)
Collecting rlp<3,>=1.0.0
  Using cached rlp-2.0.1-py2.py3-none-any.whl (20 kB)
Collecting eth-keyfile<0.6.0,>=0.5.0
  Using cached eth_keyfile-0.5.1-py3-none-any.whl (8.3 kB)
Collecting bitarray<1.3.0,>=1.2.1
  Using cached bitarray-1.2.2.tar.gz (48 kB)
Collecting eth-keys!=0.3.2,<0.4.0,>=0.2.1
  Using cached eth_keys-0.3.3-py3-none-any.whl (20 kB)
Collecting pycryptodome<4,>=3.6.6
  Using cached pycryptodome-3.10.4-cp35-abi3-win_amd64.whl (1.8 MB)
Collecting cytoolz<1.0.0,>=0.9.0
  Using cached cytoolz-0.11.0-cp39-cp39-win_amd64.whl (367 kB)
Collecting toolz>=0.8.0
  Using cached toolz-0.11.1-py3-none-any.whl (55 kB)
Requirement already satisfied: setuptools in c:\program files\windowsapps\pythonsoftwarefoundation.python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\site-packages (from jsonschema<4.0.0,>=3.2.0->web3) (57.4.0)
Collecting six>=1.11.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting pyrsistent>=0.14.0
  Using cached pyrsistent-0.18.0-cp39-cp39-win_amd64.whl (62 kB)
Collecting netaddr
  Using cached netaddr-0.8.0-py2.py3-none-any.whl (1.9 MB)
Collecting base58
  Using cached base58-2.1.0-py3-none-any.whl (5.6 kB)
Collecting varint
  Using cached varint-1.0.2.tar.gz (1.9 kB)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\pc\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests<3.0.0,>=2.16.0->web3) (2.0.6)      
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\pc\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests<3.0.0,>=2.16.0->web3) (1.26.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\pc\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests<3.0.0,>=2.16.0->web3) (3.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\pc\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests<3.0.0,>=2.16.0->web3) (2021.5.30)
Using legacy 'setup.py install' for bitarray, since package 'wheel' is not installed.
Using legacy 'setup.py install' for lru-dict, since package 'wheel' is not installed.
Using legacy 'setup.py install' for parsimonious, since package 'wheel' is not installed.
Using legacy 'setup.py install' for varint, since package 'wheel' is not installed.
Installing collected packages: toolz, eth-typing, eth-hash, cytoolz, six, eth-utils, varint, rlp, pycryptodome, parsimonious, netaddr, multidict, hexbytes, eth-keys, base58, yarl, typing-extensions, pyrsistent, multiaddr, eth-rlp, eth-keyfile, 
eth-abi, chardet, bitarray, attrs, async-timeout, websockets, pywin32, protobuf, lru-dict, jsonschema, ipfshttpclient, eth-account, aiohttp, web3
    Running setup.py install for varint ... done
    Running setup.py install for parsimonious ... done
  WARNING: The script netaddr.exe is installed in 'C:\Users\pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.       
  WARNING: The script base58.exe is installed in 'C:\Users\pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.       
  WARNING: The script chardetect.exe is installed in 'C:\Users\pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.       
    Running setup.py install for bitarray ... done
    Running setup.py install for lru-dict ... done
.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.       
Successfully installed aiohttp-3.7.4.post0 async-timeout-3.0.1 attrs-21.2.0 base58-2.1.0 bitarray-1.2.2 chardet-4.0.0 cytoolz-0.11.0 eth-abi-2.1.1 eth-account-0.5.6 eth-hash-0.3.2 eth-keyfile-0.5.1 eth-keys-0.3.3 eth-rlp-0.2.1 eth-typing-2.2.2 
eth-utils-1.10.0 hexbytes-0.2.2 ipfshttpclient-0.8.0a2 jsonschema-3.2.0 lru-dict-1.1.7 multiaddr-0.0.9 multidict-5.1.0 netaddr-0.8.0 parsimonious-0.8.1 protobuf-3.18.0 pycryptodome-3.10.4 pyrsistent-0.18.0 pywin32-301 rlp-2.0.1 six-1.16.0 toolz-0.11.1 typing-extensions-3.10.0.2 varint-1.0.2 web3-5.24.0 websockets-9.1 yarl-1.6.3
WARNING: You are using pip version 21.2.3; however, version 21.2.4 is available.
You should consider upgrading via the 'C:\Users\pc\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.
PS D:\Projets\python-projects\first-project> python3 -m pip install --upgrade pip
Requirement already satisfied: pip in c:\program files\windowsapps\pythonsoftwarefoundation.python.3.9_3.9.2032.0_x64__qbzCollecting pip
  Using cached pip-21.2.4-py3-none-any.whl (1.6 MB)
Installing collected packages: pip
  WARNING: The scripts pip.exe, pip3.9.exe and pip3.exe are installed in 'C:\Users\pc\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.       
Successfully installed pip-21.2.4
WARNING: You are using pip version 21.2.3; however, version 21.2.4 is available.
You should consider upgrading via the 'C:\Users\pc\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command] 

 but when I write `from web3 import web3` the compiler didn't recognize web3 to import from

**Comment by MohamedZouh** [comment]
It worked , using `python3 -m pip install web3`, I made sure by importing web3 in python3 console

**Comment by PatrickAlphaC** [comment]
Awesome work!!
